extern const GeoLayout totwc_entrance_001_switch_opt1[];
extern const GeoLayout totwc_entrance_geo[];
extern Lights1 totwc_entrance_sun_lights;
extern Lights1 totwc_entrance_light_lights;
extern Lights1 totwc_entrance_empty_lights;
extern u8 totwc_entrance__1_rgba16_ci8[];
extern u8 totwc_entrance__1_rgba16_pal_rgba16[];
extern u8 totwc_entrance_castle_light_ia16_ia8[];
extern Vtx totwc_entrance_000_displaylist_001_mesh_layer_1_vtx_0[9];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_1_tri_0[];
extern Vtx totwc_entrance_000_displaylist_001_mesh_layer_5_vtx_0[24];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_5_tri_0[];
extern Gfx mat_totwc_entrance_sun[];
extern Gfx mat_revert_totwc_entrance_sun[];
extern Gfx mat_totwc_entrance_light[];
extern Gfx mat_revert_totwc_entrance_light[];
extern Gfx mat_totwc_entrance_empty[];
extern Gfx mat_revert_totwc_entrance_empty[];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_1[];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_1_mat_override_empty_0[];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_5[];
extern Gfx totwc_entrance_000_displaylist_001_mesh_layer_5_mat_override_empty_0[];
extern Gfx totwc_entrance_material_revert_render_settings[];
