extern const GeoLayout crown_001_switch_opt1[];
extern const GeoLayout crown_001_switch_opt2[];
extern const GeoLayout crown_geo[];
extern Lights1 crown_f3dlite_material_lights;
extern u8 crown_Gold_ci8[];
extern u8 crown_Gold_pal_rgba16[];
extern u8 crown_silver_ci8[];
extern u8 crown_silver_pal_rgba16[];
extern u8 crown_bronze_ci8[];
extern u8 crown_bronze_pal_rgba16[];
extern Vtx crown_001_displaylist_mesh_layer_1_vtx_0[106];
extern Gfx crown_001_displaylist_mesh_layer_1_tri_0[];
extern Vtx crown_001_displaylist_mesh_layer_1_vtx_1[94];
extern Gfx crown_001_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_crown_f3dlite_material_001[];
extern Gfx mat_revert_crown_f3dlite_material_001[];
extern Gfx mat_crown_f3dlite_material[];
extern Gfx mat_revert_crown_f3dlite_material[];
extern Gfx mat_crown_f3dlite_material_002[];
extern Gfx mat_revert_crown_f3dlite_material_002[];
extern Gfx mat_crown_f3dlite_material_004[];
extern Gfx mat_revert_crown_f3dlite_material_004[];
extern Gfx crown_001_displaylist_mesh_layer_1[];
extern Gfx crown_001_displaylist_mesh_layer_1_mat_override_f3dlite_material_002_0[];
extern Gfx crown_001_displaylist_mesh_layer_1_mat_override_f3dlite_material_004_1[];
