extern const GeoLayout gcrown_geo[];
extern Lights1 gcrown_f3dlite_material_lights;
extern u8 gcrown_Gold_ci8[];
extern u8 gcrown_Gold_pal_rgba16[];
extern Vtx gcrown_000_displaylist_mesh_layer_1_vtx_0[111];
extern Gfx gcrown_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx gcrown_000_displaylist_mesh_layer_1_vtx_1[121];
extern Gfx gcrown_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_gcrown_f3dlite_material_001[];
extern Gfx mat_revert_gcrown_f3dlite_material_001[];
extern Gfx mat_gcrown_f3dlite_material[];
extern Gfx gcrown_000_displaylist_mesh_layer_1[];
