extern const GeoLayout scrown_geo[];
extern Lights1 scrown_f3dlite_material_lights;
extern u8 scrown_silver_ci8[];
extern u8 scrown_silver_pal_rgba16[];
extern Vtx scrown_000_displaylist_mesh_layer_1_vtx_0[111];
extern Gfx scrown_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx scrown_000_displaylist_mesh_layer_1_vtx_1[121];
extern Gfx scrown_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_scrown_f3dlite_material_001[];
extern Gfx mat_revert_scrown_f3dlite_material_001[];
extern Gfx mat_scrown_f3dlite_material[];
extern Gfx scrown_000_displaylist_mesh_layer_1[];
