langdata["en"] = -- the letters here will be what you type for the command (ex: to switch to this language, type "/lang en")
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "English",

  -- name in the built-in menu
  name_menu = "English",

  -- global command info
  to_switch = "Type \"/lang %s\" to switch languages",
  switched = "Switched to English!", -- Replace "English" with the name of this language
  rule_command = "Type /rules to show this message again",
  open_menu = "Type /mh or press %s to open the menu",
  stalk = "Use /stalk to warp to runners!",
  rules_desc = "- Shows MarioHunt rules",
  rules_desc_egg = "- Shows LuigiHunt rules",
  mh_desc = "[COMMAND,ARGS] - Runs commands; type nothing or \"menu\" to open the menu",
  lang_desc = "%s - Switch language",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Toggle hard mode for yourself",
  tc_desc = "[ON|OFF|MSG] - Send message to team only; turn ON to apply to all messages",
  stats_desc = "- Show/hide stat table",
  stalk_desc = "[NAME|ID] - Warps to the level the specified player is in, or the first Runner",
  spectate_desc = "[NAME|ID|OFF] - Spectate the specified player, free camera if not specified, or OFF to turn off", -- not to be confused with spectator_desc
  target_desc = "[NAME|ID] - Set this Runner as your target, which displays their location at all times.",
  gc_desc = "[MSG] - Send message that all players can see, even if you are dead; host/mod only",
  unsaved_changes = "\\#ff5a5a\\You have unsaved changes! Press again if you're sure.",

  -- roles
  runner = "Runner",
  runners = "Runners",
  short_runner = "Run", -- unused
  hunters = "Hunters",
  hunter = "Hunter",
  spectator = "Spectator",
  player = "Player",
  players = "Players",
  all = "All",
  dead = "Dead",
  opponents = "Opponents", -- only used for the show on map setting

  -- rules
  --[[
    This is laid out as follows:
    {welcome|welcome_mini}
    {runners}{shown_above|thats_you}{any_bowser|collect_bowser|mini_collect}
    {hunters}{thats_you}{all_runners|any_runners}
    {rule_lives_one|rule_lives}{time_needed|stars_needed}{become_hunter|become_runner}
    {infinite_lives}{spectate}
    {banned_glitchless|banned_general}{fun}

    I highly recommend testing this in-game
    Also:
    \\#ffffff\\ = white (default)
    \\#00ffff\\ = cyan (for Runner team name)
    \\#ff5a5a\\ = red (for Hunter team name and popups)
    \\#ffff5a\\ = yellow
    \\#5aff5a\\ = green
    \\#b45aff\\ = purple (for Extreme Mode)
  ]]
  welcome = "Welcome to \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! HOW TO PLAY:",
  welcome_mini = "Welcome to \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! HOW TO PLAY:",
  welcome_mys = "Welcome to \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! HOW TO PLAY:",
  welcome_egg = "Welcome to \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! HOW TO PLAY:",
  all_runners = "Defeat all \\#00ffff\\Runners\\#ffffff\\.",
  any_runners = "Defeat any \\#00ffff\\Runners\\#ffffff\\.",
  shown_above = "(shown above)",
  any_bowser = "Defeat %s through \\#ffff5a\\any\\#ffffff\\ means necessary.",
  collect_bowser = "Collect \\#ffff5a\\%d star(s)\\#ffffff\\ and defeat %s.",
  mini_collect = "Be the first to \\#ffff5a\\collect the star\\#ffffff\\.",
  collect_only = "Collect \\#ffff5a\\%d star(s)\\#ffffff\\.",
  thats_you = "(that's you!)",
  banned_glitchless = "NO: Cross teaming, BLJs, wall clipping, stalling, camping.", -- no longer used
  banned_general = "NO: Cross teaming, stalling, camping.",
  time_needed = "%d:%02d to leave any main stage; collect stars to decrease",
  stars_needed = "%d star(s) to leave any main stage",
  become_hunter = "become \\#ff5a5a\\Hunters\\#ffffff\\ when defeated",
  become_runner = "defeat a \\#00ffff\\Runner\\#ffffff\\ to become one",
  become_spectator = "become a \\#a9a9a9\\Spectator\\#ffffff\\ when defeated",
  infinite_lives = "Infinite lives",
  unless_defeated = "unless defeated by another player",
  spectate = "type \"/spectate\" to spectate",
  mini_goal = "\\#ffff5a\\Whoever collects the most stars in %d:%02d wins!\\#ffffff\\",
  fun = "Happy Hunting!",
  keep_secret = "Don't get caught!",
  mystery_altgoal = "OR: Discover the \\#ff5a5a\\Hunters\\#ffffff\\ and defeat them.",
  runners_can_kill =
  "\\#00ffff\\Runners\\#ffffff\\ can defeat players they suspect of being \\#ff5a5a\\Hunters\\#ffffff\\.\nIf they kill an innocent, they also die.",                    -- \n is a newline
  dead_become = "Dead \\#00ffff\\Runners\\#ffffff\\ leave behind a body.",
  dead_become_noconfirm = "Dead players leave behind a body.",
  dead_become_infection = "Dead players that don't become \\#ff5a5a\\Hunters\\#ffffff\\ leave behind a body.",
  report_info_rules = "Press %s to report them and discuss.",
  guard_info_rules = "Dead players can protect their teammates with %s.",
  sabo_info_rules = "\\#ff5a5a\\Hunters\\#ffffff\\ can also cause chaos with sabotages.\nTo disable a sabotage, go to the level listed and press %s on the sabotage.",

  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ win!", -- team name is placed here
  can_leave = "\\#5aff5a\\Can leave course",
  cant_leave = "\\#ff5a5a\\Can't leave course",
  time_left = "Can leave in \\#ffff5a\\%d:%02d",
  stars_left = "Need \\#ffff5a\\%d star(s)\\#ffffff\\ to leave",
  in_castle = "In castle",
  until_hunters = "%d second(s) until \\#ff5a5a\\Hunters\\#ffffff\\ begin",
  until_runners = "%d second(s) until \\#00ffff\\Runners\\#ffffff\\ begin",
  until_grace = "%d second(s) until grace period ends",
  until_cooldown = "%d second(s) until kill cooldown ends",
  lives_one = "1 life",
  lives = "%d lives",
  stars_one = "1 star",
  stars = "%d stars",
  no_runners = "No \\#00ffff\\Runners!",
  camp_timer = "Keep moving! \\#ff5a5a\\(%d)",
  game_over = "The game is over!",
  winners = "Winners: ",
  no_winners = "\\#ff5a5a\\No winners!",
  death_timer = "Death",
  mini_score = "Score: %d",
  new_record = "\\#ffff5a\\NEW RECORD!!!",
  on = "\\#5aff5a\\ON",
  off = "\\#ff5a5a\\OFF",
  frozen = "Frozen for %d",
  shuffle_timer = "Shuffling teams in %d",
  no_runners_here = "No \\#00ffff\\Runners\\#ffffff\\ here!",
  no_players_here = "No other players here!",

  -- popups
  lost_life = "%s\\#ffa0a0\\ lost a life!",
  lost_all = "%s\\#ffa0a0\\ lost all of their lives!",
  now_role = "%s\\#ffa0a0\\ is now a %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ got a star!",
  got_key = "%s\\#ffa0a0\\ got a key!",
  rejoin_start = "%s\\#ffa0a0\\ has two minutes to rejoin.",
  rejoin_success = "%s\\#ffa0a0\\ rejoined in time!",
  rejoin_fail = "%s\\#ffa0a0\\ did not reconnect in time.",
  leave_error = "%s\\#ffa0a0\\ left due to an error.",
  using_ee = "This is using Extreme Edition only.",
  not_using_ee = "This is using Standard Edition only.",
  killed = "%s\\#ffa0a0\\ killed %s!",
  sidelined = "%s\\#ffa0a0\\ finished off %s!",
  paused = "You have been paused.",
  unpaused = "You are no longer paused.",
  kill_combo_2 = "%s\\#ffa0a0\\ got a \\#ffff5a\\double\\#ffa0a0\\ kill!",
  kill_combo_3 = "%s\\#ffa0a0\\ got a \\#ffff5a\\triple\\#ffa0a0\\ kill!",
  kill_combo_4 = "%s\\#ffa0a0\\ got a \\#ffff5a\\quadruple\\#ffa0a0\\ kill!",
  kill_combo_5 = "%s\\#ffa0a0\\ got a \\#ffff5a\\quintuple\\#ffa0a0\\ kill!",
  kill_combo_large = "\\#ffa0a0\\Wow! %s\\#ffa0a0\\ got \\#ffff5a\\%d\\#ffa0a0\\ kills in a row!",
  set_hack = "Hack set to %s",
  incompatible_hack = "WARNING: Hack does not have compatibility!",
  vanilla = "Using vanilla game",
  omm_detected = "OMM Rebirth detected!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth is outdated!\\#ffffff\\\nMinimum version: %s\nYour version: %s",
  warp_spam = "Slow down with the warps!",
  no_valid_star = "Could not find a valid star!",
  custom_enter = "%s\\#ffffff\\ entered\n%s", -- same as coop
  vanish_custom = "Hold \\#ffff5a\\%s\\#ffffff\\ to avoid PVP attacks!",
  got_all_stars = "You have enough stars!",
  unstuck = "Attempted to fix state",
  use_out = "Use /mh out to warp everyone out of this level",
  stars_in_area = "%d star(s) available here!",
  demon_unlock = "Unlocked Green Demon mode!",
  hit_switch_red = "%s\\#ffa0a0\\ hit the\n\\#df5050\\Red Switch!",         -- dark red (unique)
  hit_switch_green = "%s\\#ffa0a0\\ hit the\n\\#50b05a\\Green Switch!",     -- dark green (unique)
  hit_switch_blue = "%s\\#ffa0a0\\ hit the\n\\#5050e3\\Blue Switch!",       -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ hit the\n\\#e3b050\\Yellow Switch...", -- orangeish (unique)
  mysteryhunt_disabled = "\\#ffa0a0\\One of your mods is not compatible with MysteryHunt!",
  mysteryhunt_spectate = "\\#ffa0a0\\You will spectate this game.",
  mysteryhunt_innocent = "\\#ffa0a0\\You killed an innocent player!",
  connected = "%s\\#ffff5a\\ connected!",                                  -- same as coop
  disconnected = "%s\\#ffa0a0\\ disconnected",                             -- same as coop
  report_body = "%s\\#ffa0a0\\ found %s's\\#ffa0a0\\ body in \\#ffff5a\\", -- "[Level Name]!" is added to the end
  global_talk_start = "\\#ffa0a0\\Global chat is enabled for %d second(s).",
  global_talk_end = "\\#ffa0a0\\Global chat has ended.",
  runners_remain = "%d \\#00ffff\\Runners\\#ffffff\\ remain.",
  runners_remain_one = "1 \\#00ffff\\Runner\\#ffffff\\ remains.",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Hunters\\#ffa0a0\\ remain.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Hunter\\#ffa0a0\\ remains.",
  players_remain = "\\#ffa0a0\\%d players remain.",
  players_remain_one = "\\#ffa0a0\\1 player remains.", -- will this even appear?
  other_hunters = "Other Hunters are: ",
  hunters_were = "The Hunters were: ",
  chara_left = "\\#ff0000\\* %d left.", -- easter egg
  chara_left_one = "\\#ff0000\\* 1 left.",

  -- command feedback
  not_mod = "You don't have the AUTHORITY to run this command, you fool!",
  no_such_player = "No such player exists",
  bad_id = "Invalid player ID!",
  command_disabled = "This command is disabled.",
  change_setting = "Setting change:",
  you_are_muted = "You are muted.",

  -- more command feedback
  bad_param = "Invalid parameters!",
  bad_command = "Invalid command!",
  error_no_runners = "Can't start game with 0 runners!",
  set_team = "%s's team has been set to '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "Game hasn't been started yet",
  set_lives_one = "%s now has 1 life",
  set_lives = "%s now has %d lives",
  not_runner = "%s isn't a Runner",
  may_leave = "%s may leave",
  must_have_one = "Must have at least 1 hunter",
  added = "Added runners: ", -- list comes afterward
  no_runners_added = "No Runners added",
  runners_are = "Runners are: ",
  hunters_set_count_one = "There is 1 hunter",
  hunters_set_count = "There are %d hunters",
  added_count_one = "Added 1 runner",
  added_count = "Added %d runners",
  set_lives_total = "Runner lives set to %d",
  wrong_mode = "Not available in this mode",
  need_time_feedback = "Runners can leave in %d second(s) now",
  game_time = "Game now lasts %d second(s)",
  need_stars_feedback = "Runners need %d star(s) now",
  new_category = "This is now a %d star run",
  new_category_any = "This is now an any% run",
  mode_normal = "In Normal mode",
  mode_swap = "In Swap mode",
  mode_mini = "In MiniHunt mode",
  mode_mys = "In MysteryHunt mode",
  using_stars = "Using stars collected",
  using_timer = "Using timer",
  can_spectate = "Hunters can now spectate",
  no_spectate = "Hunters can no longer spectate",
  all_paused = "All players paused",
  all_unpaused = "All players unpaused",
  player_paused = "%s has been paused",
  player_unpaused = "%s has been unpaused",
  hunter_metal = "All hunters are metal",
  hunter_normal = "All hunters appear normal",
  hunter_glow = "All hunters glow red",
  hunter_outline = "All hunters have an outline",
  hunter_color = "All hunters have the Burgundy palette",
  runner_sparkle = "All runners now sparkle",
  runner_normal = "All runners appear normal",
  runner_glow = "All runners now glow",
  runner_outline = "All runners have an outline",
  runner_color = "All runners have the Azure palette",
  now_weak = "All players have half invincibility frames",
  not_weak = "All players have normal invincibility frames",
  auto_on = "Games will start automatically",
  auto_off = "Games will not start automatically",
  force_spectate = "Everyone must spectate",
  force_spectate_off = "Spectate is no longer forced",
  force_spectate_one = "%s must spectate",
  force_spectate_one_off = "%s does not have to spectate anymore",
  blacklist_add = "Blacklisted %s",
  blacklist_remove = "Whitelisted %s",
  blacklist_add_already = "That star or level is already blacklisted.",
  blacklist_remove_already = "That star or level isn't blacklisted.",
  blacklist_remove_invalid = "Can't whitelist this star or level.",
  blacklist_list = "Blacklisted:",
  blacklist_reset = "Reset the blacklist!",
  blacklist_save = "Blacklist saved!",
  blacklist_load = "Blacklist loaded!",
  anarchy_set_0 = "Players cannot attack their teammates",
  anarchy_set_1 = "Runners can attack their teammates",
  anarchy_set_2 = "Hunters can attack their teammates",
  anarchy_set_3 = "Players can attack their teammates",
  dmgAdd_set = "Runners will now take %d extra damage from PVP attacks.",
  dmgAdd_set_ohko = "Runners will now die in one hit",
  voidDmg_set = "Players will take %d damage from falling into the void or quicksand.",
  voidDmg_set_ohko = "Players will instantly die from falling into the void or quicksand.",
  target_hunters_only = "Only Hunters can set a target.",
  muted = "\\#ffff00\\%s\\#ffffff\\ was muted by \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ was unmuted by \\#ffff00\\%s\\#ffffff\\.",
  you_muted = "You muted \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "You unmuted \\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ was muted automatically.",
  tc_only_hunter = "Only alive Hunters can use team chat.",
  scroll_up = "Scroll up for more...",

  -- team chat, nearby/far tag, and guard stuff
  tc_toggle = "Team chat is %s!",
  to_team = "\\#8a8a8a\\To team: ",
  from_team = "\\#8a8a8a\\ (team): ",
  nearby = "\\#8a8a8a\\(nearby)",
  far = "\\#8a8a8a\\(far)",
  guard_save = "\\#ffff00\\A ghost saved you from death!",
  guard_info = "Press %s to guard %s", -- first is a button, second is a name
  guard_timer = "%s\\#ffff00\\ is guarded (%d)",
  guard_cooldown = "Can guard in %d",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ voted to skip this star",
  vote_info = "Type /skip to vote",
  vote_pass = "The vote passed!",
  already_voted = "You've already voted.",

  -- sabotage
  sabo_bomb = "\\#ff4040\\Mega Bomb",
  sabo_bomb_desc = "Kills all players if not disabled!",
  sabo_gas = "\\#ffff32\\Toxic Gas",
  sabo_gas_desc = "Makes toxic gas appear!",
  sabo_dark = "\\#5050ff\\Darkness",
  sabo_dark_desc = "Covers the world in darkness!",
  sabo_active = "\\#ffff00\\SABOTAGE ACTIVE!",
  sabo_bomb_timer = "\\#ff4040\\Everyone will die in %d:%02d",
  sabo_info = "Press %s to sabotage",
  sabo_cooldown = "Can sabotage in %d:%02d",
  sabo_activate_timer = "Activating in %d",
  press_report = "%s - Report",
  press_fix = "%s - Fix",

  -- hard mode
  hard_notice = "Psst, try typing /hard...",
  extreme_notice = "Psst, try typing /hard ex...",
  hard_toggle = "\\#ff5a5a\\Hard Mode\\#ffffff\\ is %s!",
  extreme_toggle = "\\#b45aff\\Extreme Mode\\#ffffff\\ is %s!",
  hard_info = "Interested in \\#ff5a5a\\Hard Mode\\#ffffff\\?" ..
      "\n- Half health" ..
      "\n- No water heal" ..
      "\n- \\#ff5a5a\\One life" ..
      "\n\\#ffffff\\Type /hard ON if you're up for the challenge.",
  extreme_info = "Are you drawn to \\#b45aff\\Extreme Mode\\#ffffff\\? How foolish." ..
      "\n- One life" ..
      "\n- One health" ..
      "\n- \\#b45aff\\Death Timer\\#ffffff\\; collect coins and stars to increase" ..
      "\nIf this doesn't scare you, type /hard ex ON.",
  no_hard_win = "Your Hard Wins or Extreme Wins score will not be updated for this game.",
  hard_mode = "Hard Mode",
  extreme_mode = "Extreme Mode",
  hard_info_short = "Half health, no water heal, and one life.",
  extreme_info_short = "One health, one life, and death timer.",

  -- spectator
  hunters_only = "Only Hunters can spectate!",
  spectate_disabled = "Spectate is disabled!",
  timer_going = "Can't spectate during timer!", -- now unused
  spectate_self = "Can't spectate yourself!",
  spectator_controls = "Controls:" ..
      "\nDPAD-UP: Turn off hud" ..
      "\nDPAD-DOWN: Swap freecam/player view" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Switch player" ..
      "\nJOYSTICK: Move" ..
      "\nA: Go up" ..
      "\nZ: Go down" ..
      "\nType \"/spectate OFF\" to cancel",
  spectate_off = "No longer spectating.",
  empty = "EMPTY (%d )",
  free_camera = "FREE CAMERA",
  spectate_mode = "- SPECTATOR MODE -",
  is_spectator = '* PLAYER IS A SPECTATOR  *',

  -- stats
  disp_wins_one = "%s\\#ffffff\\ has won 1 time as \\#00ffff\\Runner\\#ffffff\\!",
  disp_wins = "%s\\#ffffff\\ has won %d times as \\#00ffff\\Runner\\#ffffff\\!",
  disp_kills_one = "%s\\#ffffff\\ has killed 1 player!", -- unused
  disp_kills = "%s\\#ffffff\\ has killed %d players!",
  disp_wins_hard_one = "%s\\#ffffff\\ has won 1 time as \\#ffff5a\\Runner\\#ffffff\\ in \\#ff5a5a\\Hard Mode!\\#ffffff\\",
  disp_wins_hard = "%s\\#ffffff\\ has won %d times as \\#ffff5a\\Runner\\#ffffff\\ in \\#ff5a5a\\Hard Mode!\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ has won 1 time as \\#b45aff\\Runner\\#ffffff\\ in \\#b45aff\\Extreme Mode!\\#ffffff\\",
  disp_wins_ex = "%s\\#ffffff\\ has won %d times as \\#b45aff\\Runner\\#ffffff\\ in \\#b45aff\\Extreme Mode!\\#ffffff\\",
  disp_asn_quarter = "%s\\#ffffff\\ reached the \\#70ff94\\quarter-finals\\#ffffff\\ in the ASN Tourney!",
  disp_asn_bronze = "%s\\#ffffff\\ got \\#b38752\\bronze\\#ffffff\\ in the ASN Tourney!",
  disp_asn_silver = "%s\\#ffffff\\ got \\#c5d8de\\silver\\#ffffff\\ in the ASN Tourney!",
  disp_asn_win = "%s \\#e3bc2d\\won\\#ffffff\\ the ASN Tourney!",
  -- for stats table
  stat_wins_standard = "Wins",
  stat_wins = "Wins (Minihunt/pre v2.3)",
  stat_wins_mys = "Wins (MysteryHunt)",
  stat_kills = "Kills",
  stat_combo = "Max Kill Streak",
  stat_wins_hard_standard = "Wins (Hard Mode)",
  stat_wins_hard = "Wins (Hard Mode, MiniHunt/pre v2.3)",
  stat_wins_hard_mys = "Wins (Hard Mode, MysteryHunt)",
  stat_mini_stars = "Maximum Stars in one game of MiniHunt",
  stat_placement = "64 Tour Placement",
  stat_wins_ex_standard = "Wins (Extreme Mode)",
  stat_wins_ex = "Wins (Extreme Mode, MiniHunt/pre v2.3)",
  stat_wins_ex_mys = "Wins (Extreme Mode, MysteryHunt)",
  stat_playtime = "Playtime (Hours)",
  stat_parkour_time = "Fastest Parkour Time",
  stat_parkour_time_omm = "Fastest Parkour Time (OMM)",
  stat_parkour_time_other = "Fastest Parkour Time (Moveset)",
  stat_placement_asn = "ASN Tourney Placement",
  stat_crown = "ASN Crown", -- planned for use in "Hide My Roles"

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1st Place]",
  place_2 = "\\#c5d8de\\[64T: 2nd Place]",
  place_3 = "\\#b38752\\[64T: 3rd Place]",
  place = "\\#e7a1ff\\[64T: %dth Place]", -- thankfully we don't go up to 21
  place_asn_1 = "\\#e3bc2d\\[ASN Winner]",
  place_asn_2 = "\\#c5d8de\\[ASN Silver]",
  place_asn_3 = "\\#b38752\\[ASN Bronze]",
  place_asn_4 = "\\#70ff94\\[ASN Quarter-Finalist]",
  place_asn = "\\#e7a1ff\\[ASN Participant]",
  place_score_1 = "%dst",
  place_score_2 = "%dnd",
  place_score_3 = "%drd",
  place_score = "%dth",

  -- chat roles
  role_lead = "\\#9a96ff\\[Lead MH Dev]",
  role_dev = "\\#96ecff\\[MH Dev]",
  role_cont = "\\#ff9696\\[MH Contributor]",
  role_trans = "\\#ffd996\\[MH Translator]",
  role_dead = "\\#ff2020\\[DEAD]",

  -- command descriptions
  page = "\\#ffff5a\\Page %d/%d", -- page for mariohunt command
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Starts the game; add \"continue\" to not warp to start; add \"alt\" for alt save file; add \"main\" for main save file; add \"reset\" to reset file",
  add_desc = "[INT] - Adds the specified amount of runners at random",
  random_desc = "[INT] - Picks the specified amount of runners at random",
  random_desc_hunt = "[INT] - Picks the specified amount of hunters at random",
  lives_desc = "[INT] - Sets the amount of lives Runners have, from 0 to 99 (note: 0 lives is still 1 life)",
  time_desc =
  "[NUM] - Sets the amount of time Runners have to wait to leave, in seconds, or the length of the game in MiniHunt.",
  stars_desc = "[INT] - Sets the amount of stars Runners must collect to leave, from 0 to 7 (only in star mode)",
  category_desc = "[INT] - Sets the amount of stars Runners must have to face Bowser.",
  flip_desc = "[NAME|ID] - Flips the team of the specified player",
  setlife_desc = "[NAME|ID|INT,INT] - Sets the specified lives for the specified runner",
  leave_desc = "[NAME|ID] - Allows the specified player to leave the level if they are a runner",
  mode_desc = "[NORMAL|SWAP|MINI] - Changes game mode; Swap switches runners when one dies",
  starmode_desc = "[ON|OFF] - Toggles using stars collected instead of time",
  spectator_desc = "[ON|OFF] - Toggles Hunters' ability to spectate",
  pause_desc = "[NAME|ID|ALL] - Toggles pause status for specified players, or all if not specified",
  hunter_app_desc = "Changes the appearance of Hunters.",
  runner_app_desc = "Changes the appearance of Runners.",
  hack_desc = "[STRING] - Sets current rom hack",
  weak_desc = "[ON|OFF] - Cuts invincibility frames in half for all players",
  auto_desc = "[ON|OFF|NUM] - Start games automatically",
  forcespectate_desc = "[NAME|ID|ALL] - Toggle forcing spectate for this player or all players",
  desync_desc = "- Attempts to fix desync errors",
  stop_desc = "- Stop the game",
  default_desc = "- Set settings to default",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Blacklist stars in MiniHunt",
  stalking_desc = "[ON|OFF] - Allow warping to a Runner's level with /stalk",
  mute_desc = "[NAME|ID] - Mutes a player, preventing them from chatting",
  unmute_desc = "[NAME|ID] - Unmutes a player, allowing them to chat again",
  out_desc = "[LEVEL|COURSE] - Kicks everyone out of this level",
  preset_desc = "[SAVE|LOAD|DELETE|RENAME] - Manage custom setting presets.",

  -- Blocky's menu
  main_menu = "Main Menu",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  menu_settings_player = "Preferences",
  menu_rules = "Rules",
  menu_list_settings = "List Settings",
  menu_list_settings_desc = "Lists all settings for this lobby.",
  menu_lang = "Language",
  menu_misc = "Misc.",
  menu_stats = "Stats",
  menu_back = "Back",
  menu_exit = "Exit",

  menu_run_random = "Randomize Runners",
  menu_run_add = "Add Runners",
  menu_hunt_random = "Randomize Hunters",
  menu_run_lives = "Runner Lives",
  menu_settings = "Game Settings",

  menu_start = "Start",
  menu_stop = "Stop",
  menu_save_main = "Main",
  menu_save_alt = "Alt Save",
  menu_save_reset = "Reset Alt Save",
  menu_save_continue = "Continue (no warping back)",
  menu_random = "Random",
  menu_campaign = "Campaign",
  menu_coop = "Coop", -- unused

  menu_gamemode = "Gamemode",
  menu_hunter_app = "Hunter Appearance",
  menu_runner_app = "Runner Appearance",
  menu_weak = "Weak Mode",
  menu_allow_spectate = "Allow Spectating",
  menu_star_mode = "Star Mode",
  menu_category = "Category",
  menu_time = "Time",
  menu_stars = "Stars",
  menu_auto = "Auto Game",
  menu_blacklist = "MiniHunt Blacklist",
  menu_default = "Reset to Defaults",
  menu_anarchy = "Friendly Fire",
  menu_anarchy_desc = "Allows the specified teams to attack their teammates.",
  menu_dmgAdd = "Runner PVP DMG Up",    -- DMG is "damage"
  menu_dmgAdd_desc = "Add this much damage to attacks against Runners.",
  menu_nerf_vanish = "Nerf Vanish Cap", -- Nerf, as in to reduce power for balancing
  menu_nerf_vanish_desc = "Nerfs vanish cap by making it vulnerable to PVP attacks, unless a button is held.",
  menu_first_timer = "Leader Death Timer",
  menu_first_timer_desc = "Gives the leader in MiniHunt a death timer.",
  menu_defeat_bowser = "Defeat %s",
  menu_allow_stalk = "Allow 'Stalking'",
  menu_countdown = "Countdown",
  menu_countdown_desc = "How long Hunters must wait before starting.",
  menu_voidDmg = "Void DMG",
  menu_voidDmg_desc = "Damage dealt to players falling into the void or quicksand.",
  menu_double_health = "Double Health",
  menu_double_health_desc = "Players get 16 points of health instead of 8.",
  menu_free_roam = "Free Roam",
  menu_free_roam_desc = "Disables Star and Key requirements for doors and most levels.",
  menu_star_heal = "Star Heal",
  menu_stalk_timer = "Stalk Cooldown",
  menu_stalk_timer_desc = "Time the player is frozen for after using /stalk.",
  menu_star_setting = "On star collection",
  menu_star_stay_old = "Stay If Already Collected",
  menu_star_stay_old_desc = "Collecting a star that has already been collected will not eject you from the level.",
  menu_spectate_on_death = "Runners Spectate On Death",
  menu_shuffle = "Team Shuffle",
  menu_shuffle_desc = "Shuffles the teams of every alive player in the selected amount of time",
  menu_confirm_hunter = "Confirm Hunter Deaths",
  menu_confirm_hunter_desc =
  "Displays a message whenever a Hunter is killed. If disabled, Hunters also leave behind corpses.",
  menu_global_chat = "Global Chat Time",
  menu_global_chat_desc = "Time players can speak when a body is found.",
  menu_grace_period = "Grace Period",
  menu_grace_period_desc = "Time until players can be killed.",
  menu_know_team = "Hunters Know Teammates",
  menu_know_team_desc = "Hunters know who their teammates are. If disabled, Hunters can also kill each other.",
  menu_hunters_win_early = "Hunters Win Early",
  menu_hunters_win_early_desc = "Hunters win when they match/exceed the amount of Runners, like in Among Us.",
  menu_show_on_map = "Show On Map",
  menu_show_on_map_desc = "Which teams can be seen on the minimap (Opponents will also have the radar)",
  menu_game_area = "Game Area",
  menu_game_area_desc = "Which parts of the game are accessible. Use \"Default\" for all levels.",
  menu_pvp_type = "PvP Mode",
  menu_pvp_type_desc = "Change how PvP works (same as the server setting). \"Revamped\" buffs slide kicks and allows punch combos, among other things.",
  menu_no_player_col = "Disable Player Collision",
  menu_no_player_col_desc = "Prevents players from bouncing or pushing eachother around. PvP still works!",
  menu_default_role = "Default Role",
  menu_default_role_desc = "Which team is assigned to new players.",
  menu_no_water_heal = "No Water Heal",
  menu_invis_wall_fix = "Fix Invisible Walls",
  menu_invis_wall_fix_desc = "Removes most invisible walls from the game. Also fixes some other collision issues, but shouldn't impact most games.",
  menu_presets = "Presets",
  menu_sabo = "Sabotage",
  star_leave = "Leave",
  star_stay = "Stay",
  star_nonstop = "Non-Stop",
  pvp_type_classic = "Classic",
  pvp_type_revamped = "Revamped",
  default = "Default",

  menu_flip = "Flip Team",
  menu_spectate = "Spectate",
  menu_stalk = "Warp To Level",
  menu_stalk_desc = "Warp to this player's level.",
  menu_pause = "Pause",
  menu_forcespectate = "Force to Spectate",
  menu_allowleave = "Allow to Leave",
  menu_setlife = "Set Lives",
  menu_players_all = "All Players",
  menu_target = "Set as Target",
  menu_mute = "Mute",

  menu_timer = "Speedrun Timer",
  menu_timer_desc = "[ON|OFF] - Show a timer at the bottom of the screen in Standard modes.",
  menu_tc = "Team Chat",
  menu_tc_desc = "Chat only with your team.",
  menu_demon = "Green Demon", -- referring to the 1-Up
  menu_demon_desc = "Have a 1-Up chase you as Runner.",
  menu_unknown = "???",
  menu_secret = "This is a secret. How do you unlock it?",
  menu_hide_roles = "Hide My Roles",
  menu_hide_roles_desc = "Hide your roles from displaying in chat.",
  menu_hide_hud = "Hide HUD",
  hidehud_desc = "- Hide all HUD elements.",
  menu_fast = "Faster Actions",
  menu_fast_desc = "You will recover, throw objects, and open doors faster.",
  menu_popup_sound = "Popup Sounds",
  menu_season = "Seasonal Changes",
  menu_season_desc = "Fun visual changes depending on the date.",
  menu_radar = "Radar",
  menu_radar_desc = "Shows where Runners and important objects are.",
  menu_minimap = "Minimap",
  menu_minimap_desc = "Shows a map of the whole level.",
  menu_romhack_cam = "Romhack Cam",                               -- (cam is short for camera)
  menu_romhack_cam_desc = "Enables romhack camera at all times.", -- (cam is short for camera)
  menu_invinc_particle = "Sparkle I-Frames",                      -- (I-Frames is short for invincibility/invulnerability frames)
  menu_invinc_particle_desc = "Replaces the \"blinking\" effect when Mario takes damage with sparkle particles.",
  menu_star_timer = "Last Star Time",
  menu_star_timer_desc = "Shows when the last star was collected on the bottom of the screen.",
  menu_overlay = "Course Progress Overlay",
  menu_overlay_desc = "Displays collected stars, keys, and cap switches near a course's painting or warp.",
  menu_binds = "Change Binds",
  menu_binds_desc = "Change the buttons used for various actions.",
  menu_old_input = "Old Menu Arrow Controls",
  menu_old_input_desc = "Changes controls for arrow selection to how they were pre v2.8.",

  -- binds menu
  menu_vanish_button = "Vanish",
  menu_vanish_button_desc = "Button held to activate the vanish cap when \"Nerf Vanish Cap\" is active.",
  menu_menu_button = "Open Menu",
  menu_menu_button_desc = "Button(s) pressed to open the MarioHunt menu.",
  menu_report_button = "Report/Fix",
  menu_report_button_desc = "Button used to report bodies and stop sabotages in MysteryHunt.",
  menu_guard_button = "Guard",
  menu_guard_button_desc = "Button pressed to guard a player in Spectator mode in MysteryHunt.",
  menu_sabo_button = "Open Sabotage Menu",
  menu_sabo_button_desc = "Button(s) pressed to open the Sabotage menu in MysteryHunt.",

  menu_free_cam_desc = "Enter Free Camera in Spectator Mode.",
  menu_spectate_run = "Spectate Runner",
  menu_spectate_run_desc = "Automatically spectate the first Runner.",
  menu_exit_spectate = "Exit Spectate",
  menu_exit_spectate_desc = "Exit spectator mode.",
  menu_stalk_run = "Warp to Runner Level",
  menu_stalk_run_desc = "Warp to the level the first Runner is in.",
  menu_skip = "Skip",
  menu_skip_desc = "- Vote to skip this star in MiniHunt.",

  menu_spectate_desc = "Spectate this player.",

  menu_blacklist_list = "List All Blacklisted",
  menu_blacklist_list_desc = "Lists all blacklisted stars in MiniHunt for this server.",
  menu_blacklist_save = "Save Blacklist",
  menu_blacklist_save_desc = "Save this blacklist on your end.",
  menu_blacklist_load = "Load Blacklist",
  menu_blacklist_load_desc = "Load your saved blacklist.",
  menu_blacklist_reset = "Reset Blacklist",
  menu_blacklist_reset_desc = "Reset the blacklist to the default.",
  menu_toggle_all = "Toggle All",

  -- presets
  preset_quick = "Quick Game",
  preset_quick_desc = "30 Star, Free Roam, No Bowser run.",
  preset_infection = "Infection",
  preset_infection_desc = "1 Hunter that can one-shot! Can the Runners survive?",
  preset_solo = "Solo",
  preset_solo_desc = "You're on your own! 3 lives and double health.",
  preset_tag = "Tag",
  preset_tag_desc = "Hit a Runner to instantly become one!",
  preset_star_rush = "Star Rush",
  preset_star_rush_desc = "Minihunt, but everyone's a Runner!",
  preset_classic = "Classic",
  preset_classic_desc = "Changes settings to match old versions of MarioHunt.",
  preset_asn = "ASN Tourney",
  preset_asn_desc = "Same settings used in the ASN Tourney (with 1 extra life).",
  preset_save = "Save Current Preset",
  preset_saved = "Preset saved as \"%s\". To rename this preset, use /mh preset rename [new name]",
  preset_deleted = "Deleted \"%s\" preset.",
  preset_cant_delete = "Can't delete this preset!",
  preset_not_saved = "This preset must be saved before you can rename it.",

  -- updater (now obsolete)
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ is up to date!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ is up to date!",
  has_update = "An update is availible for \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\!",
  has_update_egg = "An update is availible for \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\!",

  -- tips
  -- I totally understand if you don't want to translate all of these.
  tip = "Tip: ",
  tip_1 = "Press %s, or type /mh, to open the menu. You can configure settings here!",
  tip_2 = "Ground pounds deal 3 damage to other players.",
  tip_3 = "A kick will deal 2 damage and send players flying!",
  tip_4 =
  "For commands such as /spectate and /target, you can enter partial names and they'll still work (ex: entering \"Emily\" will refer to EmilyEmmi)",
  tip_5 = "You can change settings mid-game in the menu.",
  tip_6 = "If something goes wrong, type /mh pause to pause all players. Type it again to unpause.",
  tip_7 = "Is someone spamming or using slurs? Use /mh mute to mute them!",
  tip_8 = "You can pause the game before collecting a star or key and Exit Course to skip the animation.",
  tip_9 = "You can target a Runner with /target. This will display their location at the top of the screen.",
  tip_10 = "You can configure personal settings in the menu (%s).",
  tip_11 = "No need to restart the server! Select \"Reset Alt Save\" in \"Start\" to reset all progress.",
  tip_12 = "You can obtain Runner role by defeating a Runner.",
  tip_13 = "Like in vanilla Mario 64, 0 lives still counts as a life.",
  tip_14 = "Major glitches, such as LBLJ, are useless outside of Any%.",
  tip_15 = "In-game signs may contain more helpful tips!",
  tip_16 = "Dire Dire Docks may be entered at one less star than the actual category.",
  tip_17 = "Set Cappy to \"Damage\" to use him as a ranged weapon. He deals 1 damage.",
  tip_18 = "Cappy can pick up objects, such as Coins and Secrets.",
  tip_19 = "Use the D-Pad to throw Cappy in different directions.",
  tip_20 = "Check out Key's Artwork's video on YouTube to learn about OMM tech!",
  tip_21 =
  "If objects in a level start to disappear or warps stop working, use /mh out in that level to force that level to reload.",
  tip_22 = "Use /mh desync if you think a desync error has occured.",
  tip_23 = "Killing another player will restore all of your health.",
  tip_24 = "You can see progress on keys, caps, and secret stages in the Pause menu in the castle.",
  tip_25 = "Runners can hurt each other in this mode!",
  tip_26 = "Falling off in cap stages counts as losing a life.",
  tip_27 = "Blue coin switches will respawn.",
  tip_28 = "You can pick another act to throw off Hunters.",
  tip_29 = "It's a holiday! If you don't like the effects, turn off \"Seasonal Changes\" in the menu.",
  tip_30 = "You can spy on Runners with /spectate.",
  tip_31 = "Use /stalk to warp to a level another Runner is in!",
  tip_32 = "Learning speedrunning techniques is a good way to improve your game.",
  tip_33 = "You can phase through Whomps by ground-pounding or kicking as they fall.",
  tip_34 = "The fastest way to perform a Triple Jump is by kicking for the first jump.",
  tip_35 = "Metal form deals double damage to opponents.",
  tip_36 = "The Vanish Cap will only take protect you from player attacks when holding %s.",
  tip_37 = "Cap timers don't drain inside of cannons.",
  tip_38 = "Don't linger on the Act Select for too long!",
  tip_39 = "Dives are fast, and diving into another player can help you evade attacks.",
  tip_40 = "Falling off will deal damage instead of instantly killing you.",
  tip_41 = "1-Ups will restore 4 health points.",
  tip_42 = "Use the Players menu for commands that target a specific player, such as flipping teams.",
  tip_43 = "The MarioHunt menu allows for starting games and configuring game settings.",
  tip_44 = "You can hide your chat role in Settings.",
  tip_45 = "Runners wearing the Metal Cap can still be hurt by Hunters.",
  tip_46 = "In the menu, be sure to press A to save your changed settings!",

  -- These commands only appear to me, so don't translate them. You can delete these lines and everything should still work.
  debug_print_desc = "[STRING] - Outputs message to console",
  debug_warp_desc = "[LEVEL|COURSE,AREA,ACT,NODE] - Warp to level",
  debug_quick_desc = "[LEVEL|COURSE|HUNTER,AREA,ACT,NODE] - Quick game testing",
  debug_combo_desc = "[NUM] - Test combo message",
  debug_field_desc = "[STRING] - Get specified field for all players",
  debug_gfield_desc = "[STRING] - Get specified global field",
  debug_allstars_desc = "- Lists all stars",
  debug_langtest_desc = "- Do language testing stuff (see lang.lua)",
  debug_unmod_desc = "- Toggle off mod for yourself for testing",
  debug_location_desc = "[NAME|ID] - Get the name of your location, or whoever is specified",
  debug_complete_desc = "- 100%s the save file",
  debug_djui_desc = "- Opens djui menu",
  debug_swarp_desc = "- Does special warp (-1, -2, -3, -8, or -9)",
  debug_safe_desc = "- Toggle showing last valid surface",
  debug_nowin_desc = "- Toggle ability to win",
  debug_ping_desc = "- Show everyone's ping in the player list",
  debug_get_desc = "[NUM] - Get this many stars",
  ["debug_set-fov_desc"] = "[NUM] - Sets your fov; leave blank to reset",
  ["debug_wing-cap_desc"] = "- Grants wing cap",
  ["debug_kill-bowser_desc"] = "- Kills Bowser, if he exists",
}