langdata["es"] = -- By Kanheaven and SonicDark, with newer lines by EpikCool and corrected errors by green (also stuff from TenmaAkie for v2.8)
{
  -- fullname for auto select
  fullname = "Spanish",

  -- name in the built-in menu
  name_menu = "Español (US)", -- I wanted to keep the name shorter

  -- global command info
  to_switch = "Escribe \"/lang %s\" para cambiar idioma",
  switched = "¡Cambiaste a Español!",
  rule_command = "Escribe /rules para mostrar este mensaje otra vez",
  stalk = "¡Escribe /stalk para teletransportarte a los corredores!",

  -- roles
  runner = "Corredor",
  runners = "Corredores",
  short_runner = "Corre",
  hunter = "Cazador",
  hunters = "Cazadores",
  spectator = "Espectador",
  player = "Jugador",
  players = "Jugadores",
  all = "Todos",
  dead = "Muerto",

  demon_unlock = "¡Has desbloqueado el modo Green Demon!",
  hit_switch_red = "¡%s\\#ffa0a0\\ presionó el\n\\#df5050\\Interruptor Rojo!",         -- dark red (unique)
  hit_switch_green = "¡%s\\#ffa0a0\\ presionó el\n\\#50b05a\\Interruptor Verde!",      -- dark green (unique)
  hit_switch_blue = "¡%s\\#ffa0a0\\ presionó el\n\\#5050e3\\Interruptor Azul!",        -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ presionó el\n\\#e3b050\\Interruptor Amarillo...", -- orangeish (unique)
  connected = "¡%s\\#ffff5a\\ se ha conectado!",                                       -- same as coop
  disconnected = "%s\\#ffa0a0\\ se ha desconectado",                                   -- same as coop

  -- rules (%d:%02d is time in minutes:seconds format)
  welcome = "¡Bienvenido a \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! CÓMO JUGAR:",
  welcome_mini = "¡Bienvenido a \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! CÓMO JUGAR:",
  welcome_mys = "¡Bienvenido a \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! CÓMO JUGAR:",
  welcome_egg = "¡Bienvenido a \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! CÓMO JUGAR:",
  all_runners = "Eliminen a todos los \\#00ffff\\Corredores\\#ffffff\\.",
  any_runners = "Eiminen a cualquiera de los \\#00ffff\\Corredores\\#ffffff\\.",
  shown_above = "(mostrado arriba)",
  any_bowser = "Derroten a %s de \\#ffff5a\\cualquier\\#ffffff\\ manera.",
  collect_bowser = "Recolecten \\#ffff5a\\%d estrella(s)\\#ffffff\\ y derroten a %s.",
  mini_collect = "Sé el primero en \\#ffff5a\\recolectar la estrella\\#ffffff\\.",
  collect_only = "Recolecten \\#ffff5a\\%d estrella(s)\\#ffff5a\\.",
  thats_you = "(¡ese eres tú!)",
  banned_glitchless = "NO: traicionar a tu equipo, BLJs, atravesar paredes, frenar el avance del juego, campear.",
  banned_general = "NO: traicionar a tu equipo, frenar el avance del juego, campear.",
  time_needed = "%d:%02d para salir de cualquier nivel; recolecta estrellas para reducir este tiempo",
  stars_needed = "%d estrella(s) para salir de cualquier nivel",
  become_hunter = "únete a los \\#ff5a5a\\Cazadores\\#ffffff\\ cuando hayas sido eliminado",
  become_runner = "elimina a un \\#00ffff\\Corredor\\#ffffff\\ para volverte uno",
  become_spectator = "conviertete a \\#a9a9a9\\Espectador\\#ffffff\\ cuando te derroten",
  infinite_lives = "Vidas infinitas",
  spectate = "escribe \"/spectate\" para ser un espectador",
  mini_goal = "\\#ffff5a\\¡Quien recolecte la mayor cantidad de estrellas en %d:%02d, gana!\\#ffffff\\",
  fun = "¡Diviértete!",

  -- hud, extra desc, and results text
  win = "¡%s\\#ffffff\\ ganan!",
  can_leave = "\\#5aff5a\\Puedes salir del nivel",
  cant_leave = "\\#ff5a5a\\No puedes salir del nivel",
  time_left = "Puedes salir en \\#ffff5a\\%d:%02d",
  stars_left = "Necesitas \\#ffff5a\\%d estrella(s)\\#ffffff\\ para salir del nivel",
  in_castle = "En el Castillo",
  until_hunters = "Los \\#ff5a5a\\Cazadores\\#ffffff\\ empiezan en: %d segundo(s)",
  until_runners = "Los \\#00ffff\\Corredores\\#ffffff\\ empiezan en: %d segundo(s)",
  lives_one = "1 vida",
  lives = "%d vidas",
  stars_one = "1 estrella",
  stars = "%d estrellas",
  no_runners = "¡No hay \\#00ffff\\Corredores!",
  camp_timer = "¡Muévete! \\#ff5a5a\\(%d)",
  game_over = "¡La partida terminó!",
  winners = "Ganadores: ",
  no_winners = "\\#ff5a5a\\¡No hay ganadores!",
  death_timer = "Muerte",
  on = "\\#5aff5a\\ACTIVADO",
  off = "\\#ff5a5a\\DESACTIVADO",
  frozen = "Congelado por %d",
  no_runners_here = "¡No hay \\#00ffff\\Corredores\\#ffffff\\ aquí!",
  no_players_here = "¡No hay otros jugadores aquí!",

  -- popups
  lost_life = "¡%s\\#ffa0a0\\ perdió una vida!",
  lost_all = "¡%s\\#ffa0a0\\ perdió todas sus vidas!",
  now_role = "%s\\#ffa0a0\\ ahora es un %s\\#ffa0a0\\.",
  got_star = "¡%s\\#ffa0a0\\ consiguió una estrella!",
  got_key = "¡%s\\#ffa0a0\\ consiguió una llave!",
  rejoin_start = "%s\\#ffa0a0\\ tiene dos minutos para volver a unirse.",
  rejoin_success = "¡%s\\#ffa0a0\\ regresó a tiempo!",
  rejoin_fail = "%s\\#ffa0a0\\ no regresó a tiempo.",
  leave_error = "%s\\#ffa0a0\\ se desconecto por un error.",
  using_ee = "\\#ffa0a0\\La partida está teniendo lugar en Modo Extremo.",
  not_using_ee = "\\#ffa0a0\\La partida está teniendo lugar en Modo Normal.",
  killed = "¡%s\\#ffa0a0\\ mató a %s!",
  sidelined = "¡%s\\#ffa0a0\\ acabó con %s!",
  paused = "Has sido pausado.",
  unpaused = "Ya no estás pausado.",
  kill_combo_2 = "¡%s\\#ffa0a0\\ hizo una \\#ffff5a\\doble\\#ffa0a0\\ muerte!",
  kill_combo_3 = "¡%s\\#ffa0a0\\ hizo una \\#ffff5a\\triple\\#ffa0a0\\ muerte!",
  kill_combo_4 = "¡%s\\#ffa0a0\\ hizo una \\#ffff5a\\cuádruple\\#ffa0a0\\ muerte!",
  kill_combo_5 = "¡%s\\#ffa0a0\\ hizo una \\#ffff5a\\quíntuple\\#ffa0a0\\ muerte!",
  kill_combo_large = "\\#ffa0a0\\¡Wow! ¡%s\\#ffa0a0\\ hizo \\#ffff5a\\%d\\#ffa0a0\\ muertes consecutivas!",
  set_hack = "Romhack seleccionado: %s",
  incompatible_hack = "ADVERTENCIA: ¡Este romhack no es compatible!",
  vanilla = "Usando el juego original",
  omm_detected = "¡Se Detecto El OMM Rebirth!",
  omm_bad_version = "\\#ff5a5a\\¡OMM Rebirth está desactualizado!\\#ffffff\\\nVersión mínima: %s\nTu versión: %s",
  warp_spam = "¡No te teletransportes tan rápido!",
  no_valid_star = "¡No se ha podido encontrar una estrella válida!",
  custom_enter = "%s\\#ffffff\\ ha entrado a\n%s", -- same as coop

  -- command feedback
  not_mod = "No tienes la AUTORIDAD para usar este comando, ¡Tonto!",
  no_such_player = "Ese jugador no existe",
  bad_id = "¡ID de jugador inválido!",
  command_disabled = "Este comando está desactivado.",
  change_setting = "Ajuste modificado:",

  -- more command feedback
  bad_param = "¡Parámetros inválidos!",
  bad_command = "¡Comando inválido!",
  error_no_runners = "¡No se puede iniciar la partida con 0 corredores!",
  set_team = "%s ahora es un '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "La partida aún no ha iniciado",
  set_lives_one = "%s ahora tiene 1 vida",
  set_lives = "%s ahora tiene %d vidas",
  not_runner = "%s no es un Corredor",
  may_leave = "%s puede salir del nivel",
  must_have_one = "Debes tener al menos un cazador",
  added = "Se agregó a los corredores: ", -- list comes afterward
  runners_are = "Los corredores son: ",
  set_lives_total = "Vidas de los corredores ajustadas a %d",
  wrong_mode = "No disponible en este modo",
  need_time_feedback = "Los corredores podrán salir del nivel en %d segundo(s) ahora",
  game_time = "La partida ahora durará %d segundo(s)",
  need_stars_feedback = "Los corredores ahora necesitan %d estrella(s)",
  new_category = "Ahora esto es una %d star run",
  new_category_any = "Ahora esto es una any% run",
  mode_normal = "En modo Normal",
  mode_swap = "En modo Swap",
  mode_mini = "En modo MiniHunt",
  mode_mys = "En modo MysteryHunt",
  using_stars = "Usando estrellas recolectadas",
  using_timer = "Usando tiempo",
  can_spectate = "Los Cazadores ahora pueden ser espectadores",
  no_spectate = "Los Cazadores ya no pueden ser espectadores",
  all_paused = "Todos los jugadores han sido pausados",
  all_unpaused = "Todos los jugadores ya no están pausados",
  player_paused = "%s ha sido pausado",
  player_unpaused = "%s ya no está pausado",
  hunter_metal = "Todos los Cazadores son de metal",
  hunter_normal = "Todos los Cazadores se verán normales",
  hunter_glow = "Todos los Cazadores brillarán rojo",
  hunter_outline = "Ahora Todos los Cazadores tienen el aspecto Outline",
  hunter_color = "Todos los Cazadores tendran un aspecto con color Borgoña",
  runner_normal = "Todos los Corredores se verán normales",
  runner_sparkle = "Ahora todos los Corredores tendran el aspecto Brillante",
  runner_glow = "Ahora todos los Corredores tendran glow",
  runner_outline = "Ahora Todos los Corredores tienen el aspecto Outline",
  runner_color = "Ahora Todos los Corredores tender un aspecto de color Celeste",
  now_weak = "Todos los jugadores tienen la mitad de Invincibility Frames",
  not_weak = "Todos los jugadores tienen Invincibility Frames normales",
  auto_on = "Las partidas iniciarán automáticamente",
  auto_off = "Las partidas no iniciarán automáticamente",
  force_spectate = "Todos serán forzados al modo Espectador",
  force_spectate_off = "El modo Espectador ya no es forzado",
  force_spectate_one = "%s será un Espectador",
  force_spectate_one_off = "%s ya no es forzado a ser un Espectador",
  blacklist_add = "%s agregado a la Lista Negra",
  blacklist_remove = "%s removido de la Lista Negra",
  blacklist_add_already = "Esa estrella o nivel ya está en la Lista Negra.",
  blacklist_remove_already = "Esa estrella o nivel no está en la Lista Negra.",
  blacklist_remove_invalid = "No puedes agregar a esa estrella o nivel a la Lista Negra .",
  blacklist_list = "Lista Negra:",
  blacklist_reset = "¡La Lista Negra ha sido reiniciada!",
  blacklist_save = "¡La Lista Negra ha sido guardada!",
  blacklist_load = "¡La Lista negra ha sido cargada!",

  -- team chat
  tc_toggle = "¡El chat de equipo está %s!",
  to_team = "\\#8a8a8a\\Para tu equipo: ",
  from_team = "\\#8a8a8a\\ (equipo): ",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ votó para saltar esta estrella",
  vote_info = "Escribe /skip para saltarla",
  vote_pass = "¡La votación terminó!",
  already_voted = "Ya has votado.",

  -- hard mode
  hard_notice = "Psst, intenta escribir /hard info...",
  extreme_notice = "Psst, intenta escribir /hard ex...",
  hard_toggle = "¡\\#ff5a5a\\Modo Difícil\\#ffffff\\ %s!",
  extreme_toggle = "¡\\#b45aff\\Modo Extremo\\#ffffff\\ %s!",
  hard_info = "¿Interesado en el\\#ff5a5a\\Modo Difícil\\#ffffff\\?" ..
      "\n- Sólo tienes la mitad de salud" ..
      "\n- No te puedes curar usando el agua" ..
      "\n- \\#ff5a5a\\Sólo tienes una vida" ..
      "\n\\#ffffff\\Escribe /hard ON si aceptas el desafío.",
  extreme_info = "¿Acaso te interesa el \\#b45aff\\Modo Extremo\\#ffffff\\? Que tonto." ..
      "\n- Una vida" ..
      "\n- Un punto de salud" ..
      "\n- \\#b45aff\\Temporizador de Muerte\\#ffffff\\; recolecta monedas y estrellas para aumentarlo" ..
      "\nSi esto no te asusta, escribe /hard ex ON.",
  no_hard_win = "Tus victorias en Modo Difícil o Modo Extremo no contarán en esta partida.",
  hard_mode = "Modo Difícil",
  extreme_mode = "Modo Extremo",
  hard_info_short = "Sólo tienes la mitad de salud, una vida, y no te puedes curar usando el agua.",
  extreme_info_short = "Un punto de salud, una vida, y Temporizador de Muerte.",

  -- spectator
  hunters_only = "¡Sólo los Cazadores pueden ser espectadores!",
  spectate_disabled = "¡Modo Espectador desactivado!",
  timer_going = "¡No puedes ser Espectador cuando el tiempo corre!", -- now unused
  spectate_self = "¡No puedes ser Espectador de ti mismo!",
  spectator_controls = "Controles:" ..
      "\nDPAD-UP: Desactiva la interfaz" ..
      "\nDPAD-DOWN: Cambia la vista entre cámara libre/punto de vista del jugador" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Cambia jugador" ..
      "\nJOYSTICK: Moverse" ..
      "\nA: Moverse hacia arriba" ..
      "\nZ: Moverse hacia abajo" ..
      "\nType \"/spectate OFF\" para cancelar",
  spectate_off = "Dejaste de ser Espectador.",
  empty = "VACÍO (%d )",
  free_camera = "CÁMARA LIBRE",
  spectate_mode = "- MODO ESPECTADOR -",
  is_spectator = '* EL JUGADOR ES UN ESPECTADOR  *',

  -- stats
  disp_wins_one = "¡%s\\#ffffff\\ ganó 1 vez como \\#00ffff\\Corredor\\#ffffff\\!",
  disp_wins = "¡%s\\#ffffff\\ ganó %d veces como \\#00ffff\\Corredor\\#ffffff\\!",
  disp_kills_one = "¡%s\\#ffffff\\ mató a 1 jugador!", -- unused
  disp_kills = "¡%s\\#ffffff\\ mató a %d jugadores!",
  disp_wins_hard_one =
  "¡%s\\#ffffff\\ ganó 1 vez como \\#ffff5a\\Corredor\\#ffffff\\ en \\#ff5a5a\\Modo Difícil\\#ffffff\\!",
  disp_wins_hard =
  "¡%s\\#ffffff\\ ganó %d veces como \\#ffff5a\\Corredor\\#ffffff\\ en \\#ff5a5a\\Modo Difícil\\#ffffff\\!",
  disp_wins_ex_one =
  "¡%s\\#ffffff\\ ganó 1 vez como \\#b45aff\\Corredor\\#ffffff\\ en \\#b45aff\\Modo Extremo\\#ffffff\\!",
  disp_wins_ex =
  "¡%s\\#ffffff\\ ganó %d veces como \\#b45aff\\Corredor\\#ffffff\\ en \\#b45aff\\Modo Extremo\\#ffffff\\!",
  -- for stats table
  stat_wins_standard = "Victorias",
  stat_wins = "Victorias (Minihunt/pre v2.3)",
  stat_wins_mys = "Victorias (MysteryHunt)",
  stat_kills = "Muertes",
  stat_combo = "Racha de muertes más alta",
  stat_wins_hard_standard = "Victorias (Modo Difícil)",
  stat_wins_hard = "Victorias (Modo Difícil, MiniHunt/pre v2.3)",
  stat_wins_hard_mys = "Victorias (Modo Difícil, MysteryHunt)",
  stat_mini_stars = "Récord de estrellas en MiniHunt",
  stat_wins_ex_standard = "Victorias (Modo Extremo)",
  stat_wins_ex = "Victorias (Modo Extremo, MiniHunt/pre v2.3)",
  stat_wins_ex_mys = "Victorias (Modo Extremo, MysteryHunt)",
  stat_playtime = "Jugado (Horas)",
  stat_parkour_time = "Tiempo Mas Rápido En Parkour",
  stat_parkour_time_omm = "Tiempo Mas Rápido En Parkour (OMM)",
  stat_parkour_time_other = "Tiempo Mas Rápido En Parkour (Moveset)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1er Lugar]",
  place_2 = "\\#c5d8de\\[64T: 2do Lugar]",
  place_3 = "\\#b38752\\[64T: 3er Lugar]",
  place = "\\#e7a1ff\\[64T: %do Lugar]", -- thankfully we don't go up to 21 (%d is the number placeholder, so this displays as "4o" for example)
  place_score_1 = "%der",
  place_score_2 = "%ddo",
  place_score_3 = "%der",
  place_score = "%do",

  -- command descriptions
  page = "\\#ffff5a\\Página %d/%d", -- page for mariohunt command
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Inicia la partida; agrega \"continue\" para no ser enviado al principio; agrega \"alt\" para usar una ranura de guardado alternativa; agrega \"main\" para usar la ranura de guardado principal; agrega \"reset\" para reiniciar la ranura de guardado",
  add_desc = "[INT] - Agrega la cantidad especificada de Corredores de manera aleatoria",
  random_desc = "[INT] - Escoge la cantidad de Corredores",
  random_desc_hunt = "[INT] - Escoge la cantidad de Cazadores",
  lives_desc = "[INT] - Ajusta la cantidad de vidas de los Corredores, de 0 a 99 (nota: 0 vidas es aún 1 vida)",
  time_desc = "[NUM] - Ajusta la cantidad de tiempo que deben esperar los Corredores para salir del nivel, en segundos",
  stars_desc =
  "[INT] - Ajusta la cantidad de estrellas que los Corredores deben recolectar para salir del nivel, de 0 a 7 (sólo en star mode)",
  category_desc =
  "[INT] - Ajusta la cantidad de estrellas que los Corredores deben recolectar para enfrentarse a Bowser.",
  flip_desc = "[NAME|ID] - Cambia el equipo del jugador especificado",
  setlife_desc = "[NAME|ID|INT,INT] - Ajusta las vidas especificadas para el Corredor especificado",
  leave_desc =
  "[NAME|ID] - Permite al jugador especificado, o a ti mismo, si no especificas a uno, abandonar el nivel si es un corredor.",
  mode_desc = "[NORMAL|SWAP|MINI] - Cambia el modo de juego; Swap cambia a los corredores cuando uno es eliminado",
  starmode_desc =
  "[ON|OFF] - Utiliza las estrellas recogidas en lugar del tiempo para que los Corredores puedan abandonar el nivel",
  spectator_desc = "[ON|OFF] - Permite a los Cazadores ser espectadores",
  pause_desc = "[NAME|ID|ALL] - Pausa a los jugadores especificados, o a todos si no especificas uno",
  hunter_app_desc = "Cambia la apariencia de los Cazadores.",
  runner_app_desc = "Cambia la apariencia de los Corredores.",
  hack_desc = "[STRING] - Selecciona el romhack actual",
  weak_desc = "[ON|OFF] - Reduce los Invincibility Frames a la mitad a todos los jugadores",
  auto_desc = "[ON|OFF|NUM] - Inicia la partida automaticamente",
  forcespectate_desc = "[NAME|ID|ALL] - Fuerza el modo espectador para este jugador o todos los jugadores",
  desync_desc = "- Intenta arreglar los errores causados por desync",
  stop_desc = "- Detén la partida",
  default_desc = "- Restablece la configuración a la predeterminada",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Agrega estrellas a la Lista Negra en MiniHunt",
  stalking_desc = "[ON|OFF] - Permite ir al nivel en el que se encuentra un Corredor con /stalk",

  -- Blocky's menu
  main_menu = "Menu Principal",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  --menu_settings_player = "Ajustes",
  menu_rules = "Reglas",
  menu_lang = "Idioma",
  menu_misc = "Otros",
  menu_stats = "Estadísticas",
  menu_back = "Volver",
  menu_exit = "Salir",

  menu_run_random = "Cantidad de Corredores",
  menu_run_add = "Agregar Corredores",
  menu_hunt_random = "Cantidad de Cazadores",
  menu_run_lives = "Vidas de los Corredores",
  menu_settings = "Ajustes del Juego",

  menu_start = "Iniciar",
  menu_stop = "Detener",
  menu_save_main = "Ranura de Guardado Principal",
  menu_save_alt = "Ranura Alternativa",
  menu_save_reset = "Reiniciar ranura alternativa",
  menu_save_continue = "Continuar (no eres enviado al principio)",
  menu_random = "Aleatoria",
  menu_campaign = "Campaña",

  menu_gamemode = "Modo de juego",
  menu_hunter_app = "Apariencia de los Cazadores",
  menu_runner_app = "Apariencia de los Corredores",
  menu_weak = "Modo débil",
  menu_allow_spectate = "Permitir Espectadores",
  menu_star_mode = "Modo de estrellas",
  menu_category = "Categoría",
  menu_time = "Tiempo",
  menu_stars = "Estrellas",
  menu_auto = "Juego automático",
  menu_blacklist = "Lista Negra de MiniHunt",
  menu_default = "Reiniciar",
  menu_defeat_bowser = "Derrota a %s",
  menu_allow_stalk = "Permitir 'Stalking'",

  menu_players_all = "Todos los jugadores",
  menu_flip = "Cambiar Equipo",
  menu_spectate = "Observar",
  menu_stalk = "Ir al nivel",
  menu_stalk_desc = "Ve al nivel de este jugador.",
  menu_pause = "Pausa",
  menu_forcespectate = "Forzar modo Espectador",
  menu_allowleave = "Permitir que salga del nivel",
  menu_setlife = "Ajustar vidas",

  menu_timer = "Cronómetro de Speedrun",
  menu_timer_desc = "[ON|OFF] - Muestra un cronómetro en la parte inferior de la pantalla en los modos estándar.",
  menu_tc = "Chat de equipo",
  menu_tc_desc = "Chatea sólo con tu equipo.",
  menu_demon = "Green Demon", -- referring to the 1-Up
  menu_demon_desc = "Un 1-Up te perseguirá cuando seas Corredor.",
  menu_unknown = "???",
  menu_secret = "Esto es un secreto. ¿Cómo se desbloquea?",
  menu_season = "Cambios de estación",
  menu_season_desc = "Divertidos cambios visuales según la fecha.",
  menu_radar = "Radar",
  menu_radar_desc = "Muestra adonde Corredores y objetos están en el mapa.",
  menu_minimap = "Mapa",
  menu_minimap_desc = "Muestra el mapa completo.",
  menu_romhack_cam = "Cámara romhack",                                   -- -- (cam is short for camera)
  menu_romhack_cam_desc = "Activa la 'Cámara romhack' en todo momento.", -- -- (cam is short for camera)

  menu_free_cam_desc = "Usa la Cámara Libre en el modo Espectador.",
  menu_spectate_run = "Observar Corredor",
  menu_spectate_run_desc = "Automáticamente observarás al primer Corredor.",
  menu_exit_spectate = "Salir del modo Espectador",
  menu_exit_spectate_desc = "Saldrás del modo Espectador.",
  menu_stalk_run = "Ir al nivel del Corredor",
  menu_stalk_run_desc = "Ve al nivel en el que está el primer Corredor.",
  menu_skip = "Saltar",
  menu_skip_desc = "- Vota para saltar esta estrella en MiniHunt.",

  menu_spectate_desc = "Observa a este jugador.",

  menu_blacklist_list = "Lista Negra",
  menu_blacklist_list_desc = "Muestra todas las estrellas en la Lista Negra en MiniHunt de esta partida.",
  menu_blacklist_save = "Guardar Lista Negra",
  menu_blacklist_save_desc = "Guarda la Lista Negra sólo para ti.",
  menu_blacklist_load = "Cargar Lista Negra",
  menu_blacklist_load_desc = "Carga la Lista Negra guardada.",
  menu_blacklist_reset = "Reiniciar Lista Negra",
  menu_blacklist_reset_desc = "Reinicia la Lista Negra a los valores predeterminados.",
  menu_toggle_all = "Alternar todos",

  -- updater (difference for "_egg" is Luigi instead of Mario)
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ está actualizado!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ está Actualizado!!",
  has_update = "Hay una actualización para \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\!",
  has_update_egg = "Hay una actualización para \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\!",

  -- unorganized
  lang_desc = "%s - Ajusta el lenguaje",
  got_all_stars = "¡Tienes las estrellas suficientes!",
  menu_hide_roles_desc = "Esconder tus Roles en el chat.",
  spectate_desc =
  "[NAME|ID|OFF] - Sé espectador del jugador especificado, cámara libre si no es especificado, o OFF para salir",
  tc_desc = "[ON|OFF|MSG] - Envía un mensaje únicamente a tu equipo; ON para aplicar a todos los mensajes",
  stars_in_area = "¡Hay %d estrella(s) sin recolectar(se) aquí!",
  role_cont = "\\#ff9696\\[Colaborador/a de MH]",
  role_trans = "\\#ffd996\\[Traductor/a de MH]",
  role_lead = "\\#9a96ff\\[Programadora Líder de MH]",
  menu_first_timer = "Temporizador de Muerte del Líder",
  menu_popup_sound = "Sonidos de mensajes emergentes",
  stalk_desc =
  "[NAME|ID] - Viaja al nivel del jugador que está especificado, o en el que se encuentra el primer corredor",
  menu_hide_roles = "Ocultar mis roles",
  open_menu = "Escribe /mh o presiona %s para abrir el menú",
  menu_nerf_vanish = "Nerfear Gorra de Invisibilidad",
  stat_placement = "Puesto en 64 Tour",
  menu_fast = "Acciones más rápidas",
  new_record = "\\#ffff5a\\¡¡¡LOGRASTE UN NUEVO RÉCORD!!!",
  anarchy_set_2 = "Los Cazadores ahora pueden atacar a sus compañeros de equipo",
  no_runners_added = "No se agregaron Corredores",
  menu_first_timer_desc = "Agrega al líder, en MiniHunt, un temporizador de muerte.",
  role_dev = "\\#96ecff\\[Programador/a de MH]",
  menu_nerf_vanish_desc =
  "Nerfea la gorra de invisibilidad haciéndola activable (con B) y se acaba más rápido cuando se usa.",
  unstuck = "Se reparó el nivel",
  menu_list_settings = "Lista de Ajustes",
  anarchy_set_3 = "Los jugadores ahora pueden atacar a sus compañeros de equipo",
  menu_fast_desc = "Te recuperarás, lanzarás objetos, y abrirás puertas más rápido.",
  menu_hide_hud = "Esconder la HUD",
  hidehud_desc = "- Esconde todos los elementos de la HUD.",
  dmgAdd_set = "Los corredores ahora tomarán %d daño extra de los ataques PVP.",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Se activara el Modo Difícil para a ti",
  menu_dmgAdd = "Aumentar el daño hacia Corredor",
  menu_anarchy_desc = "Permite que el equipo especificado pueda atacarse entre sí.",
  rules_desc = "- Muestra las reglas de MarioHunt",
  rules_desc_egg = "Muestra las reglas de LuigiHunt!",
  menu_anarchy = "Fuego Amigo",
  mh_desc = "[COMMAND,ARGS] - Ejecuta comandos; escribe nada o \"menu\" para abrir el menú",
  ---- vanish_custom = "¡Mantiene el botón \\#ffff5a\\%s\\#ffffff\\ para volverte invisible!",
  menu_list_settings_desc = "Lista todos los ajustes para esta partida.",
  anarchy_set_1 = "Los Corredores ahora pueden atacar a sus compañeros de equipo",
  anarchy_set_0 = "Los jugadores ya no pueden atacar a sus compañeros de equipo",
  menu_dmgAdd_desc = "Agrega la cantidad de daño especificada contra los corredores.",
  mini_score = "Puntaje: %d",
  stats_desc = "- Muestra/Oculta la tabla de estadísticas",

  -- v2.5
  target_desc = "[NAME|ID] - Coloca a este Corredor como tu objetivo, lo que revela su posición en todo momento.",
  use_out = "Usa /mh out para expulsar a todos fuera de este nivel",

  you_are_muted = "Estas silenciado",

  dmgAdd_set_ohko = "Ahora todos los corredores moriran de un solo golpe",
  voidDmg_set = "Los jugadores tomaran %d daño cayendo al vacio o a arenas movedizas.",
  voidDmg_set_ohko = "Los jugadores seran instantaneamente muertos al vacio o a las arenas movedizas.",
  target_hunters_only = "Sólo los cazadores puede los corredores como objetivo.",

  muted = "\\#ffff00\\%s\\#ffffff\\ fue silenciado por \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ fue desilenciado por \\#ffff00\\%s\\#ffffff\\.",
  you_muted = "Fuiste silenciado \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Fuiste desilenciado \\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ fue silenciado automaticamente",

  mute_desc = "[NAME|ID] - Silencia a un jugador, impidiendole poder chatear",
  unmute_desc = "[NAME|ID] - Desilencia a un jugador, permitiendole chatear de nuevo",
  out_desc = "[LEVEL|COURSE] - Expulsa a todos los jugadores de este nivel",

  menu_countdown = "Temporizador",
  menu_countdown_desc = "Que tanto deben esperar los Corredores antes de comenzar.",
  menu_voidDmg = "Daño del Vacío",
  menu_voidDmg_desc = "Daño infligido a los jugadores que caen al vacío o arenas movedizas.",
  menu_double_health = "Multiplicar la Barra de Vida",
  menu_double_health_desc = "Los jugadores tienen 16 puntos de vida, en vez de 8.",

  -- v2.6
  menu_free_roam = "Movimiento Libre",
  menu_free_roam_desc = "Desactiva el requisito de estrellas y llaves para ciertas puertas y los demás niveles.",

  menu_target = "Colocar como Objetivo",
  menu_mute = "Silenciar",

  menu_invinc_particle = "I-Frames Brillantes", -- (I-Frames is short for invincibility/invulnerability frames)
  menu_invinc_particle_desc = "Reemplaza el efecto \"parpadeante\" cuando Mario recibe daño con partículas Brillantes.",
  menu_stalk_timer = "Cooldown para 'Stalk'",
  menu_stalk_timer_desc = "Tiempo que el jugador es congelado luego de usar /stalk.",
  menu_star_heal = "Curación de Estrellas",

  -- v2.6.1
  menu_star_setting = "Al conseguir una estrella", -- from base coop
  star_leave = "Salir",
  star_stay = "Seguir",
  star_nonstop = "Sin Parar",

  -- v2.7
  disp_asn_quarter = "¡%s\\#ffffff\\ llego a los \\#70ff94\\Cuartos de final\\#ffffff\\ en el torneo de ASN!",
  disp_asn_win = "¡%s \\#e3bc2d\\gano \\#ffffff\\ el torneo ASN!",
  keep_secret = "¡No te atrapen!",
  menu_coop = "Coperativo",
  menu_overlay = "Superposicion de progreso del nivel",
  menu_overlay_desc =
  "Muestra las estrellas recolectadas, llaves, y gorras botones cerca de una pintura de un nivel o teletransportacion.",
  menu_presets = "Preajustes",
  menu_shuffle = "Mezcla de equipos",
  menu_shuffle_desc = "Mezcla los equipos cada jugador vivo en la cantidad de tiempo seleccionada",
  menu_spectate_on_death = "Corredores espectan cuando estan muertos",
  menu_star_stay_old = "Quedarse si se ha recolectado",
  menu_star_stay_old_desc = "Tomando una estrella ya conseguida no te sacara del nivel.",
  menu_star_timer = "Hora de la ultima estrella",
  menu_star_timer_desc = "Muestra cuando la ultima estrella fue conseguida arriba de la pantalla.",
  mysteryhunt_disabled = "¡\\#ffa0a0\\Uno de tus mods no es compatible con MysteryHunt!",
  mysteryhunt_innocent = "¡\\#ffa0a0\\Has matado a un jugador inocente!",
  mysteryhunt_spectate = "\\#ffa0a0\\Tu espectaras este juego.",
  place_asn = "\\#e7a1ff\\[ASN Participante]",
  place_asn_1 = "\\#e3bc2d\\[ASN Ganador]",
  place_asn_4 = "\\#70ff94\\[ASN Cuartos de final]",
  players_remain = "Quedan \\#ffa0a0\\%d jugadores.",
  players_remain_one = "Queda \\#ffa0a0\\1 jugador.",
  preset_classic = "Clasico",
  preset_classic_desc = "Cambia las opciones para parecerse a las versiones antiguas de MarioHunt.",
  preset_infection = "Infeccion",
  preset_infection_desc = "¡1 Cazador que puede un-tiro! ¿Puede Los Corredores sobrevivir?",
  preset_quick = "Juego Rapido",
  preset_quick_desc = "30 Estrellas, Movimiento libre, No hay que derrotar a Bowser.",
  preset_solo = "Solo",
  preset_solo_desc = "¡Estas en las tuyas amigo! 3 vidas y barra de salud multiplicada.",
  preset_star_rush = "Star Rush",
  preset_star_rush_desc = "¡Minihunt, pero todos son corredores!",
  preset_tag = "Pintura",
  preset_tag_desc = "¡Golpea a un Corredor para convertirte en uno!",
  role_dead = "\\#ff2020\\[MUERTO]",
  shuffle_timer = "Mezclando Equipos en %d",
  stat_placement_asn = "Lugar en Torneo ASN",
  unsaved_changes = "\\#ff5a5a\\¡Tienes Cambios sin guardar! Presiona de nuevo si estas seguro.",
  added_count = "Se han agregado %d corredores",
  added_count_one = "se ha agragedo 1 corredor",
  dead_become = "\\#00ffff\\Corredores\\#ffffff\\ muertos salen detras de un cuerpo.",
  dead_become_infection = "Jugadores muertos que no se convierten en \\#ff5a5a\\Cazador\\#ffffff\\salen detras de un cuerpo.",
  dead_become_noconfirm = "Dead players leave behind a body.",
  disp_asn_bronze = "¡%s\\#ffffff\\ tuvo \\#b38752\\bronce\\#ffffff\\ en el torneo ASN!",
  disp_asn_silver = "¡%s\\#ffffff\\ tuvo \\#c5d8de\\platino\\#ffffff\\ en el torneo ASN!",
  far = "\\#8a8a8a\\(lejos)",
  global_talk_end = "\\#ffa0a0\\El Chat Global ha terminado.",
  global_talk_start = "\\#ffa0a0\\El Chat global es disponible por %d segundo(s).",
  guard_cooldown = "Puede ser protegido en %d",
  guard_info = "Presiona %s para proteger a %s",
  guard_info_rules = "Jugadores muertos puede proteger a sus compañeros con %s.",
  guard_save = "\\#ffff00\\¡Un Fantasma te ha salvado de la muerte!",
  guard_timer = "%s\\#ffff00\\ esta protegido (%d)",
  hunters_remain = "Quedan \\#ffa0a0\\%d \\#ff5a5a\\Cazadores\\#ffa0a0\\.",
  hunters_remain_one = "Queda \\#ffa0a0\\1 \\#ff5a5a\\Cazador\\#ffa0a0\\.",
  hunters_set_count = "Hay %d Cazadores",
  hunters_set_count_one = "Hay 1 Cazador",
  hunters_were = "Los Cazadores eran: ",
  menu_binds = "Cambiar Atajos",
  menu_binds_desc = "Cambia los botones por varias ocasiones.",
  menu_confirm_hunter = "Confirmar las muertes del cazador",
  menu_confirm_hunter_desc = "Dispopne un mensaje cada vez que un cazador muere. Si esta desactivado, Tambien los cazadores puede dejar su cuerpo.",
  menu_global_chat = "Tiempo de Chat Global", -- This was previously "Es Hora del chat global!" which is roughly "It's time for global chat!". I assume Epik didn't know that this was meant for the menu.
  menu_global_chat_desc = "Hora que los jugadores hablan cuando se encontro un cuerpo",
  menu_grace_period = "Periodo Grace",
  menu_grace_period_desc = "Tiempo antes de que se puedan matar a jugadores.",
  menu_guard_button = "Proteger",
  menu_guard_button_desc = "Boton presionado para proteger a un jugador en modo espectador en MysteryHunt.",
  menu_hunters_win_early = "Cazadores ganan tempranamente",
  menu_hunters_win_early_desc = "Cazadores ganan cuando atrapan/consiguen la cantidad de corredores , como en among us.",
  menu_know_team = "Los cazadores conocen sus compañeros",
  menu_know_team_desc = "Los cazadores saben cuales son sus compañeros. Si esta desactivado, los cazadores tambien se pueden matar entre si.",
  menu_menu_button = "Abrir el menu",
  menu_menu_button_desc = "Boton(es) presionado para abrir el menu de MarioHunt.",
  menu_report_button = "Reportar/Arreglar",
  menu_report_button_desc = "Boton presionado para reportar cuerpos o sabotajes en MysteryHunt.", 
  menu_sabo = "Sabotear",
  menu_sabo_button = "Abrir el menu de sabotaje",
  menu_sabo_button_desc = "Boton(es) presionado para abrir el menu de sabotaje en MysteryHunt.",
  menu_show_on_map = "Mostrar en el Mapa",
  menu_show_on_map_desc = "Que equipos se veran en em minimapa (Los Opponentes tambien tendran radar)",
  menu_vanish_button = "Gorra Vanish",
  menu_vanish_button_desc = "Boton mantenidop para activar el vanish \"Nerfear Vanish Cap\" esta activado.",
  mystery_altgoal = "o: Descubre los \\#ff5a5a\\Cazadores\\#ffffff\\ y derrotarlos.",
  nearby = "\\#8a8a8a\\(cerca)",
  opponents = "Oponentes",
  other_hunters = "Los otros cazadores son: ",
  place_asn_2 = "\\#c5d8de\\[ASN Plata]",
  place_asn_3 = "\\#b38752\\[ASN Bronce]",
  preset_asn = "Torneo ASN",
  preset_asn_desc = "Mismos ajustes usados en el torneo ASNS (con 1 vida extra).",
  press_report = "%s - Reportar", -- is this correct? (%s is a button name, such as "L")
  press_fix = "%s - Arreglar", -- is this correct? (%s is a button name, such as "L")
  report_body = "¡%s\\#ffa0a0\\ encontro %s's\\#ffa0a0\\ el cuerpo en \\#ffff5a\\",
  report_info_rules = "Presiona %s para reportarlo y discutirlo.",
  runners_can_kill = "\\#00ffff\\Corredores\\#ffffff\\ Pueden derrotar a jugadores que sospechan que son \\#ff5a5a\\Cazadores\\#ffffff\\.\nSi matan a un inocente , tambien mueren.",
  runners_remain = "Quedan %d \\#00ffff\\Corredores\\#ffffff\\.",
  runners_remain_one = "1 \\#00ffff\\Corredor\\#ffffff\\ esta vivo.",
  sabo_activate_timer = "Activandolo en %d",
  sabo_active = "\\#ffff00\\¡SABOTAJE ACTIVADO!",
  sabo_bomb = "\\#ff4040\\Mega Bomba",
  sabo_bomb_desc = "¡Mata a todos los juagadores si no se desactiva!",
  sabo_bomb_timer = "\\#ff4040\\ Todos van a morir en %d:%02d",
  sabo_cooldown = "Se puede sabotear en %d:%02d",
  sabo_dark = "\\#5050ff\\Oscuridad",
  sabo_dark_desc = "¡Pone a todo el nivel en la oscuridad!",
  sabo_gas = "\\#ffff32\\Gas Toxico",
  sabo_gas_desc = "¡Hace que un gas toxico aparezca!",
  sabo_info = "Presiona %s para sabotear",
  sabo_info_rules = "\\#ff5a5a\\Cazadores\\#ffffff\\ Tambien puede probocar el caos.\nara desactivarlo, ve al nivel listado y presiona %s en el sabotaje.",
  scroll_up = "Sube para ver mas...",
  stat_crown = "ASN Corona",
  tc_only_hunter = "Solo los cazadores muertos pueden usar el chat de equipo.",
  unless_defeated = "O que sea derrotado por otro jugador",
  until_grace = "%d segundo(s) antes que el periodo de grace se acabe",

  -- tips
  tip = "Consejo: ",
  tip_1 = "¡Presiona %s, o escribe /mh, para abrir el menú. Puedes configurar opciones aquí!",
  tip_2 = "Los Ground pounds hacen 3 de daño a los otros jugadores.",
  tip_3 = "¡Una patada puede hacer 2 de daño y sacar a jugadores volando!",
  tip_4 =
  "Para ciertos comandos como /spectate y /target, puedes escribir los nombres parcialmente y seguiran funcionando. (ej: colocando \"Emily\" se referirá a EmilyEmmi)",
  tip_5 = "Puedes cambiar configuraciones en mitad de una partida desde el menú.",
  tip_6 =
  "Si algo sale mal, escribe /mh pause para pausar a todos los jugadores. Escribelo de nuevo para despausar a todos.",
  tip_7 = "¿Hay alguien saturando el chat o siendo grosero? ¡Utiliza /mh mute para silenciarlos!",
  tip_8 =
  "Puedes pausar el juego antes de recolectar una estrella o llave y darle a Exit Course para saltar la animación.",
  tip_9 =
  "Puedes seleccionar a un corredor como tu objetivo con /target. Esto revelará su ubicación en la parte superior de tu pantalla.",
  tip_10 = "Puedes configurar opciones personales en el menú (%s).",
  tip_11 =
  "¡No necesitas reiniciar el servidor! Selecciona \"Reiniciar ranura alternativa\" en \"Inicio\" para reiniciar todo el progreso.",
  tip_12 = "Puedes obtener el rol de Corredor al eliminar un Corredor.",
  tip_13 = "Como en Mario 64 vanilla, 0 vidas todavía cuentan como una vida.",
  tip_14 = "Muchos glitches, tales como el LBLJ, son inútiles fuera de Any%.",
  tip_15 = "¡Los carteles en juego pueden contener consejos útiles!",
  tip_16 = "Dire Dire Docks puede ser ingresado con una estrella menos que la categoria actual.",
  tip_17 = "Pon a Cappy en \"Damage\" para usarlo como un arma de rango. Él quita 1 de daño.",
  tip_18 = "Cappy puede recoger objetos, tales como Monedas y Secretos.",
  tip_19 = "Usa el D-Pad para lanzar a Cappy en diferentes direcciones.",
  tip_20 = "¡Mira el video de Key's Artwork en YouTube para aprender acerca de tecnología OMM!",
  tip_21 =
  "Si los objetos en un nivel empiezan a desaparecer o los teletransportes no funcionan, utiliza /mh out en ese nivel para forcar al nivel a recargarse.",
  tip_22 = "Utiliza /mh desync si tu piensas que ocurrió un error de desincronización.",
  tip_23 = "Matar a otro jugador puede restaurar toda tu vida.",
  tip_24 = "Puedes ver el progreso en llaves, gorros, y escenarios secretos en el menú de Pausa en el castillo.",
  tip_25 = "¡Los Corredores se pueden lastimar uno al otro en este modo!",
  tip_26 = "Caerse en los escenarios de gorros cuenta como perder una vida.",
  tip_27 = "Los interruptores de monedas Azules reaparecen.",
  tip_28 = "Puedes escoger otro acto para escabullirte de los Cazadores.",
  tip_29 = "¡Es una Celebración! Si no te gustan los efectos, deshabilitalos con \"Cambios de estación\" en el menú.",
  tip_30 = "Puedes espiar a los Corredores con /spectate.",
  tip_31 = "¡Utiliza /stalk para teletransportarte al nivel en el que se encuentra otro Corredor!",
  tip_32 = "Aprender técnicas de speedrunning es una buena manera para mejorar tu juego.",
  tip_33 = "Puedes atravesar Whomps mediante ground-pounding o patear mientras caen.",
  tip_34 = "La mejor manera de realizar un Salto Triple es mediante patear para el primer salto.",
  tip_35 = "La forma Metal hace el doble de daño a tus oponentes.",
  tip_36 = "La Gorra de la Invisibilidad solo te protegera de ataques de jugadores cuando sostengas %s.",
  tip_37 = "Los temporizadores de gorros no se gastan mientras estés en un cañón.",
  tip_38 = "¡No te quedes demasiado tiempo en el Selector de Actos!",
  tip_39 = "Las Zambullidas son rápidas, y zambullirse hacía otro jugador puede ayudarte a evadir ataques.",
  tip_40 = "Caerte de lugares altos puede quitarte vida en vez de matarte instantaneamente.",
  tip_41 = "Los 1-Ups van a restaurar 4 puntos de vida.",
  tip_42 = "Utiliza el menú de Jugadores para comandos que se centran en un jugador específico, como cambiar equipos.",
  tip_43 = "El menú de MarioHunt te permite comenzar partidas y configurar ajustes del juego.",
  tip_44 = "Puedes esconder tu rol de chat en Ajustes.",
  tip_45 = "Los Corredores que visten el Gorro de Metal pueden aún ser dañados por los Cazadores.",
  tip_46 = "¡En el menú, asegurate de presionar A para guardar tus ajustes cambiados!",

  -- v2.8
  default = "Predeterminado",
  gc_desc = "[MSG] - Enviar mensaje que todos los jugadores pueden ver, incluso si estas muerto; solo host/mod",
  menu_default_role = "Rol Predeterminado",
  menu_default_role_desc = "Que equipo se asigna a los nuevos jugadores.",
  menu_game_area = "Area de Juego",
  menu_game_area_desc = "Que partes del juego son accesibles. Usar \"Predeterminado\" para todos los niveles.", -- recuerda que \ es un caracter de escape. \" se muestra como " en el juego.
  menu_no_player_col = "Deshabilitar Colisión entre Jugadores",
  menu_no_player_col_desc = "Evita que los jugadores reboten o se empujen entre si. El PvP sigue funcionando!",
  menu_no_water_heal = "No Cura con Agua", -- is this correct?
  menu_old_input = "Controles Antiguos de Flechas en el Menú",
  menu_old_input_desc = "Cambia los controles de selección con flechas a como eran antes de la versión 2.8.",
  menu_pvp_type = "Modo PvP",
  menu_pvp_type_desc = "Cambia como funciona el PvP (igual que la configuracion del servidor). \"Reformado\" mejora las patadas deslizantes y permite combos de puñetazos, entre otras cosas.",
  menu_settings_player = "Preferencias",
  preset_cant_delete = "No se puede eliminar este preset!",
  preset_deleted = "Preset \"%s\" eliminado.",
  preset_desc = "[GUARDAR|CARGAR|ELIMINAR|RENOMBRAR] - Administrar presets de configuracion personal.",
  preset_not_saved = "Este preset debe guardarse antes de que puedas renombrarlo.",
  preset_save = "Guardar Preset Actual",
  preset_saved = "Preset guardado como \"%s\". Para renombrar este preset, usa /mh preset rename [nuevo nombre]",
  pvp_type_classic = "Clasico",
  pvp_type_revamped = "Reformado",
  vanish_custom = "Manten \\#ffff5a\\%s\\#ffffff\\ para evitar ataques PvP!",
}