-- Had to replace the characters that didn't exist
langdata["ro"] = -- by N64 (not to be mistaken for N64-Mario)
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "Romanian",

  -- name in the built-in menu
  name_menu = "Româna",

  -- global command info
  to_switch = "Schrie \"/lang %s\" pentru a schimba limba",
  switched = "Schimbare în Româna!", -- Replace "English" with the name of this language
  rules_command = "Schimbare /rules pentru a arata din nou mesajul",
  open_menu = "Apasa /mh sau apasa L + Porneste in meniu",
  stalk = "Foloseste /stalk a deforma la alergatori!",
  rules_desc = "- Arata MarioHunt reguli",
  rules_desc_egg = "- Arata LuigiHunt reguli",
  mh_desc = "[COMMAND,ARGS] - Executa comenzile; Scrie nimic sau \"menu\" pentru a dischide meniul",
  lang_desc = "%s - Schimba limba",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Comutati modul greu pentru dvs",
  tc_desc = "[ON|OFF|MSG] - Trimite mesaj numai echipei; activati pentru a se aplica tuturor mesajelor",
  stats_desc = "- Afisati/ascundeti tabelul cu statistici",
  stalk_desc = "[NAME|ID] - Se deformeaza la nivelul in care se afla jucatorul specificat sau primul alergator",
  spectate_desc =
  "[NAME|ID|STOP] - Vizionati playerul specificat, camera libera daca nu este specificata sau OFF pentru a dezactiva", -- not to be confused
  target_desc = "[NAME|ID] - Setati acest Alergator ca tinta, care afiseaza locatia lui in orice moment.",

  -- roluri
  runner = "Alergator",
  runners = "Alergatori",
  short_runner = "Alerg", -- unused
  hunters = "Vânatori",
  hunter = "Vânator",
  spectator = "Spectator",
  player = "Jucator",
  players = "Jucatori",
  all = "Toti",

  -- rules
  welcome = "Bine ai venit la \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! CUM Sa JOCI:",
  welcome_mini = "Bine ai venit la \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! CUM Sa JOCI:",
  welcome_mys = "Bine ai venit la \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! CUM Sa JOCI:",
  welcome_egg = "Bine ai venit la \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! CUM Sa JOCI:",
  all_runners = "Morti toti \\#00ffff\\Alergatori\\#ffffff\\.",
  any_runners = "Învinge orice \\#00ffff\\Alergatori\\#ffffff\\.",
  shown_above = "(arata de mai sus)",
  any_bowser = "Înfrângere %s prin \\#ffff5a\\orice\\#ffffff\\ inseamna necesar.",
  collect_bowser = "Colectare \\#ffff5a\\%d stele(s)\\#ffffff\\ si înfrângere %s.",
  mini_collect = "Fi primul la \\#ffff5a\\aduna steaua\\#ffffff\\.",
  collect_only = "Colectare \\#ffff5a\\%d stele(s)\\#ffffff\\.",
  thats_you = "(asta esti tu!)",
  banned_glitchless = "NU: Echipe încrucisate, BLJs, taierea de perete, blocare, campare.",
  banned_general = "NU: Echipe încrucisate, blocare, campare.",
  time_needed = "%d:%02d a parasi orice etapa principala; aduna stele pentru a reduce",
  stars_needed = "%d stele(s) a parasi orice etapa principala",
  become_hunter = "deveni \\#ff5a5a\\Vânatori\\#ffffff\\ când este învins",
  become_runner = "Invinge \\#00ffff\\Alergatori\\#ffffff\\ a devenit unul",
  infinite_lives = "Vieti infinite",
  spectate = "Schrie \"/spectate\" pentru a te uita",
  mini_goal = "\\#ffff5a\\Cine aduna cele mai multe stele in %d:%02d castiga!\\#ffffff\\",
  fun = "Distractie placuta!",

  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ câstigat!", -- team name is placed here
  can_leave = "\\#5aff5a\\Poti iesi din curs",
  cant_leave = "\\#ff5a5a\\Nu poti iesi din curs",
  time_left = "Poti pleca în \\#ffff5a\\%d:%02d",
  stars_left = "Nevoie \\#ffff5a\\%d star(s)\\#ffffff\\ to leave",
  in_castle = "În castel",
  until_hunters = "%d secunde(s) pâna \\#ff5a5a\\Vânatori\\#ffffff\\ încep",
  until_runners = "%d secunde(s) pâna \\#00ffff\\Alergatori\\#ffffff\\ încep",
  lives_one = "1 viata",
  lives = "%d vieti",
  stars_one = "1 stea",
  stars = "%d stele",
  no_runners = "Nu \\#00ffff\\Alergatori!",
  camp_timer = "Continua sa the misti! \\#ff5a5a\\(%d)",
  game_over = "Jocul s-a terminat!",
  winners = "Câstigatori: ",
  no_winners = "\\#ff5a5a\\Nici un câstigator!",
  death_timer = "Mort",
  mini_score = "Scor: %d",
  new_record = "\\#ffff5a\\NOU RECORD!!!",
  on = "\\#5aff5a\\PORNIT",
  off = "\\#ff5a5a\\OPRIT",
  frozen = "Înghetat pentru %d",

  -- popups
  lost_life = "%s\\#ffa0a0\\ pierdut o viata!",
  lost_all = "%s\\#ffa0a0\\ pierdut toate vietile!",
  now_role = "%s\\#ffa0a0\\ acum e %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ ai luat steaua!",
  got_key = "%s\\#ffa0a0\\ ai luat cheia!",
  rejoin_start = "%s\\#ffa0a0\\ are doua minute pentru a reveni.",
  rejoin_success = "%s\\#ffa0a0\\ a intrat la timp!",
  rejoin_fail = "%s\\#ffa0a0\\ nu sa conectat la timp.",
  using_ee = "Aceasta foloseste numai Extreme Edition.",
  not_using_ee = "Aceasta utilizeaza numai editia standard.",
  killed = "%s\\#ffa0a0\\ omorât %s!",
  sidelined = "%s\\#ffa0a0\\ terminat %s!",
  paused = "Ai pus pauza.",
  unpaused = "Nu mai ai pauza.",
  kill_combo_2 = "%s\\#ffa0a0\\ a fost \\#ffff5a\\de doua ori\\#ffa0a0\\ mort!",
  kill_combo_3 = "%s\\#ffa0a0\\ a fost \\#ffff5a\\de trei ori\\#ffa0a0\\ mort!",
  kill_combo_4 = "%s\\#ffa0a0\\ a fost \\#ffff5a\\de patru ori\\#ffa0a0\\ mort!",
  kill_combo_5 = "%s\\#ffa0a0\\ a fost \\#ffff5a\\de cinci ori\\#ffa0a0\\ mort!",
  kill_combo_large = "\\#ffa0a0\\Wow! %s\\#ffa0a0\\ a facut \\#ffff5a\\%d\\#ffa0a0\\ a omorât la rând!",
  set_hack = "Hack pus la %s",
  incompatible_hack = "AVERTIZMANT: Hackul nu este compatibil!",
  vanilla = "Folosind jocul vanila",
  omm_detected = "OMM Rebirth detectat!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth este depasit!\\#ffffff\\\nMinimum version: %s\nYour version: %s",
  warp_spam = "Iao mai încet cu urzeala!",
  no_valid_star = "Nu s-a putut gasi o stea valida!",
  custom_enter = "%s\\#ffffff\\ intrat\n%s", -- same as coop
  ---- vanish_custom = "tine \\#ffff5a\\%s\\#ffffff\\ pentru a fi invisibil!",
  got_all_stars = "Ai destule stele!",
  unstuck = "Încercarea de a remedia starea",
  use_out = "Foloseste /mh pentru a deforma pe toata lumea din acest nivel",
  stars_in_area = "%d stele(s) valabile aici!",
  demon_unlock = "Modul Green Demon deblocat!",
  hit_switch_red = "%s\\#ffa0a0\\ a activat\n\\#df5050\\Comutatorul Rosu!",        -- dark red (unique)
  hit_switch_green = "%s\\#ffa0a0\\ a activat\n\\#50b05a\\Comutatorul Verde!",     -- dark green (unique)
  hit_switch_blue = "%s\\#ffa0a0\\ a activat\n\\#5050e3\\Comutatorul Albastru!",   -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ a activat\n\\#e3b050\\Comutatorul Galben...", -- orangeish (unique)

  -- command feedback
  not_mod = "Tu nu ai permisiune de a folosi comanda, prostule!",
  no_such_player = "Nu exista un asemena de jucator",
  bad_id = "ID jucatorului nu este!",
  command_disabled = "Comanda aceasta este dezacrivata.",
  change_setting = "Setari schimbate:",
  you_are_muted = "Tu esti acum mut.",

  -- more command feedback
  bad_param = "Parametri invalidi!",
  bad_command = "Comanda invalida!",
  error_no_runners = "Nu poti începe jocul cu 0 alergatori!",
  set_team = "%s's echipele au fost setate la '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "Jocul nu a început înca",
  set_lives_one = "%s acum ai 1 viata",
  set_lives = "%s acum are %d vieti",
  not_runner = "%s nu este un Alergator",
  may_leave = "%s poate pleca",
  must_have_one = "Trebuie cel puti un Vânator",
  added = "Alergatori adaugati: ", -- list comes afterward
  no_runners_added = "Nici un Alergator nu a fost adaugat",
  runners_are = "Alergatori sunt: ",
  set_lives_total = "Viata alergatorilor setata la %d",
  wrong_mode = "Nu este disponibil în acest mod",
  need_time_feedback = "Alergatori pot iesi în %d secunde(s) acum",
  game_time = "Jocul dureaza acum %d secunde(s)",
  need_stars_feedback = "Alergatori au nevoie %d stele(s) acum",
  new_category = "Acum este un %d stea alergatoare",
  new_category_any = "Acum este any% alerga",
  mode_normal = "În modul Normal",
  mode_swap = "În modul Schimbator",
  mode_mini = "În modul Minivânatoare",
  using_stars = "Folosind stelele colectate",
  using_timer = "Folosind und cronometru",
  can_spectate = "Vînîtori pot acum privi",
  no_spectate = "Vânatorii nu mai pot privi",
  all_paused = "Toti jucatori au luat o pauza",
  all_unpaused = "Toti jucatorii au reluat pauza",
  player_paused = "%s a fost întrerupta",
  player_unpaused = "%s a fost întrerupta",
  hunter_metal = "Toti vânatorii sunt din metal",
  hunter_normal = "Toti vânatorii par normali",
  hunter_glow = "Toti vânatorii stralucesc rosu",
  hunter_outline = "Toti vânatorii au un contur",
  runner_sparkle = "Toti alergatorii stralucesc acum",
  runner_normal = "Toti alergAll runners have an outlineatorii par normalil",
  runner_glow = "Toti alergatorii stralucesc acum",
  runner_outline = "Toti alergatorii au un contur",
  now_weak = "Toti jucatorii au jumatate de cadre de invincibilitate",
  not_weak = "Toti jucatorii au cadre de invincibilitate normale",
  auto_on = "Jocurile vor începe automat",
  auto_off = "Jocurile nu vor porni automat",
  force_spectate = "Toata lumea trebuie sa priveasca",
  force_spectate_off = "Spectacolul nu mai este fortat",
  force_spectate_one = "%s trebuie sa priveasca",
  force_spectate_one_off = "%s nu mai trebuie sa priveasca",
  blacklist_add = "Pe lista neagra %s",
  blacklist_remove = "Pe lista alba %s",
  blacklist_add_already = "Acea stea sau nivel este deja pe lista neagra.",
  blacklist_remove_already = "Acea stea sau nivel nu este pe lista neagra.",
  blacklist_remove_invalid = "Nu pot fi listata în alb aceasta stea sau nivel.",
  blacklist_list = "Pe lista neagra:",
  blacklist_reset = "Resetati lista neagra!",
  blacklist_save = "Lista neagra a fost salvata!",
  blacklist_load = "Lista neagra a fost încarcata!",
  anarchy_set_0 = "Alergatorul poate sa îsi atace echipa",
  anarchy_set_1 = "Alergatorii îsi pot ataca colegii",
  anarchy_set_2 = "Vânatorii îsi pot ataca colegii de echipa",
  anarchy_set_3 = "Jucatorii îsi pot ataca colegii",
  dmgAdd_set = "Alergatorii vor primi acum %d daune suplimentare din atacurile PVP.",
  dmgAdd_set_ohko = "Alergatorii vor muri acum dintr-o lovitura",
  voidDmg_set = "Jucatorii vor primi %d daune din caderea în gol sau nisipuri miscatoare.",
  voidDmg_set_ohko = "Jucatorii vor muri instantaneu din cauza caderii în gol sau în nisipuri miscatoare.",
  target_hunters_only = "Doar vânatorii pot stabili o tinta.",
  muted = "\\#ffff00\\%s\\#ffffff\\ a fost dezactivat de \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ a fost activat de \\#ffff00\\%s\\#ffffff\\.",
  you_muted = "Tu ai dezactivat \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Tu ai dezactivat\\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ a fost dezactivat automat.",

  -- team chat
  tc_toggle = "Chatul în echipa este %s!",
  to_team = "\\#8a8a8a\\La echipa: ",
  from_team = "\\#8a8a8a\\ (echipa): ",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ a votat pentru a omite aceasta stea",
  vote_info = "Tastati /skip pentru a vota",
  vote_pass = "Votul a trecut!",
  already_voted = "Ai votat deja.",

  -- hard mode
  hard_notice = "Psst, încearca sa tastezi /hard...",
  extreme_notice = "Psst, încearca sa tastezi /hard ex...",
  hard_toggle = "\\#ff5a5a\\Modul Greu\\#ffffff\\ este %s!",
  extreme_toggle = "\\#b45aff\\Modul Extrem\\#ffffff\\ este %s!",
  hard_info = "Interesat în \\#ff5a5a\\Hard Mode\\#ffffff\\?" ..
      "\n- Jumate de viata" ..
      "\n- Fara regen de la apa" ..
      "\n- \\#ff5a5a\\O viata" ..
      "\n\\#ffffff\\Tastati /hard ON daca sunteti pregatit pentru provocare.",
  extreme_info = "Esti atras de \\#b45aff\\Modul Extrem\\#ffffff\\? Ce prostie." ..
      "\n- O viata" ..
      "\n- O sanatate" ..
      "\n- \\#b45aff\\Cronometrul mortii\\#ffffff\\; aduna monede si stele pentru a creste" ..
      "\nIf asta nu te sperie, tastati /hard ex ON.",
  no_hard_win = "Scorul dvs. de câstiguri dure sau extreme nu va fi actualizat pentru acest joc.",
  hard_mode = "Modul Greu",
  extreme_mode = "Modul Extrem",
  hard_info_short = "Jumatate de sanatate, fara apa vindecare si o viata.",
  extreme_info_short = "Un singur cronometru pentru sanatate, viata si moarte.",

  -- spectator
  hunters_only = "Numai vânatorii pot privi!",
  spectate_disabled = "Spectatia este dezactivata!",
  timer_going = "Nu pot privi în timpul cronometrului!", -- now unused
  spectate_self = "Nu te poti privi!",
  spectator_controls = "Controale:" ..
      "\nDPAD-UP: Opriti hud-ul" ..
      "\nDPAD-DOWN: Schimbati vizualizarea freecam/player" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Schimbati jucatorul" ..
      "\nJOYSTICK: Misca" ..
      "\nA: Dute sus" ..
      "\nZ: Dute jos" ..
      "\nType \"/spectate OFF\" pentru a anula",
  spectate_off = "Nu mai privesc.",
  empty = "GOL (%d )",
  free_camera = "CAMERA GRATUITA",
  spectate_mode = "- MOD SPECTATOR -",
  is_spectator = '* JUCATORUL ESTE UN SPECTATOR  *',

  -- stats
  disp_wins_one = "%s\\#ffffff\\ a câstigat 1 data ca \\#00ffff\\Alergator\\#ffffff\\!",
  disp_wins = "%s\\#ffffff\\ a câstigat de %d ori ca \\#00ffff\\Alergator\\#ffffff\\!",
  disp_kills_one = "%s\\#ffffff\\ a ucis 1 jucator!", -- unused
  disp_kills = "%s\\#ffffff\\ a ucis %d jucatori!",
  disp_wins_hard_one =
  "%s\\#ffffff\\ a câstigat 1 data ca \\#ffff5a\\Runner\\#ffffff\\ în \\#ff5a5a\\Modul Greu!\\#ffffff\\",
  disp_wins_hard =
  "%s\\#ffffff\\ a câstigat de %d ori ca \\#ffff5a\\Runner\\#ffffff\\ în \\#ff5a5a\\Modul Greu!\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ a câstigat 1 data ca \\#b45aff\\Runner\\#ffffff\\ în \\#b45aff\\Modul Extrem!\\#ffffff\\",
  disp_wins_ex =
  "%s\\#ffffff\\ a câstigat de %d ori ca \\#b45aff\\Runner\\#ffffff\\ în \\#b45aff\\Modul Extrem!\\#ffffff\\",
  -- for stats table
  stat_wins_standard = "Învingeri",
  stat_wins = "Învingeri (Minihunt/pre v2.3)",
  stat_wins_mys = "Învingeri (MysteryHunt)",
  stat_kills = "Ucideri",
  stat_combo = "Maximul de Ucideri Strike",
  stat_wins_hard_standard = "Învingeri (Modul Greu)",
  stat_wins_hard = "Învingeri (Modul Greu, MiniHunt/pre v2.3)",
  stat_wins_hard_mys = "Învingeri (Modul Greu, MysteryHunt)",
  stat_mini_stars = "Maximum de stele într-un singur joc de MiniHunt",
  stat_placement = "64 Plasare în tur",
  stat_wins_ex_standard = "Învingeri (Modul Extrem)",
  stat_wins_ex = "Învingeri (Modul Extrem, MiniHunt/pre v2.3)",
  stat_wins_ex_mys = "Învingeri (Modul Extrem, MysteryHunt)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: Primul Loc]",
  place_2 = "\\#c5d8de\\[64T: Doilea Loc]",
  place_3 = "\\#b38752\\[64T: Treilea Loc]",
  place = "\\#e7a1ff\\[64T: %dPatrulea Loc]", -- thankfully we don't go up to 21
  place_score_1 = "%dprimul",
  place_score_2 = "%ddoilea",
  place_score_3 = "%dtrilea",
  place_score = "%dpatrulea",

  -- chat roles
  role_lead = "\\#9a96ff\\[Conducator MH Dev]",
  role_dev = "\\#96ecff\\[MH Dev]",
  role_cont = "\\#ff9696\\[Colaborator MH]",
  role_trans = "\\#ffd996\\[MH Traducator]",

  -- command descriptions
  page = "\\#ffff5a\\Pagina %d/%d", -- page for mariohunt command
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Începe jocul; adauga \"continue\" a nu deforma pentru a începe; adauga \"alt\" pentru alt fisier de salvare; adauga \"main\" pentru fisierul de salvare principal; adauga \"reset\" prentru a reseta fisierele",
  add_desc = "[INT] - Adauga aleatoriu cantitatea specificata de alergatorim",
  random_desc = "[INT] - Alege aleatoriu numarul specificat de alergatori",
  random_desc_hunt = "[INT] - Alege aleatoriu numarul specificat de vânatori",
  lives_desc =
  "[INT] - Seteaza numarul de vieti pe care le au alergatorii, de la 0 la 99 (nota: 0 vieti este înca 1 viata)",
  time_desc =
  "[NUM] - Seteaza timpul pe care alergatorii trebuie sa astepte pentru a pleca, în secunde, sau durata jocului în MiniHunt.",
  stars_desc =
  "[INT] - Seteaza cantitatea de stele pe care alergatorii trebuie sa le colecteze pentru a pleca, de la 0 la 7 (doar în modul stea)",
  category_desc =
  "[INT] - Stabileste numarul de stele pe care alergatorii trebuie sa le aiba pentru a se confrunta cu Bowser.",
  flip_desc = "[NAME|ID] - Întoarce echipa jucatorului specificat",
  setlife_desc = "[NAME|ID|INT,INT] - Seteaza durata de viata specificata pentru alergatorul specificat",
  leave_desc = "[NAME|ID] - Permite jucatorului specificat sa paraseasca nivelul daca este un alergator",
  mode_desc = "[NORMAL|SWAP|MINI] - Changes game mode; Swap switches runners when one dies",
  starmode_desc = "[ON|OFF] - Comuta utilizarea stelelor colectate în loc de timp",
  spectator_desc = "[ON|OFF] - Comuta capacitatea vânatorilor de a privi",
  pause_desc =
  "[NAME|ID|ALL] - Comuta starea de pauza pentru jucatorii specificati sau pentru toti daca nu este specificat",
  hunter_app_desc = "Schimba aspectul vânatorilor.",
  runner_app_desc = "Schimba aspectul alergatorilor.",
  hack_desc = "[STRING] - Seteaza hack-ul actual al romului",
  weak_desc = "[ON|OFF] - Reduce cadrele de invincibilitate la jumatate pentru toti jucatorii",
  auto_desc = "[ON|OFF|NUM] - Porniti jocurile automat",
  forcespectate_desc = "[NAME|ID|ALL] - Comutati fortarea spectatorului pentru acest jucator sau pentru toti jucatorii",
  desync_desc = "- Încercari de a remedia erorile de desincronizare",
  stop_desc = "- Opreste jocul",
  default_desc = "- Setati setarile la început",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] -Lista neagra a vedetelor din MiniHunt",
  stalking_desc = "[ON|OFF] - Permite deformarea la nivelul unui alergator cu /stalk",
  mute_desc = "[NAME|ID] - Dezactiveaza un jucator, împiedicându-l sa converseze",
  unmute_desc = "[NAME|ID] - Activeaza sunetul unui jucator, permitându-i sa discute din nou",
  out_desc = "[LEVEL|COURSE] - Scoate pe toti din acest nivel",

  -- Blocky's menu
  main_menu = "Meniu principal",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  --menu_settings_player = "Setari",
  menu_rules = "Reguli",
  menu_list_settings = "Setari lista",
  menu_list_settings_desc = "Listeaza toate setarile pentru acest lobby.",
  menu_lang = "Limba",
  menu_misc = "Muzica",
  menu_stats = "Statistici",
  menu_back = "Înapoi",
  menu_exit = "Iesi",

  menu_run_random = "Randomizati alergatorii",
  menu_run_add = "Adaugati alergatori",
  menu_hunt_random = "Randomizati vânatorii",
  menu_run_lives = "Vietile alergatorului",
  menu_settings = "Setarile jocului",

  menu_start = "Porneste",
  menu_stop = "Opreste",
  menu_save_main = "Principal",
  menu_save_alt = "Alt Salvare",
  menu_save_reset = "Resetati Alt Salvare",
  menu_save_continue = "Continua (fara deformare înapoi)",
  menu_random = "Aleatoriu",
  menu_campaign = "Campanie",
  menu_coop = "Înpreuna", -- unused

  menu_gamemode = "Mod de joc",
  menu_hunter_app = "Aspectul vânatorului",
  menu_runner_app = "Aspectul alergatorilor",
  menu_weak = "Modul Slab",
  menu_allow_spectate = "Permite Spectating",
  menu_star_mode = "Modul Stea",
  menu_category = "Categorie",
  menu_time = "Timp",
  menu_stars = "Stele",
  menu_auto = "Joc Auto",
  menu_blacklist = "Lista neagra MiniHunt",
  menu_default = "Reseteaza la Început",
  menu_anarchy = "Bataie prieteneasca",
  menu_anarchy_desc = "Permite echipelor specificate sa-si atace colegii.",
  menu_dmgAdd = "Alergatorul în PVP LOVITURA MARE",  -- DMG is "damage"
  menu_dmgAdd_desc = "Adaugati atât de mult daune la atacurile împotriva alergatorilor.",
  menu_nerf_vanish = "Sapca Nerf de Invisibilitate", -- Nerf, as in to reduce power for balancing
  -- menu_nerf_vanish_desc = "Capacul Nerfs dispare facându-l comutabil si se scurge mai repede atunci când este utilizat.",
  menu_first_timer = "Lider Mort Timp",
  menu_first_timer_desc = "Ofera liderului din MiniHunt un cronometru al mortii.",
  menu_defeat_bowser = "Înfrângere %s",
  menu_allow_stalk = "Permite ,,Stalking\"",
  menu_countdown = "Numaratoare inversa",
  menu_countdown_desc = "Cât timp trebuie sa astepte vânatorii înainte de a începe.",
  menu_voidDmg = "LOVITURA din Void",
  menu_voidDmg_desc = "Daunele aduse jucatorilor care cad în gol sau nisipuri miscatoare.",
  menu_double_health = "Sanatate dublu", -- is this correct?
  menu_double_health_desc = "Jucatorii primesc 16 puncte de sanatate în loc de 8.",
  menu_star_heal = "Viata stelelor",

  menu_flip = "Schimba echipa",
  menu_spectate = "Spectator",
  menu_stalk = "Teleporteazate la un Nivel",
  menu_stalk_desc = "Teleporteazate la nivelul acestui jucator.",
  menu_pause = "Pauza",
  menu_forcespectate = "Forzeaza pe Spectator",
  menu_allowleave = "Permite pentru a Iesi",
  menu_setlife = "Seteaza Vieatile",
  menu_players_all = "Toti Jucatori",
  menu_target = "Pune ca si o tinta",
  menu_mute = "Mut",

  menu_timer = "Cronometru de Rulare Rapida",
  menu_timer_desc = "[ON|OFF] - Afisati un cronometru în partea de jos a ecranului în modurile Standard.",
  menu_tc = "Chat în echipa",
  menu_tc_desc = "Chat numai cu echipa ta.",
  menu_demon = "Demonul Verde", -- referr
  menu_demon_desc = "Ai un 1-Up sa te urmareasca ca alergator.",
  menu_unknown = "???",
  menu_secret = "Este un secret. Cum îl deblochezi?",
  menu_hide_roles = "Ascundemi rolul meu",
  menu_hide_roles_desc = "Ascundeti-va rolurile pentru a nu se afisa în chat.",
  menu_hide_hud = "Ascunde HUD",
  hidehud_desc = "- Ascunde toate elementele HUD.",
  menu_fast = "Actiuni mai rapide",
  menu_fast_desc = "Va veti recupera, aruncati obiecte si deschideti usi mai repede.",
  menu_popup_sound = "Sunetul pop-up",
  menu_season = "Schimbari sezoniere",
  menu_season_desc = "Schimbari vizuale distractive în functie de data.",

  menu_free_cam_desc = "Introduceti Camera gratuita în modul Spectator.",
  menu_spectate_run = "Spectator pe Alergatori",
  menu_spectate_run_desc = "Priveste automat primul alergator.",
  menu_exit_spectate = "Iesi din Spectator",
  menu_exit_spectate_desc = "Iesi din modul Spectator.",
  menu_stalk_run = "Teleporteazate la Nivelul alergatorului",
  menu_stalk_run_desc = "Deformati pâna la nivelul în care se afla primul alergator.",
  menu_skip = "Omite",
  menu_skip_desc = "- Votati pentru a omite aceasta stea în MiniHunt.",

  menu_spectate_desc = "Priveste acest jucator.",

  menu_blacklist_list = "Listati toate pe lista neagra",
  menu_blacklist_list_desc = "Listeaza toate vedetele aflate pe lista neagra din MiniHunt pentru acest server.",
  menu_blacklist_save = "Salveaza lista Neagra",
  menu_blacklist_save_desc = "Salvati aceasta lista neagra de la capatul vostru.",
  menu_blacklist_load = "Încarcati lista neagra",
  menu_blacklist_load_desc = "Încarcati lista neagra salvata.",
  menu_blacklist_reset = "Resetati lista neagra",
  menu_blacklist_reset_desc = "Resetati lista neagra la valoarea implicita.",
  menu_toggle_all = "Comutati toate",

  -- updater
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Vânatoare\\#ffffff\\ este la zi!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Vânatoare\\#ffffff\\ este la zi!",
  has_update = "O actualizare este disponibila pentru \\#00ffff\\Mario\\#ff5a5a\\Vânatoare\\#ffffff\\!",
  has_update_egg = "O actualizare este disponibila pentru \\#5aff5a\\Luigi\\#ff5a5a\\Vânatoare\\#ffffff\\!",

  -- 2.6 stuff that I don't feel like sorting
  leave_error = "%s\\#ffa0a0\\ lasat din cauza unei erori.",
  hunter_color = "Toti vânatorii au paleta Burgundy",
  runner_color = "Toti alergatorii au paleta Azure",
  stat_playtime = "Timp de joaca (Ore)",
  stat_parkour_time = "Cel mai rapid timp de parkour",
  stat_parkour_time_omm = "Cel mai rapid timp de parkour (OMM)",
  stat_parkour_time_other = "Cel mai rapid timp de parkour (Moveset)",
  menu_free_roam = "Roam liber",
  menu_free_roam_desc = "Dezactiveaza cerintele Star si Key pentru usi si majoritatea nivelurilor.",
  menu_radar = "Radarul",
  menu_radar_desc = "Arata unde sunt alergatorii si obiectele importante.",
  menu_minimap = "Miniharta",
  menu_minimap_desc = "Afiseaza o harta a întregului nivel.",
  menu_romhack_cam = "Camera de la Romhack",
  menu_romhack_cam_desc = "Activeaza camera rom hack in orice moment.",

  -- v2.7
  added_count = "Adaugare %d alergator",
  added_count_one = "Adaugare 1 alergator",
  become_spectator = "a devenit \\#a9a9a9\\Spectator\\#ffffff\\ cand moare",
  connected = "%s\\#ffff5a\\ conectat!",
  dead = "Mort",
  dead_become = "Mort \\#00ffff\\Alergatori\\#ffffff\\ a lasat un corp in spate.",
  dead_become_infection = "Jucatori morti care nu sunt \\#ff5a5a\\Vanatori\\#ffffff\\ lasat un corp in spate.",
  dead_become_noconfirm = "Jucatori morti lasa corp in spate.",
  disconnected = "%s\\#ffa0a0\\ desconectat",
  disp_asn_bronze = "%s\\#ffffff\\ a avut \\#b38752\\bronz\\#ffffff\\ in ASN Turneu!",
  disp_asn_quarter = "%s\\#ffffff\\ au ajus in \\#70ff94\\sferturi de finala\\#ffffff\\ in ASN Turneu!",
  disp_asn_silver = "%s\\#ffffff\\ are \\#c5d8de\\argint\\#ffffff\\ in ASN Turneu!",
  disp_asn_win = "%s \\#e3bc2d\\castigat\\#ffffff\\ in ASN Turneu!",
  far = "\\#8a8a8a\\(departe)",
  global_talk_end = "\\#ffa0a0\\Chatul global a vost inschis.",
  global_talk_start = "\\#ffa0a0\\Chatul global este pornit pentru %d secunde(s).",
  guard_cooldown = "Poate pazi in %d",
  guard_info = "Apasa %s pentru a apara %s",
  guard_info_rules = "Jucatori morti pot proteja choiechipieri sai cu %s.",
  guard_save = "\\#ffff00\\O fantoma tea salvat de la moarte!",
  guard_timer = "%s\\#ffff00\\ ie aparat (%d)",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Vanatori\\#ffa0a0\\ ramasi.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Vanatori\\#ffa0a0\\ ramasi",
  players_remain = "\\#ffa0a0\\%d jucatori ramasi.",
  players_remain_one = "\\#ffa0a0\\1 jucatori ramasi",
  hunters_set_count = "Mai sunt %d vanatori",
  hunters_set_count_one = "Mai este 1 vanator",
  hunters_were = "Vanatori sunt: ",
  keep_secret = "Nu fi prins!",
  menu_binds = "Scaimba leaga",
  menu_binds_desc = "Schimbati butoanele folosite pentru diferite actiuni.",
  menu_confirm_hunter = "Confirmare Vanatori Morti",
  menu_confirm_hunter_desc = "Afiseaza un mesaj ori de cate ori un vanator este ucis.Daca sunt dezactivatii, vanatorii lasa in urma si cadavre",
  menu_global_chat = "Timpul pentru chat global",
  menu_global_chat_desc = "Jucatorii de timp pot vorbi cand un cadavru este gasit.",
  menu_grace_period = "Perioada de gratie",
  menu_grace_period_desc = "Timp pana jucatori pot fi omorati.",
  menu_guard_button = "Apara",
  menu_guard_button_desc = "Buttonul apasat ca sa aperi jucatorul in modul spectator in MysteryHunt.",
  menu_hunters_win_early = "Vanatori castiga mai devreme",
  menu_hunters_win_early_desc = "Hunters win when they match/exceed the amount of Runners, like in Among Us.",
  menu_invinc_particle = "Schlipirea I-Fraimulilor",
  menu_invinc_particle_desc = "Unlocuieste de \"clipind\" efect cand Mario se loveste apar particule de schlipici.",
  menu_know_team = "Vanatori is stiu coechipieri",
  menu_know_team_desc = "Vanatori stiu care sunt coechipieri sai. Daca dezactivezi, Vanatori pot chiar sa se omoare uni pe alti.",
  menu_menu_button = "Deschide Meniul",
  menu_menu_button_desc = "Buton(s) apasat pentru a deschide meinul MarioHunt.",
  menu_overlay = "Suprapunerea progresului cursului",
  menu_overlay_desc = "Afiseaza stelele, cheile si comutatoarele de capac colectate langa pictura sau urzeala unui curs.", -- 2nd to last s is s
  menu_presets = "Presetari",
  menu_report_button = "Raport/Fixeaza",
  menu_report_button_desc = "Buton folosit pentru raportarea cadavrelor si oprirea sabotajelor in MysteryHunt.",
  menu_sabo = "Saboteaza",
  menu_sabo_button = "Deschide Meniul de Sabotare",
  menu_sabo_button_desc = "Buton(s) apasat pentru a deschide meniul Sabotaj in MysteryHunt.",
  menu_show_on_map = "Arata pe harta",
  menu_show_on_map_desc = "Ce echipe pot fi vazute pe minimaharta (Oponentii vor avea si radar)",
  menu_shuffle = "Echipa Amestecata",
  menu_shuffle_desc = "Amesteca echipele fiecarui jucator in viata in intervalul de timp selectat",
  menu_spectate_on_death = "Alergatorii privesc la moarte",
  menu_stalk_timer = "Tulpina Racire",
  menu_stalk_timer_desc = "Timpul pentru care playerul este inghetat dupa utilizare /stalk.",
  menu_star_setting = "Pe alegerea stelei",
  menu_star_stay_old = "Stai daca a fost deja colectat",
  menu_star_stay_old_desc = "Colectarea unei stele care a fost deja colectata nu te va scoate din nivel.",
  menu_star_timer = "Ora ultimei stele",
  menu_star_timer_desc = "Afiseaza cand a fost colectata ultima stea in partea de jos a ecranului.",
  menu_vanish_button = "Disparea",
  menu_vanish_button_desc = "Buton tinut pentru a activa capacul de disparitie cand \"Sapca Nerf pentru a Disparea\" este activata.",
  mode_mys = "In MysteryHunt mod",
  mystery_altgoal = "SAU: Descoperit de \\#ff5a5a\\Vanatori\\#ffffff\\ si invingei.",
  mysteryhunt_disabled = "\\#ffa0a0\\Unul dintre modurile tale nu este compatibil cu MysteryHunt!",
  mysteryhunt_innocent = "\\#ffa0a0\\Ai ucis un jucator nevinovat!",
  mysteryhunt_spectate = "\\#ffa0a0\\Vei privi acest joc.",
  nearby = "\\#8a8a8a\\(aproape)",
  no_players_here = "Nici un alt jucator a fost gasit!",
  no_runners_here = "Nici \\#00ffff\\Jucator\\#ffffff\\ aici!",
  opponents = "Adversarii",
  other_hunters = "Alti fanatori sunt: ",
  place_asn = "\\#e7a1ff\\[ASN Participare]",
  place_asn_1 = "\\#e3bc2d\\[ASN Castigatori]",
  place_asn_2 = "\\#c5d8de\\[ASN Argint]",
  place_asn_3 = "\\#b38752\\[ASN Bronz]",
  place_asn_4 = "\\#70ff94\\[ASN Sferturi de finala]",
  preset_asn = "ASN Tourney",
  preset_asn_desc = "Aceleasi setari utilizate in ASN Tourney (cu o viata extra).",
  preset_classic = "Classic",
  preset_classic_desc = "Modifica setarile pentru a se potrivi cu versiunile vechi ale MarioHunt.",
  preset_infection = "Infectie",
  preset_infection_desc = "1 vanator care poate face o singura lovitura! Pot alergatorii sa supravietuiasca?",
  preset_quick = "Joc Rapid",
  preset_quick_desc = "30 Stele, Umbla Gratuit, Fara Bowser run.",
  preset_solo = "Solo",
  preset_solo_desc = "Esti pe cont propriu! 3 vieti si sanatate dubla.",
  preset_star_rush = "Papura de stele",
  preset_star_rush_desc = "Minihunt, dar toata lumea este un alergator!",
  preset_tag = "Eticheta",
  preset_tag_desc = "Loviti un alergator pentru a deveni instantaneu unul!",
  press_fix = "%s - Fixeaza",
  press_report = "%s - Raporteaza",
  report_body = "%s\\#ffa0a0\\ gasit %s's\\#ffa0a0\\ corp in \\#ffff5a\\",
  report_info_rules = "Apasati pe %s pentru a le raporta si a discuta.",
  role_dead = "\\#ff2020\\[MORT]",
  rule_command = "Scrie /rules pentru a afisa din nou acest mesaj",
  runners_can_kill = "\\#00ffff\\Alergatori\\#ffffff\\ poate invinge jucatori pe care i banuiesc ca sunt \\#ff5a5a\\Vanatori\\#ffffff\\.\nDaca ucid un nevinovat, mor si ei.", -- si is și
  runners_remain = "%d \\#00ffff\\Alergatori\\#ffffff\\ ramas.",
  runners_remain_one = "1 \\#00ffff\\Alergatori\\#ffffff\\ ramas.",
  sabo_activate_timer = "Activate in %d",
  sabo_active = "\\#ffff00\\SABOTAJ ACTIVAT!",
  sabo_bomb = "\\#ff4040\\Mega Bomba",
  sabo_bomb_desc = "Omoara toti jucatorii daca nu este dezactivat!",
  sabo_bomb_timer = "\\#ff4040\\Toatalumea va mori in %d:%02d",
  sabo_cooldown = "Poti sabota in %d:%02d",
  sabo_dark = "\\#5050ff\\Intuneric",
  sabo_dark_desc = "Acopera lumea in intuneric!",
  sabo_gas = "\\#ffff32\\Gas Toxic",
  sabo_gas_desc = "Face sa apara gaze toxice!",
  sabo_info = "Apasa %s pentru a sabota",
  sabo_info_rules = "\\#ff5a5a\\Vanatori\\#ffffff\\ poate provoca, de asemenea, haos prin sabotaj.\nPentru a dezactiva un sabotaj, mergeti la nivelul afisat si apasati pe %s pe sabotaj.", -- si is și
  scroll_up = "Derulati sus pentru mai multe...",
  shuffle_timer = "Amestecarea echipelor in %d",
  star_leave = "Pleaca",
  star_nonstop = "Non-Stop",
  star_stay = "Stai",
  stat_crown = "ASN Coroana",
  stat_placement_asn = "ASN Tourney Plasarea",
  tc_only_hunter = "Doar vanatorii in viata pot folosi chatul in echipa.",
  unless_defeated = "cu exceptia cazului in care este invins de un alt jucator",
  unsaved_changes = "\\#ff5a5a\\Ai modificari nesalvate! Apasati din nou daca sunteti sigur.",
  until_grace = "%d secunda(e) pana la sfarsitul perioadei de gratie",

  -- Tips:
  tip = "Tip: ",
  tip_1 = "Apasati %s sau tastati /mh pentru a deschide meniul. Puteti configura setarile aici!",
  tip_2 = "Lirele de pamant fac 3 din viata altor jucatori.",
  tip_3 = "O lovitura va provoca 2 daune si va trimite jucatorii in zbor!", -- si is și
  tip_4 = "Pentru comenzi precum /spectate si /target, puteti introduce nume partiale si vor functiona in continuare (ex: entering \"Emily\" will refer to EmilyEmmi)",
  tip_5 = "Poti schimba setarile in joc in meniu.",
  tip_6 = "Daca cheva nu merge, scrie /mh pauza pentru a intrerupe toti jucatorii. Scrie din now pentru a intrerupe.",
  tip_7 = "Cineva trimite spam sau foloseste insulte? Folosteste /mh pentru a le da mut!",
  tip_8 = "Puteti intrerupe jocul inainte de a colecta o stea sau o cheie si a iesi din curs pentru a sari peste animatie.",
  tip_9 = "Puteti targheta un alergator cu /target. Aceasta va afisa locația lor in partea de sus a ecranului.",
  tip_11 = "Nu trebuie sa restartezi servarul! Selecteaza \"Reset Alt Save\" in \"Start\" pentru a reseta tot progresul.",
  tip_10 = "Puteti configura setarile personale in meniu (%s).",
  tip_12 = "Puteti obtine rolul de alergator invingand un alergator.",
  tip_13 = "Ca si in vanilla Mario 64, 0 vieazi inca conteaza ca o viata.",
  tip_14 = "Glitchiuri majore, ca si LBLJ, sunt inutile in afara de Any%.",
  tip_15 = "Semnele din joc pot contine mai multe sfaturi utile!",
  tip_16 = "Dire Dire Docks poate fi introdus cu o stea mai putin decat categoria actuala",
  tip_17 = "Setati Cappy la \"Damage\" sa-l foloseasca ca arma la distanta. El da 1 damage.",
  tip_18 = "Cappy poate ridica obiecte, cum ar fi monede si secrete.",
  tip_19 = "Utilizati D-Pad pentru a arunca Cappy in directii diferite.",
  tip_20 = "Verifica Key's Artwork's videoclip pe YouTube pentru a afla despre tehnologia OMM!",
  tip_21 = "Daca obiectele dintr-un nivel incep sa dispara sau curbeturile nu mai functioneaza, foloseste /mh out in acel nivel pentru a forta acel nivel sa se reincarce.",
  tip_22 = "Foloseste /mh desync daca credeti ca a aparut o eroare de desincronizare.",
  tip_23 = "Uciderea unui alt jucator iti va restabili intreaga viaza.",
  tip_24 = "Puteți vedea progresul pe taste, majuscule si etapele secrete in meniul Pauza din castel.", -- si is și
  tip_25 = "Alergatorii se pot rani unul pe altul in acest mod!",
  tip_26 = "Caderea in etape de limitare conteaza ca pierderea unei vieti.",
  tip_27 = "Comutatoarele pentru monede albastre vor aparea.",
  tip_28 = "Poti alege un alt act pentru a-i arunca pe Hunters.",
  tip_29 = "E sarbatoare! Dacă nu va plac efectele, dezactivati „Seasonal changes” din meniu.",
  tip_30 = "Puteti spiona pe Alergatorii cu /spectate.",
  tip_31 = "Foloseste /stalk pentru a deforma la un nivel in care se afla un alt alergator!",
  tip_32 = "Invatarea tehnicilor de speedrunning este o modalitate buna de a va imbunatati jocul.",
  tip_33 = "Poti trece prin Whomps lovind sau lovind cu picioarele pe masura ce cad.",
  tip_34 = "Cea mai rapida modalitate de a efectua un triplu salt este lovirea cu piciorul pentru prima saritura.",
  tip_35 = "Forma de Metal da dublu damage pentru adversari.",
  tip_36 = "Sapca Vanish te va proteja de atacurile jucatorilor doar daca tii apasat %s.",
  tip_37 = "Timpul Palariei nu se va scurge cand intri inauntru canoane.",
  tip_38 = "Nu zabovi prea mult pe Act Select!",
  tip_39 = "Aruncarile sunt rapide, iar aruncarea in alt jucator va poate ajuta sa evitati atacurile.",
  tip_40 = "Caderea va provoca daune in loc sa te omoare instantaneu.",
  tip_41 = "1-Ups va restabili 4 puncte de sanatate.",
  tip_42 = "Utilizati meniul Jucatori pentru comenzi care vizeaza un anumit jucator, cum ar fi inversarea echipelor.",
  tip_43 = "MarioHunt meniul permite pornirea jocurilor si configurarea setarilor jocului.",
  tip_44 = "Va puteti ascunde rolul de chat in Setari.",
  tip_45 = "Alergatorii care poarta sapca metalica pot fi raniti de vanatori.",
  tip_46 = "In meniu, asigurati-va ca apasati A pentru a salva setarile de modificari!",

  -- v2.8
  default = "Normal",
  gc_desc = "[MSG] - Trimite messaje prentru totii jucatori ca toti sa vada, chiar daca esti mort; host/mod only",
  menu_default_role = "Rolul Normal",
  menu_default_role_desc = "Ce echipa este reparitzata jucatorilor noi.",
  menu_game_area = "Zona Jocului",
  menu_game_area_desc = "Ce partzi sunt accesabile. Foloseste \"Normal\" pentru toate nivelele.",
  menu_nerf_vanish_desc = "Nerf-urile dispar de la capac, facandu-l vulnerabil la atacurile PVP, cu exceptia cazului in care se tine apasat un buton.",
  menu_no_player_col = "Dezactivat Ciocniri pentru Jucatori",
  menu_no_player_col_desc = "Impiedica jucatorii sa se sara sau sa se impinga reciproc. PvP-ul functioneaza in continuare!",
  menu_no_water_heal = "Fara Regen de la Apa",
  menu_old_input = "Vechiul Meniu Sageti Controale",
  menu_old_input_desc = "Schimba controalele pentru selectia de sageti exact cum erau in v2.8.",
  menu_pvp_type = "Modul PvP",
  menu_pvp_type_desc = "Schimba cum sa mearga PvP-ul(la fel ca si in setarile de servar). \"Reinnoit\" amplifica loviturile de picior prin alunecare si permite combinatii de pumni, printre altele.",
  menu_settings_player = "Preferinte",
  preset_cant_delete = "Nu poti sterge aceste presetari!",
  preset_deleted = "Sterge \"%s\" presare.",
  preset_desc = "[SALVEAZA|INCARCA|STERGE|SCHIMBA NUMELE] - Gestionati presetarile setarilor personalizate.",
  preset_not_saved = "Acest presat trebuie sa fie salvat inainte de fii renumit.",
  preset_save = "Salveaza presatul precedent",
  preset_saved = "Presatul salvat ca \"%s\". Pentru a renumi presatul, foloseste /mh preset rename [Nou Nume]",
  pvp_type_classic = "Clasic",
  pvp_type_revamped = "Reinnoit",
  vanish_custom = "Tine \\#ffff5a\\%s\\#ffffff\\ prentru a te feri de attacurile PvP!",
}