langdata["it"] = -- by Mr. L-ore
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "Italian",

  -- name in the built-in menu
  name_menu = "Italiano",

  -- global command info
  to_switch = "Scrvi \"/lang %s\" per cambiare lingua",
  switched = "Cambiata ad Italiano!", -- Replace "English" with the name of this language
  rule_command = "Scrivi /rules per mostrare nuovamente questo messaggio",
  open_menu = "Scrivi /mh o premi %s per aprire il menu",
  stalk = "Usa /stalk per teletrasportarti dai Corridori!",
  rules_desc = "- Mostra le regole di MarioHunt",
  rules_desc_egg = "- Mostra le regole di LuigiHunt",
  mh_desc = "[COMMAND,ARGS] - Esegue i comandi; scrivi \"menu\" o lascia vuoto per aprire il menu",
  lang_desc = "%s - Cambia lingua",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Imposta la difficolta difficile per te stesso",
  tc_desc = "[ON|OFF|MSG] - Manda messaggi solo alla tua squadra; attivalo per influenzare tutti i messaggi",
  stats_desc = "- Mostra/nascondi le statistiche",
  stalk_desc = "[NAME|ID] - Teletrasportati al livello specificato, o a quello del Corridore in prima posizione",
  spectate_desc = "[NAME|ID|OFF] - Muoviti in giro liberamente, guarda un giocatore specifico, o disattiva quest'opzione", -- not to be confused with spectator_desc
  target_desc = "[NAME|ID] - Imposta questo Corridore come tuo bersaglio e vedi dove si trova in tempo reale.",

  -- roles
  runner = "Corridore",
  runners = "Corridori",
  short_runner = "Corr.", -- unused
  hunters = "Cacciatori",
  hunter = "Cacciatore",
  spectator = "Spettatore",
  player = "Giocatore",
  players = "Giocatori",
  all = "Tutti",

  -- rules
  --[[
    This is laid out as follows:
    {welcome|welcome_mini}
    {runners}{shown_above|thats_you}{any_bowser|collect_bowser|mini_collect}
    {hunters}{thats_you}{all_runners|any_runners}
    {rule_lives_one|rule_lives}{time_needed|stars_needed}{become_hunter|become_runner}
    {infinite_lives}{spectate}
    {banned_glitchless|banned_general}{fun}

    I highly recommend testing this in-game
    Also:
    \\#ffffff\\ = white (default)
    \\#00ffff\\ = cyan (for Runner team name)
    \\#ff5a5a\\ = red (for Hunter team name and popups)
    \\#ffff5a\\ = yellow
    \\#5aff5a\\ = green
    \\#b45aff\\ = purple (for Extreme Mode)
  ]]
  welcome = "Benvenuto alla \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! COME GIOCARE:",
  welcome_mini = "Benvenuto alla \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! COME GIOCARE:",
  welcome_mys = "Benvenuto alla \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! COME GIOCARE:",
  welcome_egg = "Benvenuto alla \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! COME GIOCARE:",
  all_runners = "Sconfiggi tutti i \\#00ffff\\Corridori\\#ffffff\\.",
  any_runners = "Sconfiggi alcuni \\#00ffff\\Corridori\\#ffffff\\.",
  shown_above = "(mostrato sopra)",
  any_bowser = "Sconfiggi %s in \\#ffff5a\\qualsiasi\\#ffffff\\ modo necessario.",
  collect_bowser = "Ottieni \\#ffff5a\\%d stella/e\\#ffffff\\ e sconfiggi %s.",
  mini_collect = "Sii il primo ad \\#ffff5a\\ottenere la stella\\#ffffff\\.",
  collect_only = "Ottieni \\#ffff5a\\%d stella/e\\#ffffff\\.",
  thats_you = "(sei tu!)",
  banned_glitchless = "VIETATO: Il cross teaming, il BLJ, l'attraversamento dei muri, perdere tempo, camperare.",
  banned_general = "VIETATO: Il cross teaming, perdere tempo, camperare.",
  time_needed = "%d:%02d per abbandonare un'area; ottieni le stelle per diminuire",
  stars_needed = "%d stella/e necessarie per abbandonare un'area",
  become_hunter = "Diventi un \\#ff5a5a\\Cacciatore\\#ffffff\\ quando vieni sconfitto",
  become_runner = "Sconfiggi un \\#00ffff\\Corridore\\#ffffff\\ per diventarne uno",
  infinite_lives = "Vite infinite",
  spectate = "scrivi \"/spectate\" per assistere alla partita",
  mini_goal = "\\#ffff5a\\Chi riesce a ottenere più stelle in %d:%02d vince!\\#ffffff\\",
  fun = "Divertiti!",

  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ Vince!", -- team name is placed here
  can_leave = "\\#5aff5a\\Puoi uscire",
  cant_leave = "\\#ff5a5a\\Non puoi uscire",
  time_left = "Potrai uscire tra \\#ffff5a\\%d:%02d",
  stars_left = "Ti servono \\#ffff5a\\%d stella/e\\#ffffff\\ per uscire",
  in_castle = "Nel Castello",
  until_hunters = "%d secondo/i prima che i \\#ff5a5a\\Cacciatori\\#ffffff\\ inizino",
  until_runners = "%d secondo/i prima che i \\#00ffff\\Corridori\\#ffffff\\ inizino",
  lives_one = "1 vita",
  lives = "%d vite",
  stars_one = "1 stella",
  stars = "%d stelle",
  no_runners = "Nessun \\#00ffff\\Corridore!",
  camp_timer = "Continua a muoverti! \\#ff5a5a\\(%d)",
  game_over = "La partita è finita!",
  winners = "Vincitori: ",
  no_winners = "\\#ff5a5a\\Nessun vincitore!",
  death_timer = "Morte",
  mini_score = "Punteggio: %d",
  new_record = "\\#ffff5a\\NUOVO RECORD!!!",
  on = "\\#5aff5a\\ON",
  off = "\\#ff5a5a\\OFF",
  frozen = "Congelato per %d",

  -- popups
  lost_life = "%s\\#ffa0a0\\ ha perso una vita!",
  lost_all = "%s\\#ffa0a0\\ ha perso tutte le vite!",
  now_role = "%s\\#ffa0a0\\ è ora un %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ ha ottenuto una stella!",
  got_key = "%s\\#ffa0a0\\ ha ottenuto una chiave!",
  rejoin_start = "%s\\#ffa0a0\\ ha due minuti per rientrare.",
  rejoin_success = "%s\\#ffa0a0\\ è rientrato in tempo!",
  rejoin_fail = "%s\\#ffa0a0\\ non è rientrato in tempo.",
  using_ee = "Questa è solo la Modalità Estrema.",
  not_using_ee = "Questa è solo la Versione Standard.",
  killed = "%s\\#ffa0a0\\ ha ucciso %s!",
  sidelined = "%s\\#ffa0a0\\ ha dato il colpo di grazia a %s!",
  paused = "Sei stato messo in pausa.",
  unpaused = "Non sei più in pausa.",
  kill_combo_2 = "%s\\#ffa0a0\\ ha effettuato una \\#ffff5a\\doppia\\#ffa0a0\\ uccisione!",
  kill_combo_3 = "%s\\#ffa0a0\\ ha effettuato una \\#ffff5a\\tripla\\#ffa0a0\\ uccisione!",
  kill_combo_4 = "%s\\#ffa0a0\\ ha effettuato una \\#ffff5a\\quadrupla\\#ffa0a0\\ uccisione!",
  kill_combo_5 = "%s\\#ffa0a0\\ ha effettuato una \\#ffff5a\\quintupla\\#ffa0a0\\ uccisione!",
  kill_combo_large = "\\#ffa0a0\\Wow! %s\\#ffa0a0\\ ha effettuato \\#ffff5a\\%d\\#ffa0a0\\ uccisioni di fila!",
  set_hack = "Hack impostata a %s",
  incompatible_hack = "ATTENZIONE: l'Hack non è compatibile!",
  vanilla = "Usando il gioco base",
  omm_detected = "OMM Rebirth rilevato!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth è datato!\\#ffffff\\\nVersione richiesta: %s\nLa tua versione: %s",
  warp_spam = "Rallenta coi teletrasporti!",
  no_valid_star = "Impossibile trovare una stella corrispondente!",
  custom_enter = "%s\\#ffffff\\ è entrato in\n%s", -- same as coop
  ---- vanish_custom = "Tieni premuto \\#ffff5a\\%s\\#ffffff\\ per scomparire!",
  got_all_stars = "Hai abbastanza stelle!",
  unstuck = "Tentativo di sistemare lo stato",
  use_out = "Usa /mh out per teletrasportare tutti fuori dall'area",
  stars_in_area = "%d stella/e disponibili qui!",
  demon_unlock = "Modalità demone verde sbloccata!",
  hit_switch_red = "%s\\#ffa0a0\\ ha schiacciato l'\n\\#df5050\\Interruttore Rosso!", -- dark red (unique)
  hit_switch_green = "%s\\#ffa0a0\\ ha schiacciato l'\n\\#50b05a\\Interruttore Verde!", -- dark green (unique)
  hit_switch_blue = "%s\\#ffa0a0\\ ha schiacciato l'\n\\#5050e3\\Interruttore Blu!", -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ ha schiacciato l'\n\\#e3b050\\Interruttore Giallo...", -- orangeish (unique)
  connected = "%s\\#ffff5a\\ si è connesso!",                                      -- same as coop
  disconnected = "%s\\#ffa0a0\\ si è disconnesso",                                 -- same as coop

  -- command feedback
  not_mod = "Sciocco, non hai l'AUTORITÀ di eseguire questo comando!",
  no_such_player = "Non esiste un giocatore con quel nome",
  bad_id = "ID giocatore invalido!",
  command_disabled = "questo comando è disabilitato.",
  change_setting = "cambiamento delle opzioni:",
  you_are_muted = "Sei stato silenziato.",

  -- more command feedback
  bad_param = "Parametri non validi!",
  bad_command = "Comando non valido!",
  error_no_runners = "Impossibile partire con 0 Corridori!",
  set_team = "la squadra di %s è stata rinominata a '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "La partita non è ancora iniziata",
  set_lives_one = "%s ha 1 vita",
  set_lives = "%s ha %d vite",
  not_runner = "%s non è un Corridore",
  may_leave = "%s può abbandonare",
  must_have_one = "Deve esserci almeno 1 Cacciatore",
  added = "Aggiunti i Corridori: ", -- list comes afterward
  no_runners_added = "Nessun Corridore aggiunto",
  runners_are = "I Corridori sono: ",
  set_lives_total = "Vite dei corridori impostate a %d",
  wrong_mode = "Non disponibile in questa modalità",
  need_time_feedback = "I corridori possono andarsene tra %d secondo/i",
  game_time = "La partita durerà %d secondo/i",
  need_stars_feedback = "I corridori hanno bisogno di %d stella/e",
  new_category = "Ora questa è una %d star run",
  new_category_any = "Ora questa è una run any%",
  mode_normal = "In modalità Normale",
  mode_swap = "In modalità Invertita",
  mode_mini = "In modalità MiniHunt",
  mode_mys = "In modalità MysteryHunt",
  using_stars = "Usando le stelle ottenute",
  using_timer = "Usando il timer",
  can_spectate = "Adesso i Cacciatori potranno assistere alla partita",
  no_spectate = "Adesso i Cacciatori non potranno più assistere",
  all_paused = "Tutti i giocatori messi in pausa",
  all_unpaused = "Tutti i giocatori non sono più in pausa",
  player_paused = "%s è stato messo in pausa",
  player_unpaused = "%s non è più in pausa",
  hunter_metal = "Tutti i cacciatori sono metallici",
  hunter_normal = "Tutti i cacciatori sono normali",
  hunter_glow = "Tutti i cacciatori si illuminano di rosso",
  hunter_outline = "Tutti i cacciatori sono evidenziati",
  runner_sparkle = "Tutti i corridori brillano",
  runner_normal = "Tutti i corridori sono normali",
  runner_glow = "Tutti i corridori si illuminano",
  runner_outline = "Tutti i corridori sono evidenziati",
  now_weak = "Tutti i giocatori hanno metà dei fotogrammi di invincibilità",
  not_weak = "Tutti i giocatori hanno i fotogrammi di invincibilità normali",
  auto_on = "Le partite inizieranno automaticamente",
  auto_off = "Le partite non inizieranno automaticamente",
  force_spectate = "Tutti dovranno assistere",
  force_spectate_off = "Non si è più forzati ad assistere",
  force_spectate_one = "%s deve assistere",
  force_spectate_one_off = "%s non deve più assistere",
  blacklist_add = "%s è stata bloccata",
  blacklist_remove = "%s è stata sbloccata",
  blacklist_add_already = "Quella stella è già stata bloccata.",
  blacklist_remove_already = "Quella stella o area non è bloccata.",
  blacklist_remove_invalid = "Impossibile bloccare quellala stella del livello.",
  blacklist_list = "Bloccate:",
  blacklist_reset = "Lista delle stelle bloccate reimpostata!",
  blacklist_save = "Lista delle stelle bloccate salvata!",
  blacklist_load = "Lista delle stelle bloccate caricata!",
  anarchy_set_0 = "I Giocatori non possonno attaccare i loro compagni di squadra",
  anarchy_set_1 = "I Corridori possonno attaccare i loro compagni di squadra",
  anarchy_set_2 = "I Cacciatori possonno attaccare i loro compagni di squadra",
  anarchy_set_3 = "I Giocatori possonno attaccare i loro compagni di squadra",
  dmgAdd_set = "I Corridori prenderanno %d danni extra dagli attacchi avversari.",
  dmgAdd_set_ohko = "I Corridori moriranno in un solo colpo",
  voidDmg_set = "I giocatori prenderanno %d danni se cadono nel vuoto o nelle sabbie mobili.",
  voidDmg_set_ohko = "I giocatori moriranno istantaneamente se cadono nel vuoto o nelle sabbie mobili.",
  target_hunters_only = "Solo i Cacciatori possono impostare un bersaglio.",
  muted = "\\#ffff00\\%s\\#ffffff\\ è stato mutato da \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ è stato smutato da\\#ffff00\\%s\\#ffffff\\.",
  you_muted = "Hai mutato \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Hai smutato \\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ è stato mutato automaticamente.",

  -- team chat
  tc_toggle = "La chat di squadra è %s!",
  to_team = "\\#8a8a8a\\Squadra: ",
  from_team = "\\#8a8a8a\\ (squadra): ",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ Ha votato per saltare questa stella",
  vote_info = "Scrivi /skip per votare",
  vote_pass = "Il voto è stato approvato!",
  already_voted = "Hai già votato.",

  -- hard mode
  hard_notice = "Psst, prova a scrivere /hard...",
  extreme_notice = "Psst, prova a scrivere /hard ex...",
  hard_toggle = "La \\#ff5a5a\\Modalità Difficile\\#ffffff\\ è %s!",
  extreme_toggle = "La \\#b45aff\\Modalità Estrema\\#ffffff\\ è %s!",
  hard_info = "Ti interessa la \\#ff5a5a\\Modalità Difficile\\#ffffff\\?" ..
      "\n- Metà energia" ..
      "\n- Niente cura dall'acqua" ..
      "\n- \\#ff5a5a\\Una vita" ..
      "\n\\#ffffff\\Scrivi /hard ON se sei pronto per la sfida.",
  extreme_info = "Ti interessa la \\#b45aff\\Modalità Estrema\\#ffffff\\? Che sciocco." ..
      "\n- Una vita" ..
      "\n- Un'energia" ..
      "\n- \\#b45aff\\Cronometro della Morte\\#ffffff\\; Raccogli monete per aumentare" ..
      "\nSe non ti spaventa, scrivi /hard ex ON.",
  no_hard_win = "Le tue vittorie in Difficile o Estrema non saranno contate per questa partita.",
  hard_mode = "Modalità Difficile",
  extreme_mode = "Modalità Estrema",
  hard_info_short = "Metà energia, niente cura dall'acqua, e una vita.",
  extreme_info_short = "Un'energia, una vita, ed un Cronometro della Morte.",

  -- spectator
  hunters_only = "Solo i cacciatori possono assistere!",
  spectate_disabled = "Opzione assisti disattivata!",
  timer_going = "Can't spectate during timer!", -- now unused
  spectate_self = "Non puoi assistere a te stesso!",
  spectator_controls = "Controlli:" ..
      "\nDPAD-UP: nascondi la HUD"..
      "\nDPAD-DOWN: Vista giocatore/Telecamera libera" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Cambia giocatore" ..
      "\nJOYSTICK: Muoviti" ..
      "\nA: vai su" ..
      "\nZ: vai giu" ..
      "\nScrivi \"/spectate OFF\" per annullare",
  spectate_off = "Non stai più assistendo.",
  empty = "VUOTO (%d )",
  free_camera = "TELECAMERA LIBERA",
  spectate_mode = "- MODALITÀ SPETTATORE -",
  is_spectator = '* IL GIOCATORE È UNO SPETTATORE  *',

  -- stats
  disp_wins_one = "%s\\#ffffff\\ Ha vinto 1 volta come \\#00ffff\\Corridore\\#ffffff\\!",
  disp_wins = "%s\\#ffffff\\ ha vinto %d volte come \\#00ffff\\Corridore\\#ffffff\\!",
  disp_kills_one = "%s\\#ffffff\\ has killed 1 player!", -- unused
  disp_kills = "%s\\#ffffff\\ ha ucciso %d giocatori!",
  disp_wins_hard_one =
  "%s\\#ffffff\\ Ha vinto 1 volta come \\#ffff5a\\Corridore\\#ffffff\\ in \\#ff5a5a\\Modalità Difficile!\\#ffffff\\",
  disp_wins_hard =
  "%s\\#ffffff\\ ha vinto %d volte come \\#ffff5a\\Corridore\\#ffffff\\ in \\#ff5a5a\\Modalità Difficile!\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ Ha vinto 1 volta come \\#b45aff\\Corridore\\#ffffff\\ in \\#b45aff\\Modalità Estrema!\\#ffffff\\",
  disp_wins_ex =
  "%s\\#ffffff\\ ha vinto %d volte come \\#b45aff\\Corridore\\#ffffff\\ in \\#b45aff\\Modalità Estrema!\\#ffffff\\",
  -- for stats table
  stat_wins_standard = "Vittorie",
  stat_wins = "Vittorie (Minihunt/pre v2.3)",
  stat_wins_mys = "Vittorie (MysteryHunt)",
  stat_kills = "Uccisioni",
  stat_combo = "Serie di uccisioni maggiore",
  stat_wins_hard_standard = "Vittorie (Hard Mode)",
  stat_wins_hard = "Vittorie (Modalità Difficile, MiniHunt/pre v2.3)",
  stat_wins_hard_mys = "Vittorie (Modalità Difficile, MysteryHunt)",
  stat_mini_stars = "Stelle massime in una pasrtita di MiniHunt",
  stat_placement = "Piazzamento 64 Tour",
  stat_wins_ex_standard = "Vittorie (Modalità Estrema)",
  stat_wins_ex = "Vittorie (Modalità Estrema, MiniHunt/pre v2.3)",
  stat_wins_ex_mys = "Vittorie (Modalità Estrema, MysteryHunt)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1o Posto]",
  place_2 = "\\#c5d8de\\[64T: 2o Posto]",
  place_3 = "\\#b38752\\[64T: 3o Posto]",
  place = "\\#e7a1ff\\[64T: %do Posto]", -- thankfully we don't go up to 21
  place_score_1 = "%do",
  place_score_2 = "%do",
  place_score_3 = "%do",
  place_score = "%do",

  -- chat roles
  role_lead = "\\#9a96ff\\[Svil. Principale di MH]",
  role_dev = "\\#96ecff\\[Svil. di MH]",
  role_cont = "\\#ff9696\\[Contributore a MH]",
  role_trans = "\\#ffd996\\[Traduttore di MH]",

  -- command descriptions
  page = "\\#ffff5a\\Pagina %d/%d", -- page for mariohunt command
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Inizia la partita; aggiungi \"continue\" per non partire dall'inizio; aggungi \"alt\" per un file di salvataggio alternativo; aggiungi \"main\" per il file di salvataggio principale; aggiungi \"reset\" per ripristinare il file",
  add_desc = "[INT] - Aggiungi il numero di corridori casuali specificato",
  random_desc = "[INT] - Sceglie casualmente il numero di corridori specificato",
  random_desc_hunt = "[INT] - Sceglie casualmente il numero di cacciatori specificato",
  lives_desc = "[INT] - Imposta il numero di vite dei Corridori, da 0 a 99 (n.b.: 0 vite equivale ad 1 vita)",
  time_desc =
  "[NUM] - Imposta il tempo entro cui i Corridori devono scappare, in secondi, o per la durata della partita in MiniHunt.",
  stars_desc =
  "[INT] - Imposta il numero di stelle che il Corridore deve aver per scappare, da 1 a 7 (solo per la modalità stelle)",
  category_desc = "[INT] - Imposta il numero di stelle che i Corridori devono avere per affrontare Bowser. Imposta a -1 per la any%.",
  flip_desc = "[NAME|ID] - Cambia la squadra di un giocatore",
  setlife_desc = "[NAME|ID|INT,INT] - Imposta il numero di vite per un corridore in particolare",
  leave_desc = "[NAME|ID] - Permetti ad un giocatore specifico di abbandonare il livello in caso fosse un corridore",
  mode_desc = "[NORMAL|SWAP|MINI] - Cambia modalità; Swap converte i corridori quando muoiono",
  starmode_desc = "[ON|OFF] - Attiva o disattiva l'utilizzo delle stelle piuttosto che del tempo",
  spectator_desc = "[ON|OFF] - Attiva o disattiva l'abilità dei cacciatori di assistere",
  pause_desc =
  "[NAME|ID|ALL] - Attiva o disattiva lo stato di pasua per un giocatore specificato, o tutti se non specificato",
  hunter_app_desc = "Cambia l'Aspetto dei Cacciatori.",
  runner_app_desc = "Cambia l'Aspetto dei Corridori.",
  hack_desc = "[STRING] - Imposta l'attuale rom hack",
  weak_desc = "[ON|OFF] - Dimezza i fotogrammi di invincibilità per tutti",
  auto_desc = "[ON|OFF|NUM] - Inizia automaticamente",
  forcespectate_desc = "[NAME|ID|ALL] - Attiva o disattica la modalità spettatore forzata per uno o tutti i giocatori",
  desync_desc = "- Prova a sistemare gli errori di desinc.",
  stop_desc = "- Ferma il gioco",
  default_desc = "- Ripristina le impostazioni",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Blocca stelle in MiniHunt",
  stalking_desc = "[ON|OFF] - Permetti il teletrasporto al livello di un Corridore con /stalk",
  mute_desc = "[NAME|ID] - Muta un giocatore, impedendogli di scrivere",
  unmute_desc = "[NAME|ID] - Smuta un giocatore, permettendogli di scrivere",
  out_desc = "[LEVEL|COURSE] - Butta tutti fuori da un'area",

  -- Blocky's menu
  main_menu = "Menu Principale",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  --menu_settings_player = "Impostazioni",
  menu_rules = "Regole",
  menu_list_settings = "Lista delle impostazioni",
  menu_list_settings_desc = "Mostra la lista delle impostazioni per la stanza.",
  menu_lang = "Lingua",
  menu_misc = "Altro",
  menu_stats = "Statistiche",
  menu_back = "Indietro",
  menu_exit = "Esci",

  menu_run_random = "Corridori Casuali",
  menu_run_add = "Aggiungi Corridori",
  menu_hunt_random = "Cacciatori Casuali",
  menu_run_lives = "Vite dei Corridori",
  menu_settings = "Impostazioni della partita",

  menu_start = "Inizia",
  menu_stop = "Ferma",
  menu_save_main = "Principale",
  menu_save_alt = "File Alternativo",
  menu_save_reset = "Ripristina File Alternativo",
  menu_save_continue = "Continua (non teletraspora indietro)",
  menu_random = "Casuale",
  menu_campaign = "Storia",
  menu_coop = "Cooperativa", -- unused

  menu_gamemode = "Modalità",
  menu_hunter_app = "Aspetto del Cacciatore",
  menu_runner_app = "Aspetto del Corridore",
  menu_weak = "Modalità Debole",
  menu_allow_spectate = "Permetti Spettatori",
  menu_star_mode = "Modalità Stella",
  menu_category = "Categoria",
  menu_time = "Tempo",
  menu_stars = "Stelle",
  menu_auto = "Auto Game",
  menu_blacklist = "MiniHunt Bloccate",
  menu_default = "Ripristina",
  menu_anarchy = "Fuoco Amico",
  menu_anarchy_desc = "Permette ai giocatori di attaccare i compagni di squadra.",
  menu_dmgAdd = "Danno ai Corridori Aumentato",        -- DMG is "damage"
  menu_dmgAdd_desc = "Agguinge il quantitativo al danno inflitto ai Corridori",
  menu_nerf_vanish = "Depotenzia Cappello Invisibile", -- Nerf, as in to reduce power for balancing
  -- menu_nerf_vanish_desc = "Depotenzia il cappello invisibile rendendolo disattivabile e diminuendo la durata.",
  menu_first_timer = "Cronometro della Morte per il 1o",
  menu_first_timer_desc = "Da' al giocatore in prima posizione nella MiniHunt un cronometro della morte.",
  menu_defeat_bowser = "Sconfiggi %s",
  menu_allow_stalk = "Permetti lo 'Stalking'",
  menu_countdown = "Conto alla rovescia",
  menu_countdown_desc = "Tempo di attesa per i Cacciatori.",
  menu_voidDmg = "danno del Vuoto",
  menu_voidDmg_desc = "danno inflitto ai giocatori che cadono nel vuoto o nelle sabbie mobili.",
  menu_double_health = "Energia Doppia",
  menu_double_health_desc = "I giocatori hanno 16 di energia piuttosto che 8.",

  menu_flip = "Cambia Squadra",
  menu_spectate = "Assisti",
  menu_stalk = "Teletrasporto all'Area",
  menu_stalk_desc = "Teletraspotati all'area di un giocatore.",
  menu_pause = "Pausa",
  menu_forcespectate = "Forza Modalità Spettatore",
  menu_allowleave = "Permetti di Uscire",
  menu_setlife = "Imposta Vite",
  menu_players_all = "Tutti i Giocatori",
  menu_target = "Imposta come Bersaglio",
  menu_mute = "Muta",

  menu_timer = "Cronometro Speedrun",
  menu_timer_desc = "[ON|OFF] - Mostra un cronometro speedrun in basso nelle Modalità Standard.",
  menu_tc = "Chat di Squadra",
  menu_tc_desc = "Chat con solo la tua squadra.",
  menu_demon = "Demone Verde", -- referring to the 1-Up
  menu_demon_desc = "Una 1-Up inseguirà i Corridori.",
  menu_unknown = "???",
  menu_secret = "È un segreto. Come lo sblocchi?",
  menu_hide_roles = "Nascondi il Mio Ruolo",
  menu_hide_roles_desc = "Impedisci che il to ruolo vega mostrato in chat.",
  menu_hide_hud = "Nascondi HUD",
  hidehud_desc = "- nascondi gli elementi della HUD.",
  menu_fast = "Azioni Più Veloci",
  menu_fast_desc = "Ti rialzerai, lancerai, ed aprirai le porte più velocemente.",
  menu_popup_sound = "Suoni dei Popup",
  menu_season = "Cambiamenti Stagionali",
  menu_season_desc = "Piccoli dettagli che dipendono dalla data.",

  menu_free_cam_desc = "Attiva la telecamera libera in modalità spettatore.",
  menu_spectate_run = "Assisti ad un Corridore",
  menu_spectate_run_desc = "Assisti automaticamente al corridore in prima posizione.",
  menu_exit_spectate = "Esci dalla Modalità Spettatore",
  menu_exit_spectate_desc = "Abbastanza esplicito.",
  menu_stalk_run = "Teletrasporto al Livello del corridore",
  menu_stalk_run_desc = "Teletrasportati al livello del corridore in prima posizione.",
  menu_skip = "Salta",
  menu_skip_desc = "- Vota per saltare una stella in MiniHunt.",

  menu_spectate_desc = "Assisti a questo giocatore.",

  menu_blacklist_list = "Lista Stelle Bloccate",
  menu_blacklist_list_desc = "Lista delle stelle bloccate in MiniHunt per questo server.",
  menu_blacklist_save = "Salva Lista",
  menu_blacklist_save_desc = "Salva la tua lista delle stelle bloccate.",
  menu_blacklist_load = "Carica Lista",
  menu_blacklist_load_desc = "Carica la tua lista delle stelle bloccate.",
  menu_blacklist_reset = "Ripristina Lista",
  menu_blacklist_reset_desc = "Ripristina la lista delle stelle bloccate.",
  menu_toggle_all = "Attiva tutte",

  -- updater
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ è aggiornata!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ è aggiornata!",
  has_update = "Aggiornamento disponibile per \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\!",
  has_update_egg = "Aggiornamento disponibile per \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\!",

  -- v2.6 stuff I don't feel like sorting
  leave_error = "%s\\#ffa0a0\\ è uscito a causa di un errore.",
  hunter_color = "Tutti i cacciatori useranno la palette Borgogna",
  runner_color = "Tutti i corridori useranno la palette Azzurra",
  stat_playtime = "Tempo di gioco totale (ore)",
  stat_parkour_time = "Record nel Parkour",
  stat_parkour_time_omm = "Record nel Parkour (OMM)",
  stat_parkour_time_other = "Record nel Parkour (Moveset)",
  menu_free_roam = "Esplorazione Libera",
  menu_free_roam_desc = "Rimuove la necessità di stelle o chiavi per la maggior parte delle porte.",
  menu_radar = "Radar",
  menu_radar_desc = "Mostra la posizione dei corridori e degli oggetti importanti.",
  menu_minimap = "Minimappa",
  menu_minimap_desc = "Mostra una mappa di tutto il livello.",
  menu_romhack_cam = "Telecamera Romhack", -- (cam is short for camera)
  menu_romhack_cam_desc = "Abilita permanentemente la telecamera della romhack.", -- (cam is short for camera)
  menu_star_heal = "Stelle Curative",

  -- v2.6.1
  menu_star_setting = "A stella collezzionata", -- from base
  star_leave = "Lascia",
  star_stay = "Rimani",
  star_nonstop = "Non-Stop",

  -- v2.7
  added_count = "Aggiunti %d corridori",
  added_count_one = "Aggiunto 1 corridore",
  become_spectator = "Diventa uno \\#a9a9a9\\Spettatore\\#ffffff\\ quando sconfitto",
  dead = "Morto",
  dead_become = "I \\#00ffff\\Corridori\\#ffffff\\ morti si lasciano dietro un cadavere.",
  dead_become_infection = "I giocatori morti che non diventano \\#ff5a5a\\Cacciatori\\#ffffff\\ si lasciano dietro un cadavere.",
  dead_become_noconfirm = "I giocatori morti si lasciano dietro un cadavere.",
  disp_asn_bronze = "%s\\#ffffff\\ ha ottenuto il \\#b38752\\bronzo\\#ffffff\\ nel Torneo ASN!",
  disp_asn_quarter = "%s\\#ffffff\\ ha raggiunto i \\#70ff94\\quarti di finale\\#ffffff\\ nel Torneo ASN!",
  disp_asn_silver = "%s\\#ffffff\\ ha ottenuto l'\\#c5d8de\\argento\\#ffffff\\ nel Torneo ASN!",
  disp_asn_win = "%s \\#e3bc2d\\ha vinto\\#ffffff\\ il Torneo ASN!",
  far = "\\#8a8a8a\\(lontano)",
  global_talk_end = "\\#ffa0a0\\La chat globale è chiusa.",
  global_talk_start = "\\#ffa0a0\\La chat globale è aperta per %d secondo/i.",
  guard_cooldown = "Puoi proteggere qualcuno in %d",
  guard_info = "Premi %s per  proteggere %s",
  guard_info_rules = "I giocatori possono proteggere i loro compagni di squadra con %s.",
  guard_save = "\\#ffff00\\Un fantasma ti ha salvato dalla morte!",
  guard_timer = "%s\\#ffff00\\ è protetto (%d)",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Cacciatori\\#ffa0a0\\ rimanenti.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Cacciatore\\#ffa0a0\\ rimanente.",
  hunters_set_count = "Rimangono %d hunters",
  hunters_set_count_one = "Rimane 1 cacciatore",
  hunters_were = "I Cacciatori erano: ",
  keep_secret = "Non farti beccare!",
  menu_binds = "Cambia Comandi",
  menu_binds_desc = "Cambia i comandi usati per le varie azioni.",
  menu_confirm_hunter = "Conferma Morti dei Cacciatori",
  menu_confirm_hunter_desc = "Mostra un messaggio quando un Cacciatore muore. Se disattivato, anche i Cacciarori si lasceranno dietro un cadavere.",
  menu_global_chat = "Tempo Chat Globale",
  menu_global_chat_desc = "Tempo a disposizione per parlare nella chat globale al ritrovamento di un corpo.",
  menu_grace_period = "Durata Immunità",
  menu_grace_period_desc = "Tempo prima che i giocatri possano essere uccisi.",
  menu_guard_button = "Protezione",
  menu_guard_button_desc = "Pulsante usato per proteggere i giocatori in modalità spettatore nella MysteryHunt.",
  menu_hunters_win_early = "Vittoria Anticipata dei Cacciatori",
  menu_hunters_win_early_desc = "I Cacciatori vincono se sono tanti quanti o di più dei Corridori, come Among Us.",
  menu_invinc_particle = "Particelle di Invincibilità",
  menu_invinc_particle_desc = "Rimpiazza l'effetto \"lampeggiante\" di quando prendi danno con delle particelle luccicanti.",
  menu_know_team = "I Cacciatori Vedono i Compagni",
  menu_know_team_desc = "I Cacciatori conoscono i loro compagni di squadra. Se disattivato, i Cacciatori possono uccidersi a vicenda.",
  menu_menu_button = "Apri Menù",
  menu_menu_button_desc = "Pulsante(i) usati per aprire il menù di MarioHunt.",
  menu_overlay = "Overlay Progressivo dell'Area",
  menu_overlay_desc = "Mostra le stelle, chiavi, e interruttori dei cappelli ottenuti vicino al quadro o teletrasporto dell'area.",
  menu_presets = "Preset",
  menu_report_button = "Segnala/Ripara",
  menu_report_button_desc = "Pulsante usato per segnalare i cadaveri e riparare i sabotaggi nella MysteryHunt.",
  menu_sabo = "Sabota",
  menu_sabo_button = "Apri Menù Sabotaggi",
  menu_sabo_button_desc = "Pulsante(i) usati per aprire il menù dei sabotaggi nella MysteryHunt.",
  menu_show_on_map = "Mostra nella Mappa",
  menu_show_on_map_desc = "Scegli quali squadre saranno mostrate nella minimappa (Gli avversari avranno anche il loro radar)",
  menu_shuffle = "Mischia Squadre",
  menu_shuffle_desc = "Mischia le squadre di tutti i giocatori in vita nel tempo selezionato",
  menu_spectate_on_death = "I Corridori Diventano Spettatori alla morte",
  menu_stalk_timer = "Cooldown da Teletrasporto",
  menu_stalk_timer_desc = "Il tempo durante il quale il giocatore che ha usato /stalk sarà immobilizzato.",
  menu_star_stay_old = "Resta se già Presa",
  menu_star_stay_old_desc = "Prendere una stella già ottenuta non ti farà uscire dal livello.",
  menu_star_timer = "Tempo dell'Ultima Stella",
  menu_star_timer_desc = "Mostra quando l'ultima stella ottenuta è stata presa in basso nello schermo.",
  menu_vanish_button = "Invisibilità",
  menu_vanish_button_desc = "Pulsante che tenuto premuto attiva il Cappello Invisibile quando \"Depotenzia Cappello Invisibile\" è attivo.",
  mystery_altgoal = "OPPURE: Scopri i \\#ff5a5a\\Cacciatori\\#ffffff\\ e sconfiggili.",
  mysteryhunt_disabled = "\\#ffa0a0\\Una delle tue mod non è compatibile con MysteryHunt!",
  mysteryhunt_innocent = "\\#ffa0a0\\Hai ucciso un giocatore innocente!",
  mysteryhunt_spectate = "\\#ffa0a0\\Sarai uno spettatore per questa partita.",
  nearby = "\\#8a8a8a\\(vicino)",
  no_players_here = "Non ci sono altri giocatori qui!",
  no_runners_here = "Non ci sono \\#00ffff\\Corridori\\#ffffff\\ qui!",
  opponents = "Avversari",
  other_hunters = "Gli altri Cacciatori sono: ",
  place_asn = "\\#e7a1ff\\[Partecipante ASN]",
  place_asn_1 = "\\#e3bc2d\\[Vincitore ASN]",
  place_asn_2 = "\\#c5d8de\\[Argento ASN]",
  place_asn_3 = "\\#b38752\\[Bronzo ASN]",
  place_asn_4 = "\\#70ff94\\[Quartifinalista ASN]",
  players_remain = "\\#ffa0a0\\%d giocatori rimanenti.",
  players_remain_one = "\\#ffa0a0\\1 giocatore rimanente.",
  preset_asn = "Torneo ASN",
  preset_asn_desc = "Stesse impostazioni usate nel Torneo ASN (con 1 vita extra).",
  preset_classic = "Classico",
  preset_classic_desc = "Cambia le impostaszioni a quelle di una versione più vecchia di MarioHunt.",
  preset_infection = "Infezione",
  preset_infection_desc = "1 Cacciatore che ti sconfigge con 1 colpo! Riusciranno i Corridori a sopravvivere?",
  preset_quick = "Partita Veloce",
  preset_quick_desc = "30 Stelle, Esplorazione libera, Senza Bowser.",
  preset_solo = "Solitaria",
  preset_solo_desc = "Sei da solo! 3 vite ed energia doppia.",
  preset_star_rush = "Star Rush",
  preset_star_rush_desc = "Minihunt, ma sono tutti corridori!",
  preset_tag = "Acchiapparella",
  preset_tag_desc = "Colpisci un corridore per diventarne uno!",
  press_report = "%s - Segnala", -- is this correct? (%s is a button name, such as "L")
  press_fix = "%s - Ripara", -- is this correct? (%s is a button name, such as "L")
  report_body = "%s\\#ffa0a0\\ ha trovato il corpo di %s's\\#ffa0a0\\ in \\#ffff5a\\",
  report_info_rules = "Premi %s per segnalarlo e discutere.",
  role_dead = "\\#ff2020\\[MORTO]",
  runners_can_kill = "I \\#00ffff\\Corridori\\#ffffff\\ possono sconfiggere i giocatori che sospettano essere \\#ff5a5a\\Cacciatori\\#ffffff\\.\nSe uccidono un innocente, allora muoiono anche loro.",
  runners_remain = "%d \\#00ffff\\Corridori\\#ffffff\\ rimanenti.",
  runners_remain_one = "1 \\#00ffff\\Corridore\\#ffffff\\ rimanente.",
  sabo_activate_timer = "Attivazione in %d",
  sabo_active = "\\#ffff00\\SABOTAGGIO ATTIVO!",
  sabo_bomb = "\\#ff4040\\Mega Bomba",
  sabo_bomb_desc = "Uccide tutti i giocatori se non disattivata!",
  sabo_bomb_timer = "\\#ff4040\\Tutti moriranno tra %d:%02d",
  sabo_cooldown = "Potrai sabotare tra %d:%02d",
  sabo_dark = "\\#5050ff\\Oscurità",
  sabo_dark_desc = "il mondo si ricopre di oscurità!",
  sabo_gas = "\\#ffff32\\Gas Tossico",
  sabo_gas_desc = "Fa apparire del gas tossico!",
  sabo_info = "Premi %s per sabotare",
  sabo_info_rules = "I \\#ff5a5a\\Cacciatori\\#ffffff\\ possono a loro volta causare caos con i sabotaggi.\nPer disabilitare i sabotaggi, vai al livello desiderato e premi %s sul sabotaggio.",
  scroll_up = "Scorri in alto per vedere altro...",
  shuffle_timer = "Le squadre verranno mischiate tra %d",
  stat_crown = "Corona ASN",
  stat_placement_asn = "Posizione nel Torneo ASN",
  tc_only_hunter = "Solo i cacciatori in vita possono usare la chat dei team.",
  unless_defeated = "a meno che non sia sconfitto da un altro giocatore",
  unsaved_changes = "\\#ff5a5a\\Hai dei cambiamenti non salvati! Premi di nuovo se sei sicuro.",
  until_grace = "%d Secondo(i) prima che l'immunità si esaurisca",

  -- Tips (TODO: check if these render correctly)
  tip = "Suggerimento: ",
  tip_1 = "Premi %s, o scrivi /mh, per aprire il menù. Lì potrai configurare le impostazioni!",
  tip_2 = "Gli schianti a terra infliggono 3 danni agli altri giocatori.",
  tip_3 = "Un calcio infligge 2 danni e spazza via gli altri giocatori!",
  tip_4 = "Per comandi come /spectate e /target, puoi scrivere parzialmente i nomi e funzioneranno comunque (es: scrivere \"Emily\" frà riferimento ad EmilyEmmi)",
  tip_5 = "Puoi cambiare le impostazioni durante la partita dal menù.",
  tip_6 = "Se qualcosa va storto, scrivi /mh pause per fermare tutti i giocatori. Scrivilo di nuovo per riprendere normalmente.",
  tip_7 = "Qualcuno sta spammando o insultando? Usa /mh mute per mutarli!",
  tip_8 = "Puoi mettere il gioco in pausa poco prima di prendere una stella o una chiave e selezionare Exit Course per saltare l'animazione.",
  tip_9 = "Puoi prendere di mira un Corridore con /target. Ciò mostrerà la sua posizione in cima allo schermo.",
  tip_11 = "Non serve riavviare il server! Seleziona \"Ripristina File Alternativo\" in \"Start\" per ripristinare tutti i progressi.",
  tip_10 = "Puoi configurare le impostazioni personali nel menù (%s).",
  tip_12 = "Puoi ottenere il ruolo di Corridore sconfiggendo un altro Corridore.",
  tip_13 = "Come in Mario 64 Vanilla, 0 vite contano ancora come una vita.",
  tip_14 = "I glitch più importanti, come il LBLJ, sono inutili al di fuori dall'Any%.",
  tip_15 = "I cartelli in gioco potrebbero darti consigli più utili!",
  tip_16 = "Si può entrare a Dire Dire Docks con una stella in meno dell'effettiva categoria.",
  tip_17 = "Imposta Cappy a \"Danno\" per usarlo come arma a distanza. Infligge 1 danno.",
  tip_18 = "Cappy puù prendere gli oggetti, come monete e segreti.",
  tip_19 = "Usa il D-Pad per lanciare Cappy in direzioni differenti.",
  tip_20 = "Guarda il video di Key's Artwork su YouTube per imparare le strategie di OMM!",
  tip_21 = "Se gli oggetti in un livello iniziano a sparire o i teletraspori smettono di funzionare, usa /mh out in quel livello per ripristinarlo forzatamente.",
  tip_22 = "Usa /mh desync se pensi che ci sia un errore di desincronizzazione.",
  tip_23 = "Uccidere un altro giocatore ripristinerà la tua energia.",
  tip_24 = "Puoi vedere le chiavi ottenute, i cappelli attivati, e i livelli segeti completati nel menù di pausa al castello.",
  tip_25 = "I Corridori si danneggano a vicenda in questa modalità!",
  tip_26 = "Cadere nei livelli dei cappelli speciali conterà come perdere una vita.",
  tip_27 = "Gli interruttori delle monete blu riappariranno.",
  tip_28 = "puoi selezionare un'altra stella per confondere i Cacciatori.",
  tip_29 = "Buone feste! Se non ti piacciono gli effetti, disattiva \"Cambiamenti Stagionali\" nel menù.",
  tip_30 = "Puoi spiare i Corridori con /spectate.",
  tip_31 = "Usa /stalk per teletrasportarti al livello di un Corridore!",
  tip_32 = "Imparare le tecniche di speedrun ti aiuterà a migliorare.",
  tip_33 = "Puoi passare attraverso i Womp eseguendo uno schianto a terra o calciando prima che riescano a schiaciarti.",
  tip_34 = "Il modo più veloce di eseguire un triplo salto è calciàre al posto del primo salto.",
  tip_35 = "La forma Metallo infligge danni doppi agli avversari.",
  tip_36 = "Il cappello invisibile ti protegge dagli attacchi dei giocatori quando tieni premuto %s.",
  tip_37 = "La durata dei cappelli non diminuisce dentro i cannoni.",
  tip_38 = "Non rimanere nella selezione della stella per troppo tempo!",
  tip_39 = "I tuffi sono veloci, e tuffarti su un altro giocatore può aiutarti a schivare gli attachi.",
  tip_40 = "Cadere infliggerà danno piuttosto che ucciderti istantaneamente.",
  tip_41 = "Le vite ripristineranno 4 punti energia.",
  tip_42 = "Usa il menù Giocatori per i comandi che influenzano un giocatore specifico, come cambiare squadra.",
  tip_43 = "Il menù di MarioHunt ti permette di iniziare e configurare le impostazioni della partita.",
  tip_44 = "Puoi nascondere il tuo ruolo chat nelle impostazioni.",
  tip_45 = "I Corridori che indossano il cappello di metallo possono comunque essere danneggiati dai Cacciatori.",
  tip_46 = "Nel menù, assicurati di premere A per salvare le modifiche alle impostazioni",

  -- v2.8
  default = "Base",
  gc_desc = "[MSG] - Manda un messaggio che tutti possono vedere, anche se sei morto; esclusivo per host e moderatori",
  menu_default_role = "Ruolo Predefinito",
  menu_default_role_desc = "Determina la squadra assegnata ai nuovi giocatori.",
  menu_game_area = "Area di Gioco",
  menu_game_area_desc = "Quali aree del gioco sono accessibili. Usa \"Base\" per poter accedere a tutti i livelli.",
  menu_nerf_vanish_desc = "Depotenzia il cappello invisibile rendendolo vulnerabile agli attacchi dei giocatori, a meno che non si tenga premuto un pulsante.",
  menu_no_player_col = "Disabilita Collisioni fra Giocatori",
  menu_no_player_col_desc = "Impedisce ai giocatori di rimbalzare tra loro e spingersi a vicenda. Il PVP funziona comunque!",
  menu_no_water_heal = "Niente Cura Dall'acqua",
  menu_old_input = "Vecchi Controlli a Frecce",
  menu_old_input_desc = "Cambia i controlli del menù a quelli usati prima della versione 2.8.",
  menu_pvp_type = "Modalità PvP ",
  menu_pvp_type_desc = "Cambia il funzionamento del PvP (come le impostazioni del server). \"Migliorato\" Potenzia i calci in scivolata, permette di effettuare combo coi pugni, ed altro ancora.",
  menu_settings_player = "Preferenze",
  preset_cant_delete = "Impossibile eliminare questo preset!",
  preset_deleted = "Eliminato il preset \"%s\".",
  preset_desc = "[SAVE|LOAD|DELETE|RENAME] - Gestisci i tuoi preset delle impostazioni.",
  preset_not_saved = "Questo preset deve essere salvato prima che tu possa rinominarlo.",
  preset_save = "Salva il Preset Attuale",
  preset_saved = "Il preset è stato salvato come \"%s\". Per rinominarlo, usa /mh preset rename [nuovo nome]",
  pvp_type_classic = "Classico",
  pvp_type_revamped = "Migliorato",
  vanish_custom = "Tieni premuto \\#ffff5a\\%s\\#ffffff\\ per evitare gli attacchi dei giocatori!",
}