langdata["pt-br"] = -- Made by PietroM (PietroM#4782)
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "Portuguese",

  -- name in the built-in menu
  name_menu = "Português",

  -- global command info
  to_switch = "Type \"/lang %s\" para trocar a linguagem.",
  switched = "Trocou para Português do Brasil!",
  rule_command = "Use o comando /rules para mostrar as regras novamente.",

  -- roles
  runner = "Corredor",
  runners = "Corredores",
  short_runner = "Corre",
  hunters = "Caçadores",
  hunter = "Caçador",
  spectator = "Observador",
  player = "Jogador",
  players = "Jogadores",

  -- rules
  --[[
    This is laid out as follows:
    {welcome}
    {runners}{shown_above|thats_you}{any_bowser|collect_bowser}
    {hunters}{thats_you}{all_runners|any_runners}
    {rule_lives_one|rule_lives}{time_needed|stars_needed}{become_hunter|become_runner}
    {infinite_lives}{spectate}
    {banned_glitchless|banned_general}{fun}
    I highly recommend testing this in-game
    Also:
    \\#ffffff\\ = white (default)
    \\#00ffff\\ = cyan (for Runner team name)
    \\#ff5a5a\\ = red (for Hunter team name and popups)
    \\#ffff5a\\ = yellow
    \\#5aff5a\\ = green
    \\#b45aff\\ = purple (for Extreme Mode)
  ]]
  welcome = "Bem vindo à \\#ff5a5a\\Caça-\\#00ffff\\Mario\\#ffffff\\! INSTRUÇÕES:",
  welcome_mini = "Bem vindo à \\#ffff5a\\Mini-\\#ff5a5a\\Caça\\#ffffff\\! INSTRUÇÕES:",
  welcome_mys = "Bem vindo à \\#ff5a5a\\Caça-\\#b45aff\\Mistério\\#ffffff\\! INSTRUÇÕES:",
  welcome_egg = "Bem vindo à \\#ff5a5a\\Caça-\\#5aff5a\\Luigi\\#ffffff\\! INSTRUÇÕES:",
  all_runners = "Derrote todos os \\#00ffff\\Corredores\\#ffffff\\.",
  any_runners = "Derrote quaisquer \\#00ffff\\Corredores\\#ffffff\\.",
  shown_above = "(demonstrado acima)",
  any_bowser = "Derrote %s de \\#ffff5a\\qualquer\\#ffffff\\ maneira.",
  collect_bowser = "Colete \\#ffff5a\\%d estrela(s)\\#ffffff\\ e derrote %s.",
  mini_collect = "Seja o primeiro a \\#ffff5a\\coletar a estrela\\#ffffff\\.",
  collect_only = "Colete \\#ffff5a\\%d estrela(s)\\#ffffff\\.",
  thats_you = "(este é você!)",
  banned_glitchless = "NÃO DEVE: Ajudar a equipe oposta, BLJs, cruzar paredes com glitches, enrolar, guardar caixão.",
  banned_general = "NÃO DEVE: Ajudar a equipe oposta, enrolar, guardar caixão.",
  time_needed = "%d:%02d para sair de qualquer fase; coletar estrelas para diminuir o cronômetro",
  stars_needed = "%d estrela(s) para sair de qualquer fase",
  become_hunter = "você virará um dos \\#ff5a5a\\Caçadores\\#ffffff\\ quando derrotado",
  become_runner = "derrote um \\#00ffff\\Corredor\\#ffffff\\ para virar um",
  infinite_lives = "Vidas infinitas",
  spectate = "use o comando \"/spectate\" para observar a partida",
  mini_goal = "\\#ffff5a\\Quem coletar mais estrelas em %d:%02d ganha!\\#ffffff\\",
  fun = "Se divirta!",

  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ Ganham!", -- team name is placed here
  can_leave = "\\#5aff5a\\Pode sair do nível.",
  cant_leave = "\\#ff5a5a\\Não pode sair do nível.",
  time_left = "Poderá sair em \\#ffff5a\\%d:%02d",
  stars_left = "Precisa-se de \\#ffff5a\\%d estrela(s)\\#ffffff\\ para sair.",
  in_castle = "Dentro do Castelo",
  until_hunters = "%d segundo(s) até que os \\#ff5a5a\\Caçadores\\#ffffff\\ comecem.",
  until_runners = "%d segundo(s) até que os \\#00ffff\\Corredores\\#ffffff\\ comecem.",
  lives_one = "1 vida",
  lives = "%d vidas",
  stars_one = "1 estrela",
  stars = "%d estrelas",
  no_runners = "Não há \\#00ffff\\Corredores!",
  camp_timer = "Continue se mexendo! \\#ff5a5a\\(%d)",
  game_over = "A partida acabou!",
  winners = "Vencedores: ",
  no_winners = "\\#ff5a5a\\Não há vencedores!",
  on = "\\#5aff5a\\LIGADO",
  off = "\\#ff5a5a\\DESLIGADO",
  frozen = "Congelado por %d",

  -- popups
  lost_life = "%s\\#ffa0a0\\ perdeu uma vida!",
  lost_all = "%s\\#ffa0a0\\ perdeu todas as suas vidas!",
  now_role = "%s\\#ffa0a0\\ agora é um %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ conseguiu uma estrela!",
  got_key = "%s\\#ffa0a0\\ pegou uma das chaves!",
  rejoin_start = "%s\\#ffa0a0\\ tem dois minutos para entrar novamente na partida.",
  rejoin_success = "%s\\#ffa0a0\\ entrou à tempo!",
  rejoin_fail = "%s\\#ffa0a0\\ Não reconectou a tempo.",
  using_ee = "Este servidor está usando a versão Extrema.",
  not_using_ee = "Este servidor usa a versão normal.",
  killed = "%s\\#ffa0a0\\ derrotou %s!",
  sidelined = "%s\\#ffa0a0\\ acabou de vez com %s!",
  paused = "Você está sob efeito de pausa.",
  unpaused = "Você não está mais sob o efeito de pausa.",
  kill_combo_2 = "%s\\#ffa0a0\\ já derrotou \\#ffff5a\\dois\\#ffa0a0\\ jogadores!",
  kill_combo_3 = "%s\\#ffa0a0\\ já derrotou \\#ffff5a\\três\\#ffa0a0\\ jogadores!",
  kill_combo_4 = "%s\\#ffa0a0\\ já derrotou \\#ffff5a\\quatro \\#ffa0a0\\ jogadores!",
  kill_combo_5 = "%s\\#ffa0a0\\ já derrotou \\#ffff5a\\cinco\\#ffa0a0\\ jogadores!",
  kill_combo_large = "\\#ffa0a0\\Uau! %s\\#ffa0a0\\ já consegiu\\#ffff5a\\%d\\#ffa0a0\\ baixas em uma única tacada!",
  set_hack = "A hack selecionada foi %s",
  incompatible_hack = "AVISO: Essa hack não é compatível!",
  vanilla = "Usando o jogo original",
  omm_detected = "OMM Rebirth está em uso!",
  omm_bad_version = "\\#ff5a5a\\Moveset do OMM está desatualizado!\\#ffffff\\\nVersão mínima: %s\nSua versão: %s",
  custom_enter = "%s\\#ffffff\\ entrou\n%s",                                    -- same as coop
  demon_unlock = "O modo Demônio Verde foi desbloqueado!",
  hit_switch_red = "%s\\#ffa0a0\\ pressione o\n\\#df5050\\botão Vermelho!",     -- dark red (unique)
  hit_switch_green = "%s\\#ffa0a0\\ pressione o\n\\#50b05a\\botão Verde!",      -- dark green (unique)
  hit_switch_blue = "%s\\#ffa0a0\\ pressione o\n\\#5050e3\\botão Azul!",        -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ pressione o\n\\#e3b050\\botão Amarelo...", -- orangeish (unique)
  connected = "%s\\#ffff5a\\ conectou-se!",                                     -- same as coop
  disconnected = "%s\\#ffa0a0\\ desconectou-se",                                -- same as coop


  -- command feedback
  not_mod = "Você não tem AUTORIDADE para usar esse comando, seu tolo!",
  no_such_player = "Esse jogador não existe.",
  bad_id = "ID de jogador inválido!",
  command_disabled = "Esse comando está deshabilitado.",
  change_setting = "Configuração Alterada:",

  -- more command feedback
  bad_param = "Parâmetros inválidos!",
  bad_command = "Comando inválido!",
  error_no_runners = "Não se pode começar o jogo sem corredores!",
  set_team = "O time de %s's foi mudado para '%s'",
  not_started = "A Rodada não começou ainda",
  set_lives_one = "%s agora tem apenas 1 vida extra",
  set_lives = "%s agora tem %d vida(s) extra(s)",
  not_runner = "%s Não é um Corredor",
  may_leave = "%s pode sair.",
  must_have_one = "Deve ter no mínimo 1 caçador!",
  added = "Corredores adicionados: ",
  runners_are = "Os Corredores são: ",
  set_lives_total = "Vidas dos corredores definidas para %d",
  wrong_mode = "Não está disponível neste modo.",
  need_time_feedback = "Corredores poderão sair em %d segundos(s) a partir de agora.",
  game_time = "O jogo durará %d segundo(s)",
  need_stars_feedback = "Corredores precisam de %d star(s) agora",
  new_category = "Agora é uma speedrun de %d estrelas.",
  new_category_any = "Agora a partida é uma speedrun any%",
  mode_normal = "Está no Modo Normal",
  mode_swap = "Está no Modo Swap",
  --mode_swap = "Mudando o Modo de jogo", -- I think there was a miscommunication here
  mode_mini = "Está no modo Mini-Caça",
  mode_mys = "Está no modo Caça-Mistério",
  using_stars = "Usando estrelas coletadas",
  using_timer = "Usando Cronômetro",
  can_spectate = "Caçadores podem agora observar a partida",
  no_spectate = "Caçadores não poderão mais observar.",
  all_paused = "Todos os jogadores estão pausados",
  all_unpaused = "Todos os jogadores estão despausads",
  player_paused = "%s foi pausado",
  player_unpaused = "%s foi despausado",
  hunter_metal = "Todos os Caçadores serão metálicos",
  hunter_normal = "Todos os Caçadores estão com aparência normal.",
  hunter_glow = "Todos os Caçadores brilham em vermelho",
  hunter_outline = "Todos os Caçadores têm um contorno.",
  runner_normal = "Todos os Corredores estão com aparência normal.",
  runner_sparkle = "Todos os Corredores emitem um efeito.",
  runner_glow = "Todos os Corredores brilham",
  runner_outline = "Todos os Corredores têm um contorno",
  now_weak = "Todos os jogadores têm meio-frame (quadro) de invencibilidade.",
  not_weak = "Todos os jogadores têm frames (quadros) de invencibilidade.",
  auto_on = "A rodada vai iniciar automaticamente",
  auto_off = "Rodadas não vão iniciar automaticamente.",

  -- team chat
  tc_toggle = "Chat de time está %s!",
  to_team = "\\#8a8a8a\\Para time: ",
  from_team = "\\#8a8a8a\\ (time): ",

  -- hard mode
  hard_notice = "Psiu, tente usar o modo /hard...",
  extreme_notice = "Psiu, tente usar o modo /hard ex...",
  hard_toggle = "\\#ff5a5a\\Modo Difícil\\#ffffff\\ está %s!",
  extreme_toggle = "\\#b45aff\\Modo Extremo\\#ffffff\\ está %s!",
  hard_info = "Interessado em usar o \\#ff5a5a\\Modo Difícil\\#ffffff\\?" ..
      "\n- Barra de vida pela metade." ..
      "\n- A água não recupera sua vida" ..
      "\n- \\#ff5a5a\\Uma vida" ..
      "\n\\#ffffff\\Use o comando /hard ON se você topa tentar o desafio.",
  hard_mode = "Modo Difícil",
  extreme_mode = "Modo Extremo",
  hard_info_short = "Barra de vida pela metade, uma vida, e a água não te faz recuperar a vida.",
  extreme_info_short = "Um pedaço na barra de vida, uma vida extra e o Cronômetro Mortal.",

  -- spectator
  hunters_only = "Apenas os caçadores podem observar a partida!",
  spectate_disabled = "Modo de observação desligado!",
  timer_going = "Você não pode observar durante o temporizador!", -- now unused
  spectate_self = "Você não pode observar a si mesmo!",
  spectator_controls = "Controles:" ..
      "\nDPAD-UP: Desligar a barra de status" ..
      "\nDPAD-DOWN: Trocar entre câmera livre/visão do jogador" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Trocar de jogador" ..
      "\nJOYSTICK: Movimentar" ..
      "\nA: Ir para cima" ..
      "\nZ: Ir para baixo" ..
      "\nType \"/spectate OFF\" para cancelar.",
  spectate_off = "Não está mais observando.",
  empty = "VAZIO (%d )",
  free_camera = "CÂMERA LIVRE",

  -- stats
  disp_wins_one = "%s\\#ffffff\\ ganhou uma vez como \\#00ffff\\Corredor\\#ffffff\\!",
  disp_wins = "%s\\#ffffff\\ ganhou %d vezes como \\#00ffff\\Corredor\\#ffffff\\!",
  disp_kills_one = "%s\\#ffffff\\ matou um jogador!",
  disp_kills = "%s\\#ffffff\\ matou %d jogadores!",
  disp_wins_hard_one =
  "%s\\#ffffff\\ ganhou uma vez como \\#ffff5a\\Corredor\\#ffffff\\ no \\#ff5a5a\\Modo Difícil!\\#ffffff\\",
  disp_wins_hard =
  "%s\\#ffffff\\ ganhou %d vezes como \\#ffff5a\\Corredor\\#ffffff\\ no \\#ff5a5a\\Modo Difícil!\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ ganhou uma vez como \\#b45aff\\Corredor\\#ffffff\\ no \\#b45aff\\Modo Extremo!\\#ffffff\\",
  disp_wins_ex =
  "%s\\#ffffff\\ ganhou %d vezes como \\#b45aff\\Corredor\\#ffffff\\ no \\#b45aff\\Modo Extremo!\\#ffffff\\",
  -- for stats table
  stat_wins_standard = "Vitórias",
  stat_wins = "Vitórias (Mini-Caça/pré v2.3)", -- probably wrong
  stat_wins_mys = "Vitórias (Caça-Mistério)",   -- probably wrong
  stat_kills = "Já Matou",
  stat_combo = "Combo Máx. de Assassinatos",
  stat_wins_hard_standard = "Vitórias no Modo Difícil",
  stat_wins_hard = "Vitórias no Modo Difícil (Mini-Caça/pré v2.3)",
  stat_wins_hard_mys = "Vitórias no Modo Difícil (Caça-Mistério)",
  stat_mini_stars = "Máximo de Estrelas em uma rodada de Mini-Caça",
  stat_wins_ex_standard = "Vitórias no Modo Extremo",
  stat_wins_ex = "Vitórias no Modo Extremo (Mini-Caça/pré v2.3)",
  stat_wins_ex_mys = "Vitórias no Modo Extremo (Caça-Mistério)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1ro Lugar]",
  place_2 = "\\#c5d8de\\[64T: 2ndo Lugar]",
  place_3 = "\\#b38752\\[64T: 3ro Lugar]",
  place = "\\#e7a1ff\\[64T: %do Lugar]", -- thankfully we don't go up to 21
  place_score_1 = "%dro",
  place_score_2 = "%dndo",
  place_score_3 = "%dro",
  place_score = "%do",

  -- command descriptions
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Inicia a rodada; adicione \"continue\" para que não seja teleportado para o início; adicione \"alt\" para uma save file alternativa (bugado); adicione \"main\" para a save file principal; adicione \"reset\" para resetar a sua save file (bugado)",
  add_desc = "[INT] - Os corredores virão em número aleatório.",
  random_desc = "[INT] - Seleciona os Corredores de forma aleatória com o número dado",
  random_desc_hunt = "[INT] - Seleciona os Caçadores de forma aleatória com o número dado",
  lives_desc =
  "[INT] - Seleciona o máximo de vidas dos corredores, de 0 até 99 (Não esqueça: 0 vidas ainda contam como 1!)",
  time_desc =
  "[NUM] - Define o tempo que os Corredores tem que aguardar para sair, em segundos, ou o tempo total do jogo na Mini-Caça.",
  stars_desc = "[INT] - Define quantas estrelas os Corredores devem coletar para sair, de 0 a 7 (apenas no Modo Estrela)",
  category_desc = "[INT] - Define quantas estrelas o jogador deve ter para enfrentar o Bowser.",
  flip_desc = "[NAME|ID] - Troca o jogador especificado de equipe",
  setlife_desc = "[NAME|ID|INT,INT] - Muda o número de vidas com o selecionado para os Corredores",
  leave_desc = "[NAME|ID] - Permitir que um jogador em específico saia da fase.",
  mode_desc = "[NORMAL|SWAP|MINI] - Muda o tipo de jogo; swap troca o jogador assim que ele morre.",
  starmode_desc = "[ON|OFF] - Define que sejam utilizadas estrelas coletadas e não um cronômetro",
  spectator_desc = "[ON|OFF] - Liga para os Caçadores a habilidade de observar a partida",
  pause_desc = "[NAME|ID|ALL] - Aciona o modo pausa para o(s) jogador(es), todos se não for especificado",
  hunter_app_desc = "Muda a aparência dos Caçadores.",
  runner_app_desc = "Muda a aparência dos Corredores.",
  hack_desc = "[STRING] - Seleciona a Rom-Hack atual.",
  weak_desc = "[ON|OFF] - Cortar os quadros de invencibilidade no meio para todos os jogadores",
  auto_desc = "[ON|OFF|NUM] - Inicia partidas automaticamente.",
  stalking_desc = "[ON|OFF] - Permite teleportar para o nível de um caçador com /stalk",

  -- mute
  muted = "\\#ffff00\\%s\\#ffffff\\ foi silenciado por \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ permitiu \\#ffff00\\%s\\#ffffff\\ falar novamente.",
  you_muted = "Você silenciou \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Você permitiu \\#ffff00\\%s\\#ffffff\\ falar novamente.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ foi silenciado automaticamente.",

  -- Blocky's menu
  main_menu = "Menu Principal",
  menu_settings = "Configurações do jogo", -- translate verified
  --menu_settings_player = "Configurações",
  menu_rules = "Regras",
  menu_lang = "Idioma",
  menu_misc = "Outros",
  menu_exit = "Sair",
  menu_back = "Voltar",
  menu_mh = "Caça-Mario",
  menu_mh_egg = "Caça-Luigi",
  menu_stars = "Estrelas",
  menu_tc = "Chat de time",
  menu_defeat_bowser = "Derrote %s",
  menu_hunter_app = "Aparência do Caçador",
  menu_runner_app = "Aparência do Corredor",
  menu_allow_stalk = "Permitir 'Perseguição'",
  menu_season = "Mudanças Temáticas",
  menu_season_desc = "Mudanças visuais divertidas podem acontecer dependendo da data.",

  -- updater (difference for "_egg" is Luigi instead of Mario)
  up_to_date = "\\#ff5a5a\\Caça\\#00ffff\\Mario\\#ffffff\\ está na versão mais recente!",
  up_to_date_egg = "\\#ff5a5a\\Caça\\#5aff5a\\Luigi\\#ffffff\\ está na versão mais recente!",
  has_update = "Uma versão nova de \\#ff5a5a\\Caça\\#00ffff\\Mario\\#ffffff\\ está disponível!",
  has_update_egg = "Uma versão nova de \\#ff5a5a\\Caça\\#5aff5a\\Luigi\\#ffffff\\ está disponível!",

  -- not really organized
  lang_desc = "%s - Trocar linguagem",
  got_all_stars = "Você possui estrelas suficientes!",
  spectate_mode = "- MODO ESPECTADOR -",
  menu_allow_spectate = "Permitir Observar",
  menu_hide_roles_desc = "Esconder sua função no chat.",
  menu_stop = "Parar",
  spectate_desc =
  "[NAME|ID|OFF] - Observar um jogador, ativa a câmera livre se não for especificado o jogador, ou OFF para desligar.",
  menu_stalk_run = "Teleportar para a fase de um Corredor",
  stop_desc = "- Parar o jogo",
  menu_star_mode = "Modo Estrela",
  tc_desc = "[ON|OFF|MSG] - Mandar mensagem para seu time apenas; Ative o ON para aplicar em todas as mensagens.",
  stars_in_area = "%d estrela(s) disponível(is) aqui!",
  force_spectate_one = "%s precisam observar.",
  menu_demon_desc = "Permitir que um Cogumelo Vida Extra persiga você quando for corredor.",
  vote_pass = "Passou a vez de votar!",
  menu_stats = "Estatísticas",
  extreme_info = "Certeza que tem chances com o \\#b45aff\\Modo Extremo\\#ffffff\\? Que tolice.\
  - Uma vida\
  - Um pedaço de vida na barra\
  - \\#b45aff\\Temporizador mortal\\#ffffff\\; colete moedas para aumentar\
  Se isso não te faz ter medo, digite /hard ex ON.",
  role_trans = "\\#ffd996\\[Tradutor MH]",
  role_lead = "\\#9a96ff\\[Desenvolv. Líder MH]",
  warp_desc = "[LEVEL|COURSE,AREA,ACT,NODE] - Teleportar para a fase",
  menu_timer = "Cronômetro de Speedrun",
  menu_first_timer = "Cronômetro de Liderança Mortal",
  menu_popup_sound = "Sons dos Pop-ups",
  stalk_desc = "[NAME|ID] - Teleportar para a fase de um Corredor específico, ou o primeiro Corredor.",
  menu_run_random = "Corredores aleatórios",
  menu_hunt_random = "Caçadores aleatórios",
  blacklist_add = "Listou %s",
  menu_hide_roles = "Esconder minhas funções",
  open_menu = "Digite /mh ou pressione %s para abrir o menu",
  menu_nerf_vanish = "Nerfar a Boina invisível",
  forcespectate_desc =
  "[NAME|ID|ALL] - Forçar que um jogador em específico fique observando ou todos se nenhum for especificado.",
  stalk = "Use /stalk para ir até a fase de um Corredor!",
  menu_category = "Categoria",
  stat_placement = "Posição no Tour 64",
  menu_fast = "Ações Ágeis",
  default_desc = "- Resetou as opções.",
  new_record = "\\#ffff5a\\NOVO RÉCORDE!!!",
  anarchy_set_2 = "Caçadores podem bater nos seus companheiros",
  menu_skip = "Pular",
  menu_stalk_run_desc = "Ir para a fase que se localiza o primeiro Corredor.",
  no_runners_added = "Nenhum Corredor adicionado",
  menu_exit_spectate_desc = "Sair do modo Espectador.",
  menu_flip = "Trocar de Equipe",
  quick_desc = "[LEVEL|COURSE|HUNTER,AREA,ACT,NODE] Teste rápido de jogo",
  menu_first_timer_desc = "Dá ao Corredor em primeiro um Cronômetro Mortal.",
  menu_save_continue = "Continuar (Não há teleporte para voltar)",
  menu_start = "Começar",
  role_dev = "\\#96ecff\\[Desenvolv. MH]",
  -- menu_nerf_vanish_desc = "Nerfa a Boina da invisibilidade e drena ela mais rápido quando usada.",
  menu_blacklist_list_desc = "Lista todas as estrelas na lista negra..",
  menu_pause = "Pausa",
  menu_players_all = "Todos os jogadores",
  menu_toggle_all = "Ligar tudo",
  menu_blacklist_reset_desc = "Resetar a lista negra para os padrões.",
  unstuck = "Tentando voltar ao padrão",
  menu_blacklist_load = "Carregar Lista Negra",
  menu_blacklist_load_desc = "Carregar sua Lista Negra salva.",
  menu_blacklist_reset = "Resetar a Lista Negra",
  menu_blacklist_save_desc = "Salvar sua Lista Negra ao final.",
  menu_blacklist_save = "Salvar Lista Negra",
  menu_blacklist_list = "Listar todas na Lista Negra",
  menu_spectate_desc = "Observar este jogador.",
  menu_skip_desc = "- Votar para pular essa estrela na Mini-Caça.",
  menu_exit_spectate = "Sair do modo de Observação",
  menu_spectate_run_desc = "Automaticamente Observar o primeiro Corredor.",
  menu_list_settings = "Listar as Opções",
  menu_spectate_run = "Observar Corredor",
  anarchy_set_3 = "Jogadores podem atingir seus companheiros de equipe.",
  menu_free_cam_desc = "Entrar no modo Câmera Livre quando estiver Observando.",
  menu_fast_desc = "Você vai se recuperar, arremesar objetos e abrir portas rapidamente.",
  menu_secret = "Isto é um segredo. Como você pode descubrir?",
  menu_hide_hud = "Esconder o HUD",
  hidehud_desc = "- Esconder todos os elementos do HUD.",
  menu_stalk = "Teleportar para a fase",
  dmgAdd_set = "Corredores agora tomarão %d de dano extra por ataques PvP.",
  dmgAdd_set_ohko = "Os Corredores morrerão após um único dano",
  voidDmg_set = "Jogadores tomarão um dano de %d por cair em buracos ou em areia movediça.",
  voidDmg_set_ohko = "Jogadores morrerão instantaneamente após cair em um buraco ou em areia movediça.",
  target_hunters_only = "Apenas Caçadores podem selecionar um alvo.",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Ligar o Modo Difícil apenas para você",
  is_spectator = "* ESSE JOGADOR ESTÁ OBSERVANDO  *",
  menu_setlife = "Definir vidas extras",
  menu_allowleave = "Permitir saída",
  menu_forcespectate = "Forçar Observação",
  menu_stalk_desc = "Teleportar para a fase desse jogador.",
  menu_demon = "Demônio Verde",
  menu_spectate = "Observar",
  force_spectate_off = "Spectar não é mais obrigatório",
  menu_dmgAdd = "Corredor PVP DMG",
  menu_anarchy_desc = "Permite que os jogadores específicos possam atacar os jogadores da mesma equipe.",
  rules_desc = "- Mostrar as regras da Caça-Mario",
  rules_desc_egg = "- Mostrar as regras da Caça-Luigi",
  menu_anarchy = "Ataque de Times",
  menu_blacklist = "Lista Negra da Mini-Caça",
  mh_desc = "[COMMAND,ARGS] - Usa comandos; digite nada, ou \"menu\" para abrir o menu",
  blacklist_list = "Lista Negra:",
  menu_auto = "Jogo Automático",
  menu_weak = "Modo Fraqueza",
  menu_gamemode = "Modo de jogo",
  menu_campaign = "Campanha",
  menu_random = "Aleatório",
  menu_save_reset = "Resetar Save File Alternativa",
  ---- vanish_custom = "Segure \\#ffff5a\\%s\\#ffffff\\ para desaparecer!",
  menu_save_main = "Principal",
  menu_run_lives = "Vidas Extras dos Corredores",
  menu_timer_desc = "[ON|OFF] - Mostrar um cronômetro no canto da tela no modo Padrão.",
  menu_list_settings_desc = "Lista todas as opções deste servidor.",
  blacklist_reset = "Resetar a Lista Negra!",
  blacklist_save = "A Lista Negra foi salva!",
  blacklist_load = "A Lista Negra foi carregada!",
  all = "Tudo",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Adicionar a Lista Negra estrelas na Mini-Caça",
  blacklist_remove = "Aprovou %s",
  page = "\\#ffff5a\\Página %d/%d",
  menu_default = "Restaurar para o Padrão",
  anarchy_set_1 = "Corredores podem atacar seus companheiros de equipe",
  menu_run_add = "Adicionar Corredores",
  blacklist_remove_already = "Essa estrela e(ou) fase não está na Lista Negra.",
  force_spectate = "Todos devem observar",
  menu_save_alt = "Save file alternativa",
  menu_tc_desc = "Converse apenas com sua equipe.",
  already_voted = "Você já votou.",
  vote_info = "Digite /skip para votar",
  vote_skip = "%s\\#dcdcdc\\ votou para pular essa estrela",
  blacklist_remove_invalid = "Não é possível aprovar essas fases.",
  no_hard_win = "Suas vitórias e pontuações no modo Extremo e Difícil não serão atualizados nessa rodada.",
  death_timer = "Morte",
  blacklist_add_already = "Essa estrela e(ou) fase já está na Lista Negra.",
  anarchy_set_0 = "Jogadores não podem atacar seus companheiros de equipe.",
  menu_dmgAdd_desc = "Definir este número de dano aos Corredores.",
  no_valid_star = "Não foram achadas estrelas válidas!",
  warp_spam = "Devagar aí com os teleportes!",
  mini_score = "Pontuação: %d",
  stats_desc = "- Mostrar/Esconder a tabela de estatísticas",
  force_spectate_one_off = "%s não precisa observar ninguém mais",
  menu_time = "Tempo",
  desync_desc = "- Tenta arrumar problemas de dessincronizacão",
  role_cont = "\\#ff9696\\[Contribuidor MH]",
  target_desc = "[NAME|ID] - Selecionar este Corredor como seu alvo. Ele estará em destaque na tela a todo tempo.",
  use_out = "Use /mh out para expulsar todos de um mundo.",
  you_are_muted = "Você está silenciado.",
  out_desc = "[LEVEL|COURSE] - Expulsa todos de um mundo",
  menu_countdown = "Contagem Regressiva",
  menu_countdown_desc = "Quanto um Caçador deve esperar até começar.",
  menu_voidDmg = "DN. de Buraco",
  menu_voidDmg_desc = "Dano que um jogador recebe ao cair num buraco sem fundo ou areia movediça.",
  menu_double_health = "Dobro da Barra de Vida",
  menu_double_health_desc = "Jogadores têm direito à 16 pontos de vida ao invés de 8.",
  menu_target = "Selecionar como Alvo",
  menu_mute = "Silenciar",
  mute_desc = "[NAME|ID] - Silencia um jogador, fazendo com que ele não fale mais no chat",
  unmute_desc = "[NAME|ID] - Permite que um jogador silenciado volte a falar no chat",

  -- v2.6
  leave_error = "%s\\#ffa0a0\\ saiu devido um erro.",
  hunter_color = "Todos os Corredores têm a paleta Burgundy.",
  runner_color = "Todos os Corredores têm a paleta Azure.",
  stat_playtime = "Tempo de jogo (em horas)",
  stat_parkour_time = "Tempo mais rápido no Parkour",
  stat_parkour_time_omm = "Tempo mais rápido no Parkour (OMM)",
  stat_parkour_time_other = "Tempo mais rápido no Parkour (Moveset)",
  menu_free_roam = "Andar Livremente",
  menu_free_roam_desc = "Desabilita qualquer requerimento de Estrelas e Chaves em portas e níveis.",
  menu_radar = "Radar",
  menu_radar_desc = "Mostra onde Corredores e objetos importantes estão.",
  menu_minimap = "Mini-mapa",
  menu_minimap_desc = "Exibe um mapa do nível inteiro.",
  menu_romhack_cam = "Câmera de Rom Hack",                -- (cam is short for camera)
  menu_romhack_cam_desc = "Habilita câmera de Rom Hack.", -- (cam is short for camera)
  menu_star_heal = "Recuperação por Estrela",

  menu_star_setting = "Na Coleção de Estrelas", -- from base
  star_leave = "Sair",
  star_stay = "Ficar",
  star_nonstop = "Sem-Parar",

  -- v2.7
  added_count = "Adicionou %d Corredores",
  added_count_one = "Adicionou 1 Corredor",
  become_spectator = "vIre um \\#a9a9a9\\Observador\\#ffffff\\ quando derrotado.",
  dead = "Morto",
  dead_become = "\\#00ffff\\Corredores\\#ffffff\\ mortos deixam um corpo.",
  dead_become_infection = "Jogadores mortos que não se tornam \\#ff5a5a\\Caçadores\\#ffffff\\ deixam um corpo.",
  dead_become_noconfirm = "Dead players leave behind a body.",
  disp_asn_bronze = "%s\\#ffffff\\ obteve \\#b38752\\bronze\\#ffffff\\ no torneio ASN!",
  disp_asn_quarter = "%s\\#ffffff\\ chegou as \\#70ff94\\quartas de final\\#ffffff\\ no torneio ASN!",
  disp_asn_silver = "%s\\#ffffff\\ obteve \\#c5d8de\\prata\\#ffffff\\ no torneio ASN!",
  disp_asn_win = "%s \\#e3bc2d\\venceu\\#ffffff\\ o torneio ASN!",
  far = "\\#8a8a8a\\(longe)",
  global_talk_end = "\\#ffa0a0\\Chat Global encerrado.",
  global_talk_start = "\\#ffa0a0\\Chat Global está ligado por %d segundo(s).",
  guard_cooldown = "Pode proteger em %d",
  guard_info = "Pressione %s para proteger %s",
  guard_info_rules = "Jogadores mortos podem proteger seus colegas de equipe em %s.",
  guard_save = "\\#ffff00\\Um fantasma o salvou!",
  guard_timer = "%s\\#ffff00\\ está protegido (%d)",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Caçadores\\#ffa0a0\\ sobrando.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Caçador\\#ffa0a0\\ sobrando.",
  players_remain = "\\#ffa0a0\\%d jogadores sobrando.",
  players_remain_one = "\\#ffa0a0\\1 jogador sobrando.",
  hunters_set_count = "Há %d Caçadores",
  hunters_set_count_one = "Há 1 Caçador",
  hunters_were = "Os Caçadores eram: ",
  keep_secret = "Não seja pego!",
  menu_binds = "Alterar Controles",
  menu_binds_desc = "Altere os botões usados para certas ações.",
  menu_confirm_hunter = "Confirmar Mortes de Caçador",
  menu_confirm_hunter_desc = "Exibe uma mensagem quando um Caçador for eliminado. Se desabilitado, Caçadores também deixam corpos.",
  menu_coop = "Cooperativo",
  menu_global_chat = "Tempo de Chat Global",
  menu_global_chat_desc = "Período que Jogadores podem usar quando um corpo for localizado.",
  menu_grace_period = "Período de Graças",
  menu_grace_period_desc = "Conta o tempo até que outro Jogador possa ser eliminado.",
  menu_guard_button = "Proteger",
  menu_guard_button_desc = "Botão pressionado para proteger um Jogador enquanto Observador no Caça-Mistério.",
  menu_hunters_win_early = "Hunters Win Early",
  menu_hunters_win_early_desc = "Caçadores ganham quando empatam/passam o número de Corredores, como em Among Us.",
  menu_invinc_particle = "Sparkle I-Frames",
  menu_invinc_particle_desc = "Substitui o efeito \"cintilante\" quando Mario leva dano com Partículas Brilhantes.",
  menu_know_team = "Caçadores sabem qual seu Time",
  menu_know_team_desc = "Caçadores sabem quem compõe sua equipe. Se desabilitado, Caçadores poderão se matar.",
  menu_menu_button = "Abrir Menu",
  menu_menu_button_desc = "Tecla(s) apertadas para abrir o menu do Caça-Mario.",
  menu_overlay = "Menu do Progresso de Mundo",
  menu_overlay_desc = "Exibe quais estrelas, chaves, e Botões de Chapéu estão próximas de um mundo/pintura.",
  menu_presets = "Presets",
  menu_report_button = "Reportar/Consertar",
  menu_report_button_desc = "Botão usado para reportar corpos ou consertar sabotagens no Caça-Mistério.",
  menu_sabo = "Sabotar",
  menu_sabo_button = "Abrir o Menu de Sabotagem",
  menu_sabo_button_desc = "Botão usado para abrir o menu de Sabotagem no Caça-Mistério.",
  menu_show_on_map = "Mostrar no Mapa",
  menu_show_on_map_desc = "Quais equipes podem ser vistas no mapa (Oponentes também terão um radar)",
  menu_shuffle = "Embaralhar Equipes",
  menu_shuffle_desc = "Embaralha as equipes de todos os Jogadores vivos um tempo determinado.",
  menu_spectate_on_death = "Corredores se tornam Observadores ao morrer",
  menu_stalk_timer = "Temporizador de Stalk",
  menu_stalk_timer_desc = "Tempo que o Jogador fica congelado após usar o /stalk.",
  menu_star_stay_old = "Continuar Mesmo que já Obtida",
  menu_star_stay_old_desc = "Coletar uma estrela que já foi obtida não vai te ejetar do mundo.",
  menu_star_timer = "Tempo Desde a Última Estrela",
  menu_star_timer_desc = "Exibe quando a última estrela foi obtida no inferior da tela.",
  menu_unknown = "???",
  menu_vanish_button = "Desaparecer",
  menu_vanish_button_desc = "Botão segurado para desaparecer enquanto a opção \"Nerf Vanish Cap\" estiver habilitada.",
  mystery_altgoal = "OU: Descubra quem são os \\#ff5a5a\\Caçadores\\#ffffff\\ e os derrote.",
  mysteryhunt_disabled = "\\#ffa0a0\\Um dos seus mods não é compatível com Caça-Mistério!",
  mysteryhunt_innocent = "\\#ffa0a0\\Você matou um Jogador inocente!",
  mysteryhunt_spectate = "\\#ffa0a0\\Você irá observar esta partida.",
  nearby = "\\#8a8a8a\\(próximo)",
  no_players_here = "Não há jogadores aqui!",
  no_runners_here = "Não há \\#00ffff\\Corredores\\#ffffff\\ aqui!",
  opponents = "Oponentes",
  other_hunters = "Outros Corredores são: ",
  place_asn = "\\#e7a1ff\\[Participante do ASN]",
  place_asn_1 = "\\#e3bc2d\\[Vencedor do ASN]",
  place_asn_2 = "\\#c5d8de\\[Prata no ASN]",
  place_asn_3 = "\\#b38752\\[Bronze no ASN]",
  place_asn_4 = "\\#70ff94\\[Finalista de Quartas do ASN]",
  preset_asn = "Torneio ASN",
  preset_asn_desc = "Mesmas configurações usadas no Torneio ASN (com 1 vida extra).",
  preset_classic = "Modo Clássico",
  preset_classic_desc = "Altera as configurações para ficarem iguais as versões antigas do Caça-Mario.",
  preset_infection = "Modo Infecção",
  preset_infection_desc = "1 Caçador para Infectar! Os Corredores podem sobreviver?",
  preset_quick = "Partida Relâmpago",
  preset_quick_desc = "30 Estrelas, Mundos Liberados, run Sem-Bowser.",
  preset_solo = "Modo Solo",
  preset_solo_desc = "Você contra tudo e todos! 3 vidas, Barra-de-Vida dupla.",
  preset_star_rush = "Corrida da Estrela",
  preset_star_rush_desc = "Mini-Caça, mas todos são Corredores!",
  preset_tag = "Pega-Pega",
  preset_tag_desc = "Pegue um Corredor para se tornar um!",
  press_fix = "%s - Consertar",
  press_report = "%s - Reportar",
  report_body = "%s\\#ffa0a0\\ encontrou o corpo de %s\\#ffa0a0\\ em \\#ffff5a\\",
  report_info_rules = "Pressione %s para reportar e discutir.",
  role_dead = "\\#ff2020\\[MORTO]",
  runners_can_kill = "\\#00ffff\\Corredores\\#ffffff\\ podem eliminar Jogadores os quais eles suspeitam de ser \\#ff5a5a\\Caçadores\\#ffffff\\.\nSe eles eliminarem alguém inocente, eles também serão eliminados.",
  runners_remain = "%d \\#00ffff\\Corredores\\#ffffff\\ restantes.",
  runners_remain_one = "1 \\#00ffff\\Corredor\\#ffffff\\ restante.",
  sabo_activate_timer = "Ativando em %d",
  sabo_active = "\\#ffff00\\SABOTAGEM ATIVA!",
  sabo_bomb = "\\#ff4040\\Mega Bomba",
  sabo_bomb_desc = "Mata todos os jogadores se ativa!",
  sabo_bomb_timer = "\\#ff4040\\Todos morrerão em %d:%02d",
  sabo_cooldown = "Poderá sabotar em %d:%02d",
  sabo_dark = "\\#5050ff\\Escuridão",
  sabo_dark_desc = "Cobre o mundo em uma escuridão!",
  sabo_gas = "\\#ffff32\\Gás Tóxico",
  sabo_gas_desc = "Faz com que gás tóxico apareça!",
  sabo_info = "Pressione %s para sabotar",
  sabo_info_rules = "\\#ff5a5a\\Caçadores\\#ffffff\\ também podem causar um caos com sabotagens.\nPara desabilitar uma sabotagem, vá para o Mundo indicado e selecione %s na sabotagem.",
  scroll_up = "Mova para cima para mais...",
  shuffle_timer = "Embaralhando equipes em %d",
  stat_crown = "Coroa ASN",
  stat_placement_asn = "Colocação no Torneio ASN",
  tc_only_hunter = "Apenas Caçadores vivos podem utilizar o Chat de Equipe.",
  unless_defeated = "exceto se derrotado por outro Jogador.",
  unsaved_changes = "\\#ff5a5a\\Você tem configurações que não foram salvas! Pressione novamente se tiver certeza.",
  until_grace = "%d segundo(s) até que o Período de Graça acabe",

  -- Tips:
  -- These are not a priority. You can translate these if you want.
  tip = "Tip: ",
  tip_1 = "Pressione %s, ou digite no chat /mh, para abrir o menu. Você pode acessar as configurações lá!",
  tip_2 = "Bundadas causam um dano equivalente a 3 barras à outros jogadores.",
  tip_3 = "Um chute causa um dano equivalente à 2 barras e lançam jogadores longe!",
  tip_4 = "Para comandos como /spectate e /target, você pode abreviá-los, e eles ainda funcionarão (ex: digitar \"Emily\" se refere a EmilyEmmi)",
  tip_5 = "É possível alterar configurações no meio de uma partida.",
  tip_6 = "Se algo der errado, digite /mh pause para interromper todos os jogadores. Digite novamente para desfazer o efeito de pausa.",
  tip_7 = "Tem alguém usando palavras ofensivas, ou fazendo spam? Digite /mh mute para silenciar o jogador!",
  tip_8 = "Você pode pausar durante a coleta de uma Estrela ou Chave e sair do Mundo para pular a animação.",
  tip_9 = "Você pode tornar um Corredor seu alvo com o comando /target. Sua localização estará no lado superior da tela.",
  tip_11 = "Não precisa reiniciar seu servidor! Selecione \"Reset Alt Save\" em \"Start\" para resetar as configurações.",
  tip_10 = "Você pode mexer em configurações suas durante a partida (%s).",
  tip_12 = "Você pode se tornar um Corredor ao eliminar um.",
  tip_13 = "Assim como no Super Mario 64 original, 0 ainda é considerada uma vida.",
  tip_14 = "Glitches complexos, como o LBLJ, são inúteis fora de uma Any%.",
  tip_15 = "Placas no jogo podem ser úteis e ter dicas!",
  tip_16 = "A Baía de Todos os Piratas (Dire, Dire, Docks) pode ser acessada com uma estrela a menos na classificação atual.",
  tip_17 = "Configure o Cappy para \"Damage\" para usá-lo como arma de alcance. Seu dano equivale a 1.",
  tip_18 = "Cappy consegue pegar objetos, como Moedas e Segredos.",
  tip_19 = "Use o D-Pad para arremessar Cappy em diferentes direções.",
  tip_20 = "Confira o vídeo do Key's Artwork's no YouTube para aprender a técnica no moveset OMM!",
  tip_21 = "Se os objetos não aparecerem ou canos não funcionem, use /mh out para forçar um reset naquele Mundo.",
  tip_22 = "Use /mh desync se você acha que uma dessincronização tenha ocorrido.",
  tip_23 = "Matar outro jogador restaura sua barra de vida.",
  tip_24 = "Você pode ver seu progresso com Chaves, Estrelas e Botões de Chapéu no menu do Castelo.",
  tip_25 = "Corredores podem infringir dano uns contra os outros nesse modo!",
  tip_26 = "Cair em Mundos que possuam um Botão de Chapéu também podem fazê-lo perder uma vida.",
  tip_27 = "Pistões de Moeda Azul podem restaurar sua barra de vida.",
  tip_28 = "Você pode selecionar outro Ato para despistar Caçadores.",
  tip_29 = "Hoje é Feriado! Se não gostar dos efeitos, desligue a opção \"Seasonal Changes\" no menu.",
  tip_30 = "Você pode espionar Corredores com /spectate.",
  tip_31 = "Use /stalk para se teletransportar para um Mundo com Corredores!",
  tip_32 = "Aprender técnicas de speedrun é uma boa maneira de melhorar no jogo.",
  tip_33 = "Você pode escapar de Esmagões executando uma Bundada ou um chute enquanto eles caem.",
  tip_34 = "A maneira mais rápida de fazer um Pulo Triplo é executado um chute logo após o primeiro pulo.",
  tip_35 = "Os Bonés Metálicos potencializam o dano infringido contra um jogador.",
  tip_36 = "A Boina Invisível só vai te proteger se você apertar/segurar %s.",
  tip_37 = "Temporizadores de Boné não diminuem enquanto você estiver num canhão.",
  tip_38 = "Não fique enrolando na seleção de Ato por muito tempo!",
  tip_39 = "Mergulhos são rápidos, portanto, mergulhar em outro jogador pode ser eficiente para fugir de ataques.",
  tip_40 = "Cair de um Mundo vai lhe dar dano ao invés de eliminá-lo.",
  tip_41 = "1-Vida vai restaurar 4 barras de vida.",
  tip_42 = "Use o menu de Jogadores para fazer configurações específicas, como mudança de equipe.",
  tip_43 = "O menu do Caça-Mario auxilia para fazer configurações e iniciar partidas.",
  tip_44 = "Você pode ocultar sua equipe no chat pelas configurações.",
  tip_45 = "Corredores usando o Boné Metálico ainda podem levar dano dos Caçadores.",
  tip_46 = "No menu, certifique-se de ter apertado 'A' para salvar suas configurações!",

  -- v2.8
  default = "Padrão",
  gc_desc = "[MSG] - Mande mensagens que todos os jogadores possam ver, mesmo que esteja morto; anfitrião/mod apenas.",
  menu_default_role = "Papel Padrão",
  menu_default_role_desc = "Qual time será selecionado para novos jogadores.",
  menu_game_area = "Áreas do Jogo",
  menu_game_area_desc = "Quais partes do jogo são acessíveis. Use \"Padrão\" para todos os níveis.",
  menu_nerf_vanish_desc = "Nerfa a Boina Metálica tornando-a vulnerável ao modo JvJ, A não ser que um botão seja pressionado.",
  menu_no_player_col = "Desligar Colisão Entre Jogadores",
  menu_no_player_col_desc = "Prevenir que os jogadores pulem ou empurrem uns aos outros na partida. JvJ ainda funciona!",
  menu_no_water_heal = "A Água Não Se Recupera", -- is this correct?
  menu_old_input = "Comandos de Seta Antigos",
  menu_old_input_desc = "Altera os comandos de seta para a forma como eles eram na pré-v2.8.",
  menu_pvp_type = "Modo Jogador vs. Jogador",
  menu_pvp_type_desc = "Muda a forma como o JvJ funciona (mesma configuração do servidor). \"Revamped\" aprimora os saltos de parede e permite combos de soco, entre outros.",
  menu_settings_player = "Preferências",
  preset_cant_delete = "Não é possível deletar essa configuração!",
  preset_deleted = "Configuração \"%s\" deletada.",
  preset_desc = "[SALVAR|CARREGAR|DELETAR|RENOMEAR] - Manage custom setting presets.",
  preset_not_saved = "This preset must be saved before you can rename it.",
  preset_save = "Salvar Configuração Atual",
  preset_saved = "Configuração salva como \"%s\". Para renomear, use /mh preset rename [nome novo]",
  pvp_type_classic = "Clássico",
  pvp_type_revamped = "Refeito",
  vanish_custom = "Segure \\#ffff5a\\%s\\#ffffff\\ para desviar de ataques JvJ!",

  ["debug_set-fov_desc"] = "[NUM] - Modifica o campo de visão; deixe em branco para resetar.", -- I accidently added a dev command to be translated, oops
}