langdata["fr"] = -- By Skeltan
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "French",

  -- name in the built-in menu
  name_menu = "Français",

  -- global command info
  to_switch = "Faites \"/lang %s\" pour changer de langue",
  switched = "La langue a été changée en français !", -- Replace "English" with the name of this language
  rule_command = "Faites /rules pour faire apparaître ce message de nouveau",

  -- roles
  runner = "Coureur",
  runners = "Coureurs",
  short_runner = "Cours", -- unused
  hunters = "Chasseurs",
  hunter = "Chasseur",
  spectator = "Spectateur",
  player = "Joueur",
  players = "Joueurs",
  all = "Tous",

  -- rules
  --[[
    This is laid out as follows:
    {welcome}
    {runners}{shown_above|thats_you}{any_bowser|collect_bowser}
    {hunters}{thats_you}{all_runners|any_runners}
    {rule_lives_one|rule_lives}{time_needed|stars_needed}{become_hunter|become_runner}
    {infinite_lives}{spectate}
    {banned_glitchless|banned_general}{fun}

    I highly recommend testing this in-game
    Also:
    \\#ffffff\\ = white (default)
    \\#00ffff\\ = cyan (for Runner team name)
    \\#ff5a5a\\ = red (for Hunter team name and popups)
    \\#ffff5a\\ = yellow
    \\#5aff5a\\ = green
    \\#b45aff\\ = purple (for Extreme Mode)
  ]]
  welcome = "Bienvenue dans \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ ! COMMENT JOUER:",
  welcome_mini = "Bienvenue dans \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\ ! COMMENT JOUER:",
  welcome_mys = "Bienvenue dans \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\ ! COMMENT JOUER:",
  welcome_egg = "Bienvenue dans \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ ! COMMENT JOUER:",
  all_runners = "Éliminez tous les \\#00ffff\\Coureurs\\#ffffff\\.",
  any_runners = "Éliminez n'importe quel \\#00ffff\\Coureur\\#ffffff\\.",
  shown_above = "(montré çi-dessus)",
  any_bowser = "Battez %s par \\#ffff5a\\tous les moyens nécessaires.\\#ffffff\\",
  collect_bowser = "Collectez \\#ffff5a\\%d étoile(s)\\#ffffff\\ et battez %s.",
  mini_collect = "Soyez le premier à \\#ffff5a\\obtenir l'étoile\\#ffffff\\.",
  collect_only = "Collectez \\#ffff5a\\%d étoile(s)\\#ffffff\\.",
  thats_you = "(c'est vous !)",
  banned_glitchless =
  "INTERDICTION DE: Faire des Alliances, faire des BLJs, passer à travers les murs, freiner l'avancée du jeu, camper.",
  banned_general = "INTERDICTION DE: Faire des Alliances, freiner l'avancée du jeu, camper.",
  time_needed = "%d:%02d pour sortir de n'importe quel niveau; collectez des étoiles pour réduire le compte à rebours",
  stars_needed = "%d étoile(s) pour sortir de n'importe quel niveau",
  become_hunter = "devenez \\#ff5a5a\\Chasseurs\\#ffffff\\ une fois vaincu",
  become_runner = "éliminez un \\#00ffff\\Coureur\\#ffffff\\ pour en devenir un",
  infinite_lives = "Vies Illimités",
  spectate = "faites \"/spectate\" pour devenir spectateur",
  mini_goal = "\\#ffff5a\\Celui qui collecte le plus d'étoiles en %d:%02d gagne !\\#ffffff\\",
  fun = "Amusez-vous bien !",

  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ ont gagné!", -- team name is placed here
  can_leave = "\\#5aff5a\\Peut sortir du niveau",
  cant_leave = "\\#ff5a5a\\Ne peut pas sortir du niveau",
  time_left = "Peut sortir dans \\#ffff5a\\%d:%02d",
  stars_left = "\\#ffff5a\\%d étoile(s)\\#ffffff\\ nécessaires pour sortir",
  in_castle = "Dans le château",
  until_hunters = "%d seconde(s) avant que les \\#ff5a5a\\Chasseurs\\#ffffff\\ commencent",
  until_runners = "%d seconde(s) avant que les \\#00ffff\\Coureurs\\#ffffff\\ commencent",
  lives_one = "1 vie",
  lives = "%d vies",
  stars_one = "1 étoile",
  stars = "%d étoiles",
  no_runners = "Pas de \\#00ffff\\Coureurs !",
  camp_timer = "Restez en mouvement ! \\#ff5a5a\\(%d)",
  game_over = "La partie est terminée !",
  winners = "Gagnants: ",
  no_winners = "\\#ff5a5a\\Pas de gagnants !",
  death_timer = "Mort",
  on = "\\#5aff5a\\ACTIVÉ",
  off = "\\#ff5a5a\\DÉSACTIVÉ",
  frozen = "Gelé pour %d",

  -- popups
  lost_life = "%s\\#ffa0a0\\ a perdu une vie !",
  lost_all = "%s\\#ffa0a0\\ a perdu toute ses vies !",
  now_role = "%s\\#ffa0a0\\ est désormais un %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ a obtenu une étoile !",
  got_key = "%s\\#ffa0a0\\ a obtenu une clé!",
  rejoin_start = "%s\\#ffa0a0\\ a 2 minutes pour se reconnecter.",
  rejoin_success = "%s\\#ffa0a0\\ est revenu à temps !",
  rejoin_fail = "%s\\#ffa0a0\\ ne s'est pas reconnecté à temps.",
  using_ee = "Ceci utilise le mode extrême uniquement.",
  not_using_ee = "Ceci utilise le mode standard uniquement.",
  killed = "%s\\#ffa0a0\\ a tué %s !",
  sidelined = "%s\\#ffa0a0\\ a vaincu %s !",
  paused = "Vous avez été mis en pause.",
  unpaused = "Vous n'êtes plus en pause.",
  kill_combo_2 = "%s\\#ffa0a0\\ a tué \\#ffff5a\\deux\\#ffa0a0\\ personnes à la suite !",
  kill_combo_3 = "%s\\#ffa0a0\\ a tué \\#ffff5a\\trois\\#ffa0a0\\ personnes à la suite !",
  kill_combo_4 = "%s\\#ffa0a0\\ a tué \\#ffff5a\\quatre\\#ffa0a0\\ personnes à la suite !",
  kill_combo_5 = "%s\\#ffa0a0\\ a tué \\#ffff5a\\cinq\\#ffa0a0\\ personnes à la suite !",
  kill_combo_large = "\\#ffa0a0\\Wow ! %s\\#ffa0a0\\ a tué \\#ffff5a\\%d\\#ffa0a0\\ personnes à la suite !",
  set_hack = "Rom-Hack définie sur %s",
  incompatible_hack = "ATTENTION: Rom-Hack incompatible !",
  vanilla = "Utilisation du jeu Vanilla",
  omm_detected = "OMM Rebirth a été détecté!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth est obsolète !\\#ffffff\\\nVersion Minimum: %s\nVotre version: %s",
  warp_spam = "Doucement avec les téléportations !",
  no_valid_star = "Impossible de trouver une étoile valide !",
  custom_enter = "%s\\#ffffff\\ est entré dans\n%s",                           -- same as coop
  demon_unlock = "Mode Green Demon débloqué!",
  hit_switch_red = "%s\\#ffa0a0\\ a activé le\n\\#df5050\\Bouton Rouge !",      -- dark red (unique)
  hit_switch_green = "%s\\#ffa0a0\\ a activé le\n\\#50b05a\\Bouton Vert !",     -- dark green (unique)
  hit_switch_blue = "%s\\#ffa0a0\\ a activé le\n\\#5050e3\\Bouton Bleu !",      -- dark blue (unique)
  hit_switch_yellow = "%s\\#ffa0a0\\ a activé le\n\\#e3b050\\Bouton Jaune...", -- orangeish (unique)
  connected = "%s\\#ffff5a\\ s'est connecté!",                                 -- same as coop
  disconnected = "%s\\#ffa0a0\\ s'est déconnecté",                             -- same as coop

  -- command feedback
  not_mod = "Vous n'avez pas la permission d'utiliser cette commande, pauvre fou !",
  no_such_player = "Ce joueur n'existe pas",
  bad_id = "ID de joueur invalide !",
  command_disabled = "Cette commande est désactivée.",
  change_setting = "Paramètre changé:",
  you_are_muted = "Vous êtes muet.",

  -- more command feedback
  bad_param = "Paramètres Invalides !",
  bad_command = "Commande Invalide !",
  error_no_runners = "Impossible de commencer avec 0 Coureur !",
  set_team = "L'équipe de %s a été défini sur '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "La partie n'a pas encore commencé",
  set_lives_one = "%s à désormais 1 vie",
  set_lives = "%s à désormais %d vies",
  not_runner = "%s n'est pas un Coureur",
  may_leave = "%s est autorisé à sortir",
  must_have_one = "Il faut au moins 1 Chasseur",
  added = "Coureurs ajoutés: ", -- list comes afterward
  runners_are = "Les Coureurs sont: ",
  set_lives_total = "Nombre de vies de Coureur défini à %d",
  wrong_mode = "Indisponible dans ce mode",
  need_time_feedback = "Les Coureurs peuvent désormais sortir après %d seconde(s)",
  game_time = "La partie dure désoarmais %d seconde(s)",
  need_stars_feedback = "Les Coureurs ont désormais besoin de %d étoile(s)",
  new_category = "Il s'agit désormais d'un speedrun %d étoile(s)",
  new_category_any = "Il s'agit désormais d'un speedrun Any%",
  mode_normal = "En mode Normal",
  mode_swap = "En mode Inversion de Rôles",
  mode_mini = "En mode MiniHunt",
  mode_mys = "En mode MysteryHunt",
  using_stars = "Mode: Étoiles Ramassées",
  using_timer = "Mode: Compte à Rebours",
  can_spectate = "Les Chasseurs peuvent désormais être spectateurs",
  no_spectate = "Les Chasseurs ne peuvent plus être spectateurs",
  all_paused = "Tous les joueurs ont été mit en pause",
  all_unpaused = "Tous les joueurs ne sont plus en pause",
  player_paused = "%s a été mit en pause",
  player_unpaused = "%s n'est plus en pause",
  hunter_metal = "Tous les Chasseurs sont en métal",
  hunter_normal = "Tous les Chasseurs apparaissent normalement",
  hunter_glow = "Tous les Chasseurs brillent en rouge",
  runner_normal = "Tous les Coureurs apparaissent normalement",
  now_weak = "Tous les joueurs n'ont plus que la moitié de leurs frames d'invincibilité",
  not_weak = "Tous les joueurs ont leurs frames d'invincibilité par défaut",
  auto_on = "La partie commencera automatiquement",
  auto_off = "La partie ne commencera pas automatiquement",
  force_spectate = "Tous le monde doit être spectateur",
  force_spectate_off = "Le mode spectateur n'est désormais plus forcé",
  force_spectate_one = "%s doit être en mode spectateur",
  force_spectate_one_off = "%s n'est plus obligé d'être en mode spectateur",
  blacklist_add = "%s ajouté à la liste noire",
  blacklist_remove = "%s ajouté à la liste blanche",
  blacklist_add_already = "Cette étoile ou ce niveau est déjà sur la liste noire.",
  blacklist_remove_already = "Cette étoile ou ce niveau n'est pas sur la liste noire.",
  blacklist_remove_invalid = "Impossible d'ajouter cette étoile ou ce niveau sur la liste blanche.",
  blacklist_list = "Liste Noire:",
  blacklist_reset = "Réinitialise la liste noire !",
  blacklist_save = "Liste noire sauvegardée !",
  blacklist_load = "Liste noire chargée !",

  -- team chat
  tc_toggle = "Le tchat d'équipe est %s !",
  to_team = "\\#8a8a8a\\Pour ton équipe: ",
  from_team = "\\#8a8a8a\\ (équipe): ",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ a voté pour passer cette étoile",
  vote_info = "Tapez /skip dans le tchat pour voter",
  vote_pass = "Le vote est passé!",
  already_voted = "Vous avez déja voté.",

  -- hard mode
  hard_notice = "Psst, essaye de faire /hard dans le tchat...",
  extreme_notice = "Psst, essaye de faire /hard ex dans le tchat...",
  hard_toggle = "Le \\#ff5a5a\\Mode Difficile\\#ffffff\\ est %s !",
  extreme_toggle = "Le \\#b45aff\\Mode Extrême\\#ffffff\\ est %s !",
  "\n- 2x moins de vie" ..
  "\n- L'eau ne regénère pas la vie" ..
  "\n- \\#ff5a5a\\Une Seule Vie" ..
  "\n\\#ffffff\\Tapez /hard ON dans le tchat si vous êtes prêt à relever le défi.",
  extreme_info = "Êtes-vous attirez par le \\#b45aff\\Mode Extrême\\#ffffff\\ ? Quelle folie." ..
      "\n- Une Seule Vie" ..
      "\n- Un unique Point de Vie" ..
      "\n- \\#b45aff\\Compte à Rebourd Mortel\\#ffffff\\; ramassez des pièces ou des étoiles pour l'augmenter" ..
      "\nSi cela ne vous fait pas peur, alors tapez /hard ex ON dans le tchat.",
  no_hard_win = "Vos Victoires Difficiles ou Extrêmes ne seront pas sauvegardés pour cette partie.",
  hard_mode = "Mode Difficile",
  extreme_mode = "Mode Extrême",
  hard_info_short = "2x moins de PV, l'eau ne régen pas, et une seule vie.",
  extreme_info_short = "Un seul PV, une seule vie, et compte à rebours mortel.",

  -- spectator
  hunters_only = "Seuls les Chasseurs peuvent être spectateurs !",
  spectate_disabled = "Le mode spectateur est désactivé!",
  timer_going = "Vous ne pouvez pas être spectateur durant le compte à rebours !", -- now unused
  spectate_self = "Vous ne pouvez être votre propre spectateur !",
  spectator_controls = "Contrôles:" ..
      "\nDPAD-UP: Désactiver le HUD" ..
      "\nDPAD-DOWN: Alterner Caméra Libre/Suivre Joueur" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Changer de joueur" ..
      "\nJOYSTICK: Se déplacer" ..
      "\nA: Aller vers le haut" ..
      "\nZ: Aller vers le bas" ..
      "\nFaites \"/spectate OFF\" pour annuler",
  spectate_off = "Vous n'êtes plus en mode spectateur.",
  empty = "Vide (%d )",
  free_camera = "CAMÉRA LIBRE",
  spectate_mode = "- MODE SPECTATEUR -",
  is_spectator = "* LE JOUEUR EST SPECTATEUR *",

  -- stats
  disp_wins_one = "%s\\#ffffff\\ a gagné 1 fois en tant que \\#00ffff\\Coureur\\#ffffff\\ !",
  disp_wins = "%s\\#ffffff\\ a gagné %d fois en tant que \\#00ffff\\Coureur\\#ffffff\\ !",
  disp_kills_one = "%s\\#ffffff\\ a tué 1 joueur !", -- unused
  disp_kills = "%s\\#ffffff\\ a tué %d joueurs !",
  disp_wins_hard_one =
  "%s\\#ffffff\\ a gagné 1 fois en tant que \\#ffff5a\\Coureur\\#ffffff\\ en \\#ff5a5a\\Mode Difficile !\\#ffffff\\",
  disp_wins_hard =
  "%s\\#ffffff\\ a gagné %d fois en tant que \\#ffff5a\\Coureur\\#ffffff\\ en \\#ff5a5a\\Mode Difficile !\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ a gagné 1 fois en tant que \\#b45aff\\Coureur\\#ffffff\\ en \\#b45aff\\Mode Extrême !\\#ffffff\\",
  disp_wins_ex =
  "%s\\#ffffff\\ a gagné %d fois en tant que \\#b45aff\\Coureur\\#ffffff\\ en \\#b45aff\\Mode Extrême !\\#ffffff\\",
  -- for stats table
  stat_wins_standard = "Victoires",
  stat_wins = "Victoires (Minihunt/pré v2.3)",
  stat_wins_mys = "Victoires (MysteryHunt)",
  stat_kills = "Kills",
  stat_combo = "Record de Kills",
  stat_wins_hard_standard = "Victoires (Mode Difficile)",
  stat_wins_hard = "Victoires (Mode Difficile, Minihunt/pré v2.3)",
  stat_wins_hard_mys = "Victoires (Mode Difficile, MysteryHunt)",
  stat_mini_stars = "Maximum d'étoiles en une partie de MiniHunt",
  stat_placement = "Placement du 64 Tour",
  stat_wins_ex_standard = "Victoires (Mode Extrême)",
  stat_wins_ex = "Victoires (Mode Extrême, Minihunt/pré v2.3)",
  stat_wins_ex_mys = "Victoires (Mode Extrême, MysteryHunt)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1ère Place]",
  place_2 = "\\#c5d8de\\[64T: 2ème Place]",
  place_3 = "\\#b38752\\[64T: 3ème Place]",
  place = "\\#e7a1ff\\[64T: %dème Place]", -- thankfully we don't go up to 21
  place_score_1 = "%dère",
  place_score_2 = "%dème",
  place_score_3 = "%dème",
  place_score = "%dème",

  -- chat roles
  role_lead = "\\#9a96ff\\[Dev Principal MH]",
  role_dev = "\\#96ecff\\[Dev MH]",
  role_cont = "\\#ff9696\\[Contributeur MH]",
  role_trans = "\\#ffd996\\[Traducteur MH]",

  -- command descriptions
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Lancez la partie; ajoutez \"continue\" pour ne pas être téléporté au début; ajoutez \"alt\" pour utiliser la sauvegarde alternative; ajoutez \"main\" pour utiliser la sauvegarde principale; ajoutez \"reset\" pour effacer la sauvegarde",
  add_desc = "[INT] - Ajoute aléatoirement le nombre indiqué de Coureur",
  random_desc = "[INT] - Sélectionne aléatoirement les Coureurs selon le nombre indiqué",
  random_desc_hunt = "[INT] - Sélectionne aléatoirement les Chasseurs selon le nombre indiqué",
  lives_desc =
  "[INT] - Défini le nombre de vies que les Coureurs ont, de 0 à 99 (note: 0 vies équivaut toujours à 1 vie)",
  time_desc = "[NUM] - Défini le temps que les Coureurs doivent attendre pour sortir, en secondes",
  stars_desc =
  "[INT] - Défini le nombre d'étoiles que les Coureurs doivent ramasser pour sortir, de 0 à 7 (seulement en mode Étoiles Ramassées)",
  category_desc = "[INT] - Défini le nombre d'étoiles que les Coureurs doivent ramasser pour faire face à Bowser.",
  flip_desc = "[NAME|ID] - Inverse l'équipe du joueur spécifié",
  setlife_desc = "[NAME|ID|INT,INT] - Défini le nombre de vies spécifié pour le Coureur spécifié",
  leave_desc = "[NAME|ID] - Autorise le joueur spécifié à sortir du niveau si il est Coureur",
  mode_desc =
  "[NORMAL|SWAP|MINI] - Change le mode de jeu; swap inverse le rôle du Coureur mort avec celui du Chasseur qui l'a tué",
  starmode_desc = "[ON|OFF] - Active le Mode Étoiles Ramassées à la place du Mode Compte à Rebours",
  spectator_desc = "[ON|OFF] - Active la capacité des Chasseurs à devenir spectateurs",
  pause_desc = "[NAME|ID|ALL] - Met en pause le joueur spécifié, ou tous les joueurs si rien n'est spécifié",
  hunter_app_desc = "Change l'apparence des Chasseurs.",
  runner_app_desc = "Change l'apparence des Coureurs.",
  hack_desc = "[STRING] - Défini la Rom-Hack actuelle",
  weak_desc = "[ON|OFF] - Divise les frames d'invincibilités par 2 pour tous les joueurs",
  auto_desc = "[ON|OFF|NUM] - Lance la partie automatiquement",
  forcespectate_desc = "[NAME|ID|ALL] - Force le mode specatateur pour ce joueur ou tous les joueurs",
  desync_desc = "- Essaye de régler les erreurs de désyncronisation",
  stop_desc = "- Arrête la partie",
  default_desc = "- Défini les paramètres à ceux par défaut",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Ajoute des étoiles à la liste noire pour MiniHunt",
  stalking_desc = "[ON|OFF] - Autorise la téléportation dans le niveau d'un Coureur avec /stalk",

  -- Blocky's menu
  main_menu = "Menu Principal",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  --menu_settings_player = "Paramètres",
  menu_rules = "Règles",
  menu_lang = "Langue",
  menu_misc = "Autres",
  menu_stats = "Statistiques",
  menu_back = "Retour",
  menu_exit = "Fermer",

  menu_run_random = "Séléction Aléatoire des Coureurs",
  menu_run_add = "Ajouter des Coureurs",
  menu_hunt_random = "Séléction Aléatoire des Chasseurs",
  menu_run_lives = "Vies des Coureurs",
  menu_settings = "Paramètres de la Partie",

  menu_start = "Démarrer",
  menu_stop = "Arrêter",
  menu_save_main = "Suavegarde Principale",
  menu_save_alt = "Sauvegarde Alternative",
  menu_save_reset = "Effacer Sauvegarde Alternative",
  menu_save_continue = "Continuer (sans téléportation au départ)",
  menu_random = "Aléatoire",
  menu_campaign = "Campagne",

  menu_gamemode = "Mode de Jeu",
  menu_hunter_app = "Apparence des Chasseurs",
  menu_runner_app = "Apparence des Coureurs",
  menu_weak = "Mode Faible",
  menu_allow_spectate = "Autoriser le mode Spectateur",
  menu_star_mode = "Mode Étoiles Ramassées",
  menu_category = "Catégorie",
  menu_time = "Temps",
  menu_stars = "Étoiles",
  menu_auto = "Partie Auto",
  menu_blacklist = "Liste Noire MiniHunt",
  menu_default = "Réinitialiser par défaut",
  menu_defeat_bowser = "Battez %s",
  menu_allow_stalk = "Autoriser le 'Stalking'",
  menu_countdown = "Compte à rebours",
  menu_countdown_desc = "Combien de temps les Chasseurs doivent attendre",
  menu_voidDmg = "Dégâts du vide",
  menu_voidDmg_desc = "Dégâts infligés aux joueurs tombant dans le vide ou les sables mouvants.",
  menu_double_health = "Doubler la vie",
  menu_double_health_desc = "Les joueurs ont 16 points de vie au lieu de 8.",

  menu_flip = "Inverser l'équipe",
  menu_spectate = "Passer en Mode Spectateur",
  menu_stalk = "Se téléporter au niveau",
  menu_stalk_desc = "Vous téléporte dans le niveau de ce joueur.",
  menu_pause = "Mettre en Pause",
  menu_forcespectate = "Forcer le Mode Spectateur",
  menu_allowleave = "Autoriser à sortir",
  menu_setlife = "Définir les vies",
  menu_players_all = "Tous les Joueurs",
  menu_target = "Mettre en tant que cible",
  menu_mute = "Muter",

  menu_timer = "Chronomètre de Speedrun",
  menu_timer_desc = "[ON|OFF] - Affiche un chronomètre en bas de l'écran dans les modes Standards.",
  menu_tc = "Tchat d'Équipe",
  menu_tc_desc = "Discutez seulement avec votre équipe.",
  menu_demon = "Green Demon", -- referring to the 1-Up
  menu_demon_desc = "Un 1-Up mortel vous poursuit en tant que Coureur.",
  menu_unknown = "???",
  menu_secret = "C'est un secret. Comment l'avez vous débloqué?",
  menu_hide_roles = "Cacher mes Rôles",
  menu_hide_roles_desc = "Cache vos rôles dans le tchat.",
  menu_hide_hud = "Cacher le HUD",
  hidehud_desc = "- Cache tous les éléments du HUD.",
  menu_season = "Changements Saisonniers",
  menu_season_desc = "Changements visuels amusants en fonction de la date.",

  menu_free_cam_desc = "Entrer en Caméra Libre en mode Spectateur.",
  menu_spectate_run = "Regarder le Coureur",
  menu_spectate_run_desc = "Regarde automatiquement le premier Coureur.",
  menu_exit_spectate = "Sortir du mode Spectateur",
  menu_exit_spectate_desc = "Vous fait sortir du mode spectateur.",
  menu_stalk_run = "Se téléporter au niveau du Coureur",
  menu_stalk_run_desc = "Vous téléporte dans le niveau dans lequel le 1er Coureur se situe.",
  menu_skip = "Passer",
  menu_skip_desc = "- Vote pour passer cette étoile en mode MiniHunt.",

  menu_spectate_desc = "Regarder ce joueur.",

  menu_blacklist_list = "Afficher Liste Noire",
  menu_blacklist_list_desc = "Liste la liste noire des étoiles en MiniHunt pour ce serveur.",
  menu_blacklist_save = "Sauvegarder la liste noire",
  menu_blacklist_save_desc = "Sauvegarde la liste noire pour les prochaines fois.",
  menu_blacklist_load = "Charger la liste noire",
  menu_blacklist_load_desc = "Charge la liste noire que vous avez sauvegardé.",
  menu_blacklist_reset = "Réinitialiser la liste noire",
  menu_blacklist_reset_desc = "Réinitialise la liste noire par celle par défaut.",
  menu_toggle_all = "Tout activer",

  -- unorganized
  lang_desc = "%s - Changer de langue",
  got_all_stars = "Vous avez assez d'étoiles !",
  spectate_desc =
  "[NAME|ID|OFF] - Devenez spectateur du joueur spécifié, en caméra libre si rien n'est spécifié ou désactivée si OFF est spécifié",
  tc_desc =
  "[ON|OFF|MSG] - Envoie les messages seulement à votre équipe; spécifiez ON pour l'appliquer à tous les messages",
  stars_in_area = "%d étoile(s) disponible(s) ici !",
  hard_info = "Intéressé par le \\#ff5a5a\\Mode Difficile \\#ffffff\\?\
  - 2x moins de PV\
  - L'eau ne régen pas\
  - \\#ff5a5a\\Une seule vie\
  \\#ffffff\\Tapez /hard ON dans le tchat si vous êtes prêt à relever le défi.",
  menu_first_timer = "Timer de mort pour le Leader",
  menu_popup_sound = "Sons de popups",
  stalk_desc = "[NAME|ID] - Vous téléporte dans le niveau du joueur spécifié, ou du premier Coureur",
  open_menu = "Tapez /mh ou appuyez sur %s pour ouvrir le menu",
  menu_nerf_vanish = "Nerf la casquette d'invisibilité",
  stalk = "Utilisez /stalk pour vous téléporter aux Coureurs !",
  menu_fast = "Actions plus rapides",
  new_record = "\\#ffff5a\\NOUVEAU RECORD !!!",
  anarchy_set_2 = "Les Chasseurs peuvent attaquer leurs coéquipiers",
  no_runners_added = "Aucun Coureur n'a été ajouté",
  menu_first_timer_desc = "Donne au leader un timer de mort dans Minihunt.",
  menu_nerf_vanish_desc =
  "Nerf la casquette d'invisibilité en la rendant commutable et en réduisant sa durée d'utilisation.",
  unstuck = "Tentative de réparer l'État",
  use_out = "Faites /mh out pour faire sortir tout le monde de ce niveau",
  menu_list_settings = "Paramètre des Listes",
  anarchy_set_3 = "Les joueurs peuvent attaquer leurs coéquipiers",
  menu_fast_desc = "Vous allez régénerer votre vie, lancer des objets et ouvrir les portes plus rapidement.",
  dmgAdd_set = "Les Coureurs font maintenant prendre %d de dégats supplémentaires lors du PVP.",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Active le mode difficile pour vous-même",
  menu_dmgAdd = "Coureur Dégâts PVP +",
  menu_anarchy_desc = "Permet aux équipes spécifiées d'attaquer leurs coéquipiers.",
  rules_desc = "- Affiche les règles de MarioHunt",
  rules_desc_egg = "- Affiche les règles de LuigiHunt",
  menu_anarchy = "Dégâts alliés",
  mh_desc = "[COMMAND,ARGS] - Exécute des commandes; Tapez rien ou \"menu\" pour ouvrir le menu",
  ---- vanish_custom = "Maintenez \\#ffff5a\\%s\\#ffffff\\ pour devenir invisible !",
  menu_list_settings_desc = "Liste tous les paramètres pour ce lobby.",
  page = "\\#ffff5a\\Page %d/%d", -- no translation needed for this one
  anarchy_set_1 = "Les Coureurs peuvent attaquer leurs coéquipiers",
  anarchy_set_0 = "Les joueurs ne peuvent pas attaquer leurs coéquipiers",
  menu_dmgAdd_desc = "Ajoute cette quantité de dégâts supplémentaires aux attaques contre les Coureurs.",
  mini_score = "Score: %d", -- no translation needed for this one
  stats_desc = "- Afficher/Cacher la liste des stats",
  target_desc = "[NAME|ID] - Défini ce Coureur en tant que cible, ce qui affiche sa position tout le temps.",
  hunter_outline = "Tous les Chasseurs ont un contour",
  runner_sparkle = "Tous les Coureurs scintillent",
  runner_glow = "Tous les Coureurs brillent",
  runner_outline = "Tous les Coureurs ont un contour",
  dmgAdd_set_ohko = "Les Coureurs mourront en un coup",
  voidDmg_set = "Les joueurs prendront %d dégâts s'ils tombent dans le vide ou les sables mouvants.",
  voidDmg_set_ohko = "Les joueurs mourront instantanément s'ils tombent dans le vide ou les sables mouvants.",
  target_hunters_only = "Seuls les Chasseurs peuvent mettre une cible.",

  -- mute
  muted = "\\#ffff00\\%s\\#ffffff\\ a été rendu muet par \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ a retrouvé la parole grâce à \\#ffff00\\%s\\#ffffff\\.",
  you_muted = "Vous avez rendu muet \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Vous avez redonné la parole à \\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ a été rendu muet automatiquement.",

  mute_desc = "[NAME|ID] - Rend muet un joueur, les empêchant de parler",
  unmute_desc = "[NAME|ID] - Rétablit la parole d'un joueur",
  out_desc = "[LEVEL|COURSE] - Fait sortir tout le monde du niveau",

  -- updater
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ est à jour !",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ est à jour !",
  has_update = "Une mise à jour est disponible pour \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ !",
  has_update_egg = "Une mise à jour est disponible pour \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ !",

  -- version 2.6 stuff I don't feel like sorting
  leave_error = "%s\\#ffa0a0\\ est parti à cause d'une erreur.",
  hunter_color = "Tous les chasseurs ont la palette Bordeaux",
  runner_color = "Tous les coureurs ont la palette Azur",
  stat_playtime = "Temps de jeu (Heures)",
  stat_parkour_time = "Meilleur Temps Parcours",
  stat_parkour_time_omm = "Meilleur Temps Parcours (OMM)",
  stat_parkour_time_other = "Meilleur Temps Parcours (Moveset)",
  menu_free_roam = "Accès Libre",
  menu_free_roam_desc = "Désactive le nombre d'étoile nécessaire pour accéder à la plupart des niveaux et ouvre toutes les portes à clés.",
  menu_radar = "Radar",
  menu_radar_desc = "Affiche à l'écran l'emplacement des Coureurs et des objets importants.",
  menu_minimap = "Minimap",
  menu_minimap_desc = "Affiche la carte de tout le niveau.",
  menu_romhack_cam = "Romhack Cam",
  menu_romhack_cam_desc = "Active la Romhack Cam partout.",
  menu_star_heal = "Soin Étoile",

  -- v2.6.1
  menu_star_setting = "Obtention d'étoile", -- from base
  star_leave = "Sortir",
  star_stay = "Rester",
  star_nonstop = "Non-Stop",

  -- v2.7
  added_count = "Ajouté %d coureurs",
  added_count_one = "Ajouté 1 coureur",
  become_spectator = "devient un \\#a9a9a9\\Spectateur\\#ffffff\\ une fois vaincu",
  dead = "Mort",
  dead_become = "Les \\#00ffff\\coureurs morts\\#ffffff\\ laissent derrière eux un corps.",
  dead_become_infection = "Les joueurs morts qui ne deviennent pas \\#ff5a5a\\chasseurs\\#ffffff\\ laissent derrière eux un corps.",
  dead_become_noconfirm = "Les joueurs morts laissent derrière eux un corps.",
  disp_asn_bronze = "%s\\#ffffff\\ a obtenu la médaille de \\#b38752\\bronze\\#ffffff\\ lors du tournoi ASN !",
  disp_asn_quarter = "%s\\#ffffff\\ a atteint les \\#70ff94\\quarts de finale\\#ffffff\\ lors du tournoi ASN !",
  disp_asn_silver = "%s\\#ffffff\\ a obtenu la médaille d'\\#c5d8de\\argent\\#ffffff\\ lors du tournoi ASN !",
  disp_asn_win = "%s \\#e3bc2d\\a gagné\\#ffffff\\ le tournoi ASN !",
  far = "\\#8a8a8a\\(loin)",
  global_talk_end = "\\#ffa0a0\\Le chat global est terminé.",
  global_talk_start = "\\#ffa0a0\\Le chat global est activé pour %d seconde(s).",
  guard_cooldown = "Peut protéger dans %d",
  guard_info = "Appuyez sur %s pour protéger %s",
  guard_info_rules = "Les joueurs morts peuvent protéger leurs coéquipiers avec %s.",
  guard_save = "\\#ffff00\\Un fantôme vous a sauvé de la mort !",
  guard_timer = "%s\\#ffff00\\ est protégé (%d)",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\chasseurs\\#ffa0a0\\ restants.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\chasseur\\#ffa0a0\\ restant.",
  players_remain = "\\#ffa0a0\\%d joueurs restants.",
  players_remain_one = "\\#ffa0a0\\1 joueur restant.",
  hunters_set_count = "Il y a %d chasseurs",
  hunters_set_count_one = "Il y a 1 chasseur",
  hunters_were = "Les chasseurs étaient : ",
  keep_secret = "Ne vous faites pas attraper !",
  menu_binds = "Modifier les touches",
  menu_binds_desc = "Modifier les boutons utilisés pour différentes actions.",
  menu_confirm_hunter = "Confirmer la mort des chasseurs",
  menu_confirm_hunter_desc = "Affiche un message chaque fois qu’un chasseur est tué. Si désactivé, les chasseurs laissent également des corps derrière eux.",
  menu_coop = "Coop",
  menu_global_chat = "Temps de chat global",
  menu_global_chat_desc = "Temps pendant lequel les joueurs peuvent parler lorsqu’un corps est trouvé.",
  menu_grace_period = "Période de grâce",
  menu_grace_period_desc = "Temps avant que les joueurs puissent être tués.",
  menu_guard_button = "Protéger",
  menu_guard_button_desc = "Bouton pour protéger un joueur en mode spectateur dans MysteryHunt.",
  menu_hunters_win_early = "Victoire anticipée des Chasseurs",
  menu_hunters_win_early_desc = "Les chasseurs gagnent lorsqu’ils égalent ou dépassent le nombre de coureurs, comme dans Among Us.",
  menu_invinc_particle = "Étincelles I-Frames",
  menu_invinc_particle_desc = "Remplace l’effet \"clignotant\" lorsque Mario prend des dégâts par des particules scintillantes.",
  menu_know_team = "Chasseurs connaissent leurs coéquipiers",
  menu_know_team_desc = "Les chasseurs savent qui sont leurs coéquipiers. Si désactivé, les chasseurs peuvent également s’entre-tuer.",
  menu_menu_button = "Ouvrir le menu",
  menu_menu_button_desc = "Bouton(s) pour ouvrir le menu MarioHunt.",
  menu_overlay = "Affichage de l'avancement des niveaux",
  menu_overlay_desc = "Affiche les étoiles, clés et interrupteurs de casquette collectés près du tableau ou du téléporteur d’un niveau.",
  menu_presets = "Préréglages",
  menu_report_button = "Signaler/Réparer",
  menu_report_button_desc = "Bouton utilisé pour signaler des corps et arrêter les sabotages dans MysteryHunt.",
  menu_sabo = "Sabotage",
  menu_sabo_button = "Ouvrir le menu Sabotage",
  menu_sabo_button_desc = "Bouton(s) pour ouvrir le menu Sabotage dans MysteryHunt.",
  menu_show_on_map = "Afficher sur la carte",
  menu_show_on_map_desc = "Équipes visibles sur la mini-carte (les adversaires auront également le radar)",
  menu_shuffle = "Mélanger les équipes",
  menu_shuffle_desc = "Mélange les équipes de chaque joueur vivant après un délai défini",
  menu_spectate_on_death = "Coureurs deviennent spectateur en cas de mort",
  menu_stalk_timer = "Temps de recharge pour traquer",
  menu_stalk_timer_desc = "Temps où le joueur est figé après avoir utilisé /stalk.",
  menu_star_stay_old = "Reste dans le niveau si déjà collectée",
  menu_star_stay_old_desc = "Collecter une étoile déjà collectée ne vous fera pas sortir du niveau.",
  menu_star_timer = "Temps d'obtention de la dernière étoile",
  menu_star_timer_desc = "Montre quand la dernière étoile a été collectée en bas de l'écran.",
  menu_vanish_button = "Devenir invisible",
  menu_vanish_button_desc = "Bouton à maintenir pour activer la casquette d'invisibilité lorsque \"Nerf Vanish Cap\" est actif.",
  mystery_altgoal = "OU : Découvrez les \\#ff5a5a\\chasseurs\\#ffffff\\ et battez-les.",
  mysteryhunt_disabled = "\\#ffa0a0\\L’un de vos mods est incompatible avec MysteryHunt !",
  mysteryhunt_innocent = "\\#ffa0a0\\Vous avez tué un joueur innocent !",
  mysteryhunt_spectate = "\\#ffa0a0\\Vous serez spectateur cette partie.",
  nearby = "\\#8a8a8a\\(proche)",
  no_players_here = "Aucun autre joueur ici !",
  no_runners_here = "Pas de \\#00ffff\\coureurs\\#ffffff\\ ici !",
  opponents = "Adversaires",
  other_hunters = "Les autres chasseurs sont : ",
  place_asn = "\\#e7a1ff\\[Participant ASN]",
  place_asn_1 = "\\#e3bc2d\\[Vainqueur ASN]",
  place_asn_2 = "\\#c5d8de\\[Argent ASN]",
  place_asn_3 = "\\#b38752\\[Bronze ASN]",
  place_asn_4 = "\\#70ff94\\[Quart-finaliste ASN]",
  preset_asn = "Tournoi ASN",
  preset_asn_desc = "Les mêmes paramètres utilisés dans le tournoi ASN (avec 1 vie supplémentaire).",
  preset_classic = "Classique",
  preset_classic_desc = "Modifie les paramètres pour correspondre aux anciennes versions de MarioHunt.",
  preset_infection = "Infection",
  preset_infection_desc = "1 chasseur qui peut éliminer en un coup ! Les coureurs peuvent-ils survivre ?",
  preset_quick = "Partie rapide",
  preset_quick_desc = "30 étoiles, exploration libre, sans affrontement contre Bowser.",
  preset_solo = "Solo",
  preset_solo_desc = "Vous êtes seul ! 3 vies et double énergie.",
  preset_star_rush = "Star Rush",
  preset_star_rush_desc = "Minihunt, mais tout le monde est un coureur !",
  preset_tag = "Tag",
  preset_tag_desc = "Frappez un coureur pour en devenir un instantanément !",
  press_report = "%s - Signaler",
  press_fix = "%s - Réparer",
  report_body = "%s\\#ffa0a0\\ a trouvé le corps de %s\\#ffa0a0\\ dans \\#ffff5a\\",
  report_info_rules = "Appuyez sur %s pour le signaler et discuter.",
  role_dead = "\\#ff2020\\[MORT]",
  runners_can_kill = "\\#00ffff\\Les coureurs\\#ffffff\\ peuvent éliminer les joueurs qu’ils soupçonnent d’être \\#ff5a5a\\chasseurs\\#ffffff\\.\nS’ils tuent un innocent, ils meurent également.",
  runners_remain = "%d \\#00ffff\\coureurs\\#ffffff\\ restants.",
  runners_remain_one = "1 \\#00ffff\\coureur\\#ffffff\\ restant.",
  sabo_activate_timer = "Activation dans %d",
  sabo_active = "\\#ffff00\\SABOTAGE ACTIF !",
  sabo_bomb = "\\#ff4040\\Méga Bombe",
  sabo_bomb_desc = "Tue tous les joueurs si elle n'est pas désactivée !",
  sabo_bomb_timer = "\\#ff4040\\Tout le monde mourra dans %d:%02d",
  sabo_cooldown = "Sabotage possible dans %d:%02d",
  sabo_dark = "\\#5050ff\\Obscurité",
  sabo_dark_desc = "Plonge le monde dans l'obscurité !",
  sabo_gas = "\\#ffff32\\Gaz toxique",
  sabo_gas_desc = "Fait apparaître du gaz toxique !",
  sabo_info = "Appuyez sur %s pour saboter",
  sabo_info_rules = "\\#ff5a5a\\Les chasseurs\\#ffffff\\ peuvent également semer le chaos avec des sabotages.\nPour désactiver un sabotage, allez au niveau indiqué et appuyez sur %s.",
  scroll_up = "Faites défiler vers le haut pour en voir plus...",
  shuffle_timer = "Mélange des équipes dans %d",
  stat_crown = "Couronne ASN",
  stat_placement_asn = "Classement du Tournoi ASN",
  tc_only_hunter = "Seuls les chasseurs en vie peuvent utiliser le chat d'équipe.",
  unless_defeated = "à moins d'être vaincu par un autre joueur",
  unsaved_changes = "\\#ff5a5a\\Vous avez des modifications non sauvegardées ! Appuyez de nouveau si vous êtes sûr.",
  until_grace = "Il reste %d seconde(s) avant la fin de la période de grâce",

  tip = "Astuce : ",
  tip_1 = "Appuyez sur %s, ou tapez /mh, pour ouvrir le menu. Vous pouvez configurer les paramètres ici !",
  tip_2 = "Les attaques rodéos infligent 3 dégâts aux autres joueurs.",
  tip_3 = "Un coup de pied inflige 2 dégâts et projette les joueurs en arrière !",
  tip_4 = "Pour des commandes comme /spectate et /target, vous pouvez entrer des noms partiels et elles fonctionneront (ex : entrer \"Emily\" se référera à EmilyEmmi).",
  tip_5 = "Vous pouvez modifier les paramètres en cours de partie dans le menu.",
  tip_6 = "Si quelque chose ne va pas, tapez /mh pause pour mettre tous les joueurs en pause. Tapez la commande à nouveau pour reprendre.",
  tip_7 = "Quelqu'un spamme ou utilise des insultes ? Utilisez /mh mute pour le rendre muet !",
  tip_8 = "Vous pouvez mettre le jeu en pause avant de récupérer une étoile ou une clé, puis quitter le niveau pour éviter l'animation.",
  tip_9 = "Vous pouvez cibler un coureur avec /target. Cela affichera sa position en haut de l'écran.",
  tip_10 = "Vous pouvez configurer vos paramètres personnels dans le menu (%s).",
  tip_11 = "Pas besoin de redémarrer le serveur ! Sélectionnez \"Réinitialiser sauvegarde alt.\" dans \"Démarrer\" pour réinitialiser tous les progrès.",
  tip_12 = "Vous pouvez obtenir le rôle de coureur en battant un coureur.",
  tip_13 = "Comme dans Mario 64 vanilla, 0 vies compte toujours comme une vie.",
  tip_14 = "Les glitchs majeurs, comme LBLJ, sont inutiles en dehors du Any%.",
  tip_15 = "Les panneaux dans le jeu peuvent contenir des astuces supplémentaires !",
  tip_16 = "Dire Dire Docks peut être entré avec une étoile de moins que la catégorie réelle.",
  tip_17 = "Réglez Cappy sur \"Dégâts\" pour l'utiliser comme arme à distance. Il inflige 1 dégât.",
  tip_18 = "Cappy peut ramasser des objets comme des pièces et des secrets.",
  tip_19 = "Utilisez la croix directionnelle pour lancer Cappy dans différentes directions.",
  tip_20 = "Regardez la vidéo de Key's Artworks sur YouTube pour en apprendre plus sur les techniques d'OMM !",
  tip_21 = "Si des objets dans un niveau commencent à disparaître ou si les téléporteurs cessent de fonctionner, utilisez /mh out dans ce niveau pour forcer le rechargement du niveau.",
  tip_22 = "Utilisez /mh desync si vous pensez qu'une erreur de désynchronisation s'est produite.",
  tip_23 = "Tuer un autre joueur restaure toute votre énergie.",
  tip_24 = "Vous pouvez voir les progrès sur les clés, casquettes et stages secrets dans le menu Pause dans le château.",
  tip_25 = "Les coureurs peuvent se blesser entre eux dans ce mode !",
  tip_26 = "Tomber dans les stages de casquettes compte comme une perte de vie.",
  tip_27 = "Les interrupteurs de pièces bleues réapparaîtront.",
  tip_28 = "Vous pouvez choisir un autre acte pour dérouter les chasseurs.",
  tip_29 = "C'est une fête ! Si vous n'aimez pas les effets, désactivez \"Changements saisonniers\" dans le menu.",
  tip_30 = "Vous pouvez espionner les coureurs avec /spectate.",
  tip_31 = "Utilisez /stalk pour vous téléporter dans un niveau où se trouve un autre coureur !",
  tip_32 = "Apprendre des techniques de speedrun est un bon moyen de s'améliorer au jeu.",
  tip_33 = "Vous pouvez traverser les Whomps en faisant une attaque rodéo ou en donnant un coup de pied lorsqu'ils tombent.",
  tip_34 = "La façon la plus rapide de faire un triple saut est de donner un coup de pied pour le premier saut.",
  tip_35 = "La casquette métal inflige le double de dégâts aux adversaires.",
  --tip_36 = "La casquette d'invisibilité ne s'activera que lorsque vous maintenez %s.",
  tip_37 = "Les minuteurs des casquettes ne diminuent pas dans les canons.",
  tip_38 = "Ne traînez pas trop longtemps sur l'écran de sélection d'acte !",
  tip_39 = "Les plongeons sont rapides, et plonger sur un autre joueur peut vous aider à esquiver des attaques.",
  tip_40 = "Tomber dans le vide infligera des dégâts au lieu de vous tuer instantanément.",
  tip_41 = "Les 1-Up restaurent 4 points d'énergie.",
  tip_42 = "Utilisez le menu Joueurs pour des commandes visant un joueur spécifique, comme changer d'équipe.",
  tip_43 = "Le menu MarioHunt permet de lancer des parties et de configurer les paramètres de jeu.",
  tip_44 = "Vous pouvez cacher votre rôle de chat dans les paramètres.",
  tip_45 = "Les coureurs portant la casquette de métal peuvent toujours être blessés par les chasseurs.",
  tip_46 = "Dans le menu, assurez-vous d'appuyer sur A pour sauvegarder vos paramètres modifiés !",

  -- v2.8
  default = "Par défaut",
  gc_desc = "[MSG] - Envoie un message que tous les joueurs peuvent voir, même si vous êtes mort ; hôte/modérateur uniquement",
  menu_default_role = "Rôle par défaut",
  menu_default_role_desc = "Équipe attribuée aux nouveaux joueurs.",
  menu_game_area = "Zone de jeu",
  menu_game_area_desc = "Parties du jeu accessibles. Utiliser \"Par défaut\" pour tous les niveaux.",
  menu_no_player_col = "Désactiver la collision entre joueurs",
  menu_no_player_col_desc = "Empêche les joueurs de se pousser ou de se bousculer. Le PvP reste actif !",
  menu_no_water_heal = "L'eau Ne Régen Pas", -- is this correct?
  menu_old_input = "Anciens contrôles des flèches du menu",
  menu_old_input_desc = "Change les contrôles de sélection par flèches pour revenir à ceux d'avant v2.8.",
  menu_pvp_type = "Type de PvP",
  menu_pvp_type_desc = "Change la façon dont le PvP fonctionne (identique au réglage du serveur). \"Remanié\" améliore les slide kicks et permet des combos de coups de poing, entre autres.",
  menu_settings_player = "Préférences",
  preset_cant_delete = "Impossible de supprimer ce préréglage !",
  preset_deleted = "Préréglage \"%s\" supprimé.",
  preset_desc = "[SAVE|LOAD|DELETE|RENAME] - Gérer les préréglages personnalisés.",
  preset_not_saved = "Ce préréglage doit être enregistré avant de pouvoir être renommé.",
  preset_save = "Enregistrer le préréglage actuel",
  preset_saved = "Préréglage enregistré sous le nom \"%s\". Pour renommer ce préréglage, utilisez /mh preset rename [nouveau nom]",
  pvp_type_classic = "Classique",
  pvp_type_revamped = "Remanié",
  tip_36 = "La casquette d'invisibilité vous protège des attaques des joueurs uniquement lorsque vous maintenez %s.",
  vanish_custom = "Maintenez \\#ffff5a\\%s\\#ffffff\\ pour éviter les attaques PvP !",
}