langdata["de"] = -- by N64 Mario
{
  -- fullname for auto select
  fullname = "German",

  -- name in the built-in menu
  name_menu = "Deutsch",

  -- global command info
  to_switch = "Gebe \"/lang %s\" ein, um die Sprache zu wechseln",
  switched = "Auf Deutsch umgestellt!",
  rule_command = "Gebe /rules ein, um diese Nachricht erneut anzuzeigen",

  -- roles
  runner = "Läufer",
  runners = "Läufer",
  short_runner = "Run",
  hunters = "Jäger",
  hunter = "Jäger",
  spectator = "Zuschauer",
  player = "Spieler",
  players = "Spieler",

  -- rules
  welcome = "Wilkommen zu \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! WIE MAN SPIELT:",
  welcome_mini = "Wilkommen zu \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! WIE MAN SPIELT:",
  welcome_mys = "Wilkommen zu \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! WIE MAN SPIELT:",
  welcome_egg = "Wilkommen zu \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! WIE MAN SPIELT:",
  all_runners = "Besiege alle \\#00ffff\\Läufer\\#ffffff\\.",
  any_runners = "Besiege alle \\#00ffff\\Läufer\\#ffffff\\.",
  shown_above = "(oben gezeigt)",
  any_bowser = "Besiege %s, \\#ffff5a\\egal durch welcher Art und Weise.\\#ffffff\\",
  collect_bowser = "Sammle \\#ffff5a\\%d Stern(e)\\#ffffff\\ und besiege %s.",
  mini_collect = "Sei der Erste, der \\#ffff5a\\einen Stern sammelt\\#ffffff\\.",
  collect_only = "Sammle \\#ffff5a\\%d Stern(e)\\#ffffff\\.",
  thats_you = "(das bist du!)",
  banned_glitchless = "NEIN: Cross-Teaming, BLJs, durch Wände clippen, hinhalten, camping.",
  banned_general = "NEIN: Cross-Teaming, stalling, camping.",
  time_needed = "%d:%02d um jeden Hauptkurs zu verlassen; Sammle Sterne zum Verringern",
  stars_needed = "%d Stern(e) werden benötigt, um jeden Hauptkurs zu verlassen",
  become_hunter = "werde \\#ff5a5a\\Jäger\\#ffffff\\, wenn du besiegt wirst",
  become_runner = "Besiege einen \\#00ffff\\Läufer\\#ffffff\\, um einer zu werden",
  infinite_lives = "Unendlich viele Leben",
  spectate = "gebe \"/spectate\" ein, um zuzuschauen",
  mini_goal = "\\#ffff5a\\Wer auch immer die meisten Sterne in %d:%02d sammelt, gewinnt\\#ffffff\\",
  fun = "Viel Spaß!",

  -- hud, extra desc, and results text
  win = "%s\\#ffffff\\ haben gewonnen!",
  can_leave = "\\#5aff5a\\Kurs kann verlassen werden",
  cant_leave = "\\#ff5a5a\\Kurs kann nicht verlassen werden",
  time_left = "Kannst in \\#ffff5a\\%d:%02d\\#ffffff\\ verlassen",
  stars_left = "Brauchst \\#ffff5a\\%d Stern(e)\\#ffffff\\ um zu verlassen",
  in_castle = "Im Schloss",
  until_hunters = "%d Sekunde(n) bis die \\#ff5a5a\\Jäger\\#ffffff\\ beginnen",
  until_runners = "%d Sekunde(n) bis die \\#00ffff\\Läufer\\#ffffff\\ beginnen",
  lives_one = "1 Leben",
  lives = "%d Leben",
  stars_one = "1 Stern",
  stars = "%d Sterne",
  no_runners = "Keine \\#00ffff\\Läufer!",
  camp_timer = "Weiter bewegen! \\#ff5a5a\\(%d)",
  game_over = "Das Spiel ist vorbei!",
  winners = "Gewinner: ",
  no_winners = "\\#ff5a5a\\Keine Gewinner!",
  on = "\\#5aff5a\\AN",
  off = "\\#ff5a5a\\AUS",
  frozen = "Eingefroren für %d",

  -- popups
  lost_life = "%s\\#ffa0a0\\ hat einen Leben verloren!",
  lost_all = "%s\\#ffa0a0\\ hat ihr ganzes Leben verloren!",
  now_role = "%s\\#ffa0a0\\ ist jetzt ein %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ hat einen Stern bekommen!",
  got_key = "%s\\#ffa0a0\\ hat einen Schlüssel bekommen!",
  rejoin_start = "%s\\#ffa0a0\\ hat zwei Minuten um erneut beizutreten.",
  rejoin_success = "%s\\#ffa0a0\\ ist das Spiel pünktlich erneut beigetreten!",
  rejoin_fail = "%s\\#ffa0a0\\ ist nicht in Zeit beigetreten.",
  using_ee = "Dies verwendet nur die Extreme Edition.",
  not_using_ee = "Dies verwendet nur die Standard Version.",
  killed = "%s\\#ffa0a0\\ hat %s getötet!",
  sidelined = "%s\\#ffa0a0\\ hat %s erledigt!",
  paused = "Du wurdest pausiert.",
  unpaused = "Du bist nicht mehr pausiert.",
  kill_combo_2 = "%s\\#ffa0a0\\ hat einen \\#ffff5a\\doppelten\\#ffa0a0\\ Kill!",
  kill_combo_3 = "%s\\#ffa0a0\\ hat einen \\#ffff5a\\dreifachen\\#ffa0a0\\ Kill!",
  kill_combo_4 = "%s\\#ffa0a0\\ hat einen \\#ffff5a\\vierfachen\\#ffa0a0\\ Kill!",
  kill_combo_5 = "%s\\#ffa0a0\\ hat einen \\#ffff5a\\fünffachen\\#ffa0a0\\ Kill!",
  kill_combo_large = "\\#ffa0a0\\Wow! %s\\#ffa0a0\\ hat \\#ffff5a\\%d\\#ffa0a0\\ Kills in Folge!",
  set_hack = "Hack auf %s eingestellt",
  incompatible_hack = "WARNUNG: Dieser Hack ist nicht kompatibel!",
  vanilla = "Das Vanilla-Spiel wird verwendet",
  omm_detected = "OMM Rebirth wurde detektiert!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth ist veraltet!\\#ffffff\\nMindestversion: %s\nDeine Version: %s",
  custom_enter = "%s\\#ffffff\\ ist beigetreten bei\n%s", -- same as coop
  hit_switch_red = "%s drückte den\n\\#df5050\\Roten Schalter!",
  hit_switch_green = "%s drückte den\n\\#50b05a\\Grünen Schalter!",
  hit_switch_blue = "%s drückte den\n\\#5050e3\\Blauen Schalter!",
  hit_switch_yellow = "%s drückte den\n\\#e3b050\\Gelben Schalter...",
  use_out = "Benutze /mh out, um alle aus diesem Level zu warpen",
  connected = "%s\\#ffff5a\\ hat den Server betreten!",    -- same as coop
  disconnected = "%s\\#ffa0a0\\ hat den Server verlassen", -- same as coop

  -- command feedback
  not_mod = "Du hast nicht die BERECHTIGUNG diesen Befehl auszuführen.",
  no_such_player = "Es gibt nicht so einen Spieler",
  bad_id = "Ungültige Spieler ID!",
  command_disabled = "Dieser Befehl ist deaktiviert.",
  change_setting = "Einstellungsänderung:",
  you_are_muted = "Du bist stummgeschaltet.",

  -- more command feedback
  bad_param = "Ungültige Parameter!",
  bad_command = "Ungültiger Command!",
  error_no_runners = "Spiel kann nicht mit 0 Läufer gestartet werden!",
  set_team = "%s's Team wurde auf '%s' eingestellt", -- First %s is player name, second is team name
  not_started = "Das Spiel hat noch nicht begonnen",
  set_lives_one = "%s hat nun einen Leben",
  set_lives = "%s hat nun %d Leben",
  not_runner = "%s ist kein Läufer",
  may_leave = "%s darf verlassen",
  must_have_one = "Es muss mindestens ein Jäger vorhanden sein",
  added = "Hinzugefügte Läufer: ", -- list comes afterward
  runners_are = "Die Läufer sind: ",
  set_lives_total = "Die Leben des Läufers ist eingestellt zu %d",
  wrong_mode = "Nicht verfügbar in diesem Modus",
  need_time_feedback = "Läufer können jetzt in %d Sekunden(n) verlassen",
  game_time = "Spiel dauert jetzt %d Sekunde(n)",
  need_stars_feedback = "Läufer brauchen jetzt %d Stern(e)",
  new_category = "Das ist jetzt ein %d Sterne run",
  new_category_any = " Das ist jetzt ein any% run",
  mode_normal = "Im Normalmodus",
  mode_swap = "Im Swap-Modus",
  mode_mini = "Im MiniHunt-Modus",
  mode_mys = "Im MysteryHunt-Modus",
  using_stars = "Sterne erforderlich wird verwendet",
  using_timer = "Timer wird verwendet",
  can_spectate = "Jäger können jetzt zuschauen",
  no_spectate = "Jäger können nicht mehr zuschauen",
  all_paused = "Alle Spieler sind pausiert",
  all_unpaused = "Alle Spieler sind nicht mehr pausiert",
  player_paused = "%s wurde pausiert",
  player_unpaused = "%s ist nicht mehr pausiert",
  hunter_metal = "Alle Jäger sind Metall",
  hunter_normal = "Alle Jäger sehen normal aus",
  hunter_glow = "All Jäger glühen rot",
  runner_normal = "Alle Läufer sehen normal aus",
  now_weak = "Alle Spieler haben Halbunbesiegbarkeitsrahmen",
  not_weak = "Alle Spieler haben normale Unbesiegbarkeitsrahmen",
  auto_on = "Spiele werden automatisch starten",
  auto_off = "Spiele werden nicht automatisch starten",

  -- team chat
  tc_toggle = "Team chat ist %s!",
  to_team = "\\#8a8a8a\\zu Team: ",
  from_team = "\\#8a8a8a\\ (Team): ",

  -- hard mode
  hard_notice = "Psst, tippe /hard...",
  extreme_notice = "Psst, tippe /hard ex...",
  hard_toggle = "\\#ff5a5a\\Harter Modus\\#ffffff\\ ist %s!",
  extreme_toggle = "\\#b45aff\\Extrem Modus\\#ffffff\\ ist %s!",
  hard_info = "Interessiert am \\#ff5a5a\\Harten Modus\\#ffffff\\?" ..
      "\n- Hälfte des Lebens" ..
      "\n- Wasser heilt nicht" ..
      "\n- \\#ff5a5a\\Ein Leben" ..
      "\n\\#ffffff\\Tippe /hard ON wenn sie für die Herausforderungen bereit sind.",
  hard_mode = "Harter Modus",
  extreme_mode = "Extrem Modus",
  hard_info_short = "Hälfte des Powermeters, Wasser heilt nicht und nur ein Leben.",
  extreme_info_short = "Einen Schadenspunkt, einen Leben und Todestimer.",

  -- spectator
  hunters_only = "Nur Jäger können zuschauen!",
  spectate_disabled = "Zuschauermodus ist deaktiviert!",
  timer_going = "Kann während des Timers nicht zuschauen!", -- now unused
  spectate_self = "Du kannst dich nicht selber zuschauen!",
  spectator_controls = "Steuerung:" ..
      "\nDPAD-UP: HUD ausschalten" ..
      "\nDPAD-DOWN: Freecam/Spieleransicht tauschen" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Spieler wechseln" ..
      "\nJOYSTICK: Bewegen" ..
      "\nA: Geh hoch" ..
      "\nZ: geh runter" ..
      "\nType \"/spectate OFF\" um abzubrechen",
  spectate_off = "Nicht mehr am zuschauen.",
  empty = "LEER (%d )",
  free_camera = "FREIE KAMERA",

  -- stats
  disp_wins_one = "%s\\#ffffff\\ hat 1 mal als \\#ffff5a\\Läufer\\#ffffff\\ gewonnen!",
  disp_wins = "%s\\#ffffff\\ hat %d mal als \\#ffff5a\\Läufer\\#ffffff\\ gewonnen!",
  disp_kills_one = "%s\\#ffffff\\ hat einen Spieler getötet!", -- unused
  disp_kills = "%s\\#ffffff\\ hat %d Spieler getötet!",
  -- for stats table
  stat_wins_standard = "Siege",
  stat_wins = "Siege (Minihunt/vor v2.3)",
  stat_wins_mys = "Siege (MysteryHunt)",
  stat_kills = "Kills",
  stat_combo = "Max Kill Streak",
  stat_wins_hard_standard = "Siege (Harter Modus)",
  stat_wins_hard = "Siege (Harter Modus, Minihunt/vor v2.3)",
  stat_wins_hard_mys = "Siege (Harter Modus, MysteryHunt)",
  stat_mini_stars = "Maximale Sterne in einem Minihunt",
  stat_wins_ex_standard = "Siege (Extrem Modus)",
  stat_wins_ex = "Siege (Extrem Modus, Minihunt/vor v2.3)",
  stat_wins_ex_mys = "Siege (Extrem Modus, MysteryHunt)",

  -- placements
  place_1 = "\\#e3bc2d\\[64T: Platz 1]",
  place_2 = "\\#c5d8de\\[64T: Platz 2]",
  place_3 = "\\#b38752\\[64T: Platz 3]",
  place = "\\#e7a1ff\\[64T: Platz %d]", -- thankfully we don't go up to 21
  place_score_1 = "%d",
  place_score_2 = "%d",
  place_score_3 = "%d",
  place_score = "%d",

  -- command descriptions
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Startet das Spiel; Fügen sie \"continue\" hinzu, um um nicht zum Anfang teleportiert zu werden; Fügen sie \"alt\" hinzu, für einen Alternativen Speicherstand; Fügen sie \"main\" hinzu, für die Hauptspeicher Datei füge \"reset\" hinzu, um den Speicherstand zurückzusetzen",
  add_desc = "[INT] - fügt die spezifische Anzahl an Läufern nach dem Zufallsprinzip hinzu",
  random_desc = "[INT] - wählt zufällig eine bestimmte Anzahl an Läufern aus",
  random_desc_hunt = "[INT] - wählt zufällig eine bestimmte Anzahl an Jägern aus",
  lives_desc =
  "[INT] - Legt die Anzahl der Leben fest, die Läufer haben, von 0 zu 99 (Notiz: 0 Leben ist immer noch 1 Leben)",
  time_desc = "[NUM] - Legt fest, wie lange Läufer maximal warten müssen, bis sie verlassen können, in Sekunden",
  stars_desc =
  "[INT] - Legt die maximale Anzahl an Sternen fest, die Läufer sammeln müssen, um verlassen zu können, from 0 to 7 (only in star mode)",
  category_desc = "[INT] - Legt die Anzahl der Sterne fest, die Läufer haben müssen, um gegen Bowser anzutreten.",
  flip_desc = "[NAME|ID] - Dreht das Team des angegebenen Spielers um",
  setlife_desc = "[NAME|ID|INT,INT] - Legt die angegebenen Leben für den angegebenen Läufer",
  leave_desc = "[NAME|ID] - Ermöglicht dem angegebenen Spieler, das Level zu verlassen, wenn die Person ein Läufer ist",
  mode_desc = "[NORMAL|SWAP|MINI] - Ändert den Spielmodus; swap ändert den Läufer wenn einer stirbt",
  starmode_desc = "[ON|OFF] - Schaltet die gesammelten Sterne anstelle der Zeit um",
  spectator_desc = "[ON|OFF] - Schaltet die Fähigkeit von Jägern, zuzuschauen",
  pause_desc = "[NAME|ID|ALL] - Schaltet den Pausenstatus für bestimmte Spieler um, oder für alle, wenn nicht angegeben",
  hunter_app_desc = "Verändert das Aussehen von Jägern.",
  runner_app_desc = "Verändert das Aussehen von Läufern.",
  hack_desc = "[STRING] - Legt den aktuellen Rom Hack fest",
  weak_desc = "[ON|OFF] - Halbiert die Unbesiegbarkeitsrahmen für alle Spieler",
  auto_desc = "[ON|OFF] - Startet Spiele automatisch",
  stalking_desc = "[ON|OFF] - Erlaube auf das Level, bei dem sich der Läufer befindet mit /stalk zu warpen",
  hidehud_desc = "- Verstecke alle HUD Elemente.",

  -- mute
  muted = "\\#ffff00\\%s\\#ffffff\\ wurde von \\#ffff00\\%s\\#ffffff\\ stummgeschaltet.",
  unmuted = "Die Stummschaltung von \\#ffff00\\%s\\#ffffff\\ wurde von \\#ffff00\\%s\\#ffffff\\ aufgehoben.",
  you_muted = "Du hast \\#ffff00\\%s\\#ffffff\\ stummgeschaltet.",
  you_unmuted = "Du hast die Stummschaltung von \\#ffff00\\%s\\#ffffff\\ aufgehoben.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ wurde automatisch stummgeschaltet.",

  -- Blocky's menu
  main_menu = "Hauptmenü",
  menu_settings = "Spieleinstellungen",
  --menu_settings_player = "Einstellungen",
  menu_rules = "Regeln",
  menu_lang = "Sprache",
  menu_misc = "Sonstiges",
  menu_exit = "Verlassen",
  menu_back = "Zurück",
  menu_stats = "Statistiken",
  menu_timer = "Speedrun-Timer",
  menu_run_random = "Läufer zufällig auswählen",
  menu_run_add = "Läufer hinzufügen",
  menu_hunt_random = "Jäger zufällig auswählen",
  menu_run_lives = "Läuferleben",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  menu_gamemode = "Spielmodus",
  menu_stars = "Sterne",
  menu_defeat_bowser = "Besiege %s",
  menu_allow_stalk = "'Stalking' erlauben",
  menu_season = "Ändert die Jahreszeit",
  menu_season_desc = "Lustige visuelle Veränderungen je nach Datum.",
  menu_countdown = "Countdown",
  menu_countdown_desc = "Wie lange Jäger warten müssen, bevor sie beginnen können.",
  menu_voidDmg = "Abgrund Schaden",
  menu_voidDmg_desc = "Schaden, der Spielern zugefügt wird, die in den Abgrund oder Treibsand fallen.",
  menu_double_health = "Doppelleben", -- is this correct?
  menu_double_health_desc = "Spieler erhalten 16 statt 8 Schadenspunkte.",
  menu_target = "Als Ziel festlegen",
  menu_mute = "Stummschalten",

  -- updater (difference for "_egg" is Luigi instead of Mario)
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ ist auf dem neuesten Stand!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ ist auf dem neuesten Stand!",
  has_update = "Ein Update ist verfügbar für \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\!",
  has_update_egg = "Ein Update ist verfügbar für \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\!",

  -- unsorted
  lang_desc = "%s - Sprache wechseln",
  got_all_stars = "Du hast genug Sterne!",
  spectate_mode = "- ZUSCHAUER MODUS -",
  menu_allow_spectate = "Zuschauen Erlauben",
  menu_hide_roles_desc = "Versteck deine Rolle vom Anzeigen im Chat.",
  menu_stop = "Stopp",
  spectate_desc =
  "[NAME|ID|OFF] - Schaue den angegeben Spieler zu, freie Kamera falls nicht angegeben, oder OFF um es auszuschalten",
  menu_stalk_run = "Warp zum Läufer Level",
  stop_desc = "- Stoppe das Spiel",
  menu_star_mode = "Sternenmodus",
  tc_desc = "[ON|OFF|MSG] - Sende eine Nachricht nur zum Team; Anmachen mit \"ON\" um es auf alle Nachrichten anzuwenden",
  stars_in_area = "%d Stern(e) sind hier verfügbar!",
  force_spectate_one = "%s muss zuschauen",
  role_cont = "\\#ff9696\\[MH Mitwerkender]",
  menu_demon_desc = "Lass dich als Läufer von einem 1-Up gejagt werden.",
  vote_pass = "Die Abstimmung hat bestanden!",
  extreme_info = "Fühlst du dich vom \\#b45aff\\Extrem Modus\\#ffffff\\ angezogen? Wie albern.\
  - Ein Leben\
  - Einen Powermeter\
  - \\#b45aff\\Todestimer\\#ffffff\\; sammle Münzen und Sterne um es zu steigern\
  Wenn dir das keine Angst macht, tippe /hard ex ON ein.",
  role_trans = "\\#ffd996\\[MH Übersetzer]",
  desync_desc = "- Versucht Desynchonisierungsfehler zu beheben",
  role_lead = "\\#9a96ff\\[Leitender MH Entwickler]",
  menu_first_timer = "Führer Todestimer",
  menu_popup_sound = "Popup-Sounds",
  stalk_desc = "[NAME|ID] - Warpt dich zu das Level, in dem sich der angegebene Spieler ist, oder zum ersten Läufer",
  blacklist_add = "%s wurde zur schwarzen Liste hinzugefügt",
  menu_hide_roles = "Verstecke meine Rollen",
  open_menu = "Geben Sie /mh ein oder drücke %s um das Menü zu öffnen",
  menu_nerf_vanish = "Unsichtbarkeitskappe schwächen",
  forcespectate_desc = "[NAME|ID|ALL] - Schalte das Erzwingen des Zuschauens für diesen Spieler oder für alle Spieler um",
  stalk = "Benutze /stalk um zum Läufer zu warpen!",
  menu_category = "Kategorie",
  stat_placement = "64 Tour Platzierung",
  menu_fast = "Schnellere Aktionen",
  default_desc = "- Einstellungen zurücksetzen",
  new_record = "\\#ffff5a\\NEUER REKORD!!!",
  anarchy_set_2 = "Jäger können ihre Mitspieler attackieren",
  menu_skip = "Überspringen",
  menu_stalk_run_desc = "Warp auf das Level, in dem sich der erste Läufer befindet.",
  no_runners_added = "Keine Läufer hinzugefügt",
  menu_exit_spectate_desc = "Zuschauermodus verlassen.",
  menu_flip = "Team wechseln",
  menu_first_timer_desc = "Gibt den Führer in MiniHunt einen Todestimer.",
  menu_save_continue = "Fortsetzen (kein zurück warpen)",
  menu_start = "Start",
  role_dev = "\\#96ecff\\[MH Entwickler]",
  menu_nerf_vanish_desc =
  "Verschlechtert die Unsichtbarkeits Kappe, indem sie umschaltbar gemacht wird und bei Verwendung schneller entleert wird.",
  menu_blacklist_list_desc = "Listet alle auf der schwarzen Liste stehenden Sterne in MiniHunt für diesen Server auf.",
  menu_pause = "Pause",
  menu_players_all = "Alle Spieler",
  menu_hunter_app = "Aussehen von Jägern",
  menu_runner_app = "Aussehen von Läufern",
  menu_toggle_all = "Alles umschalten",
  menu_blacklist_reset_desc = "Setzt die schwarze Liste auf den Standard zurück.",
  unstuck = "Es wurde versucht den aktuellen Zustand zu beheben",
  menu_blacklist_load = "Schwarze Liste laden",
  menu_blacklist_load_desc = "Laden Sie ihre gespeicherte schwarze Liste.",
  menu_blacklist_reset = "Schwarze Liste zurücksetzen",
  menu_blacklist_save_desc = "Speicher diese schwarze Liste auf ihrer Seite.",
  menu_blacklist_save = "Schwarze Liste speichern",
  menu_blacklist_list = "Alles auf der schwarze Liste auflisten",
  menu_spectate_desc = "Diesen Spieler zuschauen",
  menu_skip_desc = "- Stimme ab, um diesen Stern in MiniHunt zu überspringen.",
  menu_exit_spectate = "Zuschauen Verlassen",
  menu_spectate_run_desc = "Der erste Läufer wird automatisch zugeschaut.",
  menu_list_settings = "Einstellungen auflisten",
  menu_spectate_run = "Läufer zuschauen",
  anarchy_set_3 = "Spieler können ihre Mitspieler attackieren",
  menu_free_cam_desc = "Aktiviere die freie Kamera im Zuschauermodus.",
  menu_fast_desc = "Man wirft Gegenstände und öffnet Türen schneller.",
  menu_secret = "Das ist ein Geheimnis. Wie schaltet man es frei?",
  menu_hide_hud = "Verstecke alle HUD Elemente",
  menu_stalk = "Warpe zum Level",
  dmgAdd_set = "Läufer nehmen jetzt %d zusätzlichen Schaden durch PvP-Angriffe.",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Schalte den Harter Modus für Sie selbst um",
  menu_tc = "Team-Chat",
  is_spectator = "* SPIELER IST EIN ZUSCHAUER  *",
  menu_setlife = "Leben setzen",
  menu_allowleave = "Erlauben zu verlassen",
  menu_forcespectate = "Zuschauen erzwingen",
  menu_stalk_desc = "Warp auf das Level dieses Spielers.",
  menu_demon = "Green Demon",
  menu_spectate = "Zuschauen",
  force_spectate_off = "Zuschauen ist nicht mehr erzwungen",
  menu_dmgAdd = "Läufer MVP Schaden erhöht",
  menu_anarchy_desc = "Ermöglicht den angegebenen Teams, ihre Mitspieler anzugreifen.",
  rules_desc = "- Zeigt MarioHunt Regeln",
  rules_desc_egg = "- Zeigt LuigiHunt Regeln",
  menu_anarchy = "Teamangriff",
  menu_blacklist = "MiniHunt schwarze Liste",
  mh_desc = "[COMMAND,ARGS] - Führt Befehle aus; Geben Sie nichts oder „Menü“ ein, um das Menü zu öffnen",
  blacklist_list = "Schwarze Liste:",
  menu_auto = "Auto Spiel",
  menu_weak = "Schwacher Modus",
  menu_campaign = "Kampagne",
  menu_random = "Zufällig",
  menu_save_reset = "Alternativen Speicherstand zurücksetzen",
  ---- vanish_custom = "Halte \\#ffff5a\\%s\\#ffffff\\ um Unsichtbar zu werden!",
  menu_save_main = "Haupt",
  menu_timer_desc = "[ON|OFF] - In den Standardmodi wird unten auf dem Bildschirm ein Timer angezeigt.",
  menu_list_settings_desc = "Listet alle Einstellungen für diese Lobby auf.",
  blacklist_reset = "Die schwarze Liste zurücksetzen!",
  all = "Alle",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - Sterne auf die schwarze Liste setzen in MiniHunt",
  blacklist_remove = "%s steht auf der weißen Liste",
  page = "\\#ffff5a\\Seite %d/%d",
  menu_default = "Auf Standardeinstellung zurücksetzen",
  anarchy_set_1 = "Läufer können ihre Mitspieler attackieren",
  blacklist_remove_already = "Dieser Stern oder dieses Level steht nicht auf der schwarzen Liste.",
  force_spectate = "Jeder muss zuschauen",
  menu_save_alt = "Alternativer Speicherstand",
  menu_tc_desc = "Rede nur mit deinem Team.",
  already_voted = "Du hast bereits abgestimmt.",
  vote_info = "Geben Sie /skip ein, um abzustimmen",
  vote_skip = "%s\\#dcdcdc\\ hat dafür gestimmt, diesen Stern zu überspringen",
  blacklist_remove_invalid = "Dieser Stern oder dieses Level kann nicht auf die weiße Liste gesetzt werden.",
  no_hard_win = "Ihr Punktestand für Harte Siege oder Extrem Siege wird für dieses Spiel nicht aktualisiert.",
  death_timer = "Tod",
  blacklist_add_already = "Dieser Stern oder dieses Level ist bereits auf der schwarze Liste.",
  anarchy_set_0 = "Spieler können nicht ihre Mitspieler attackieren",
  menu_dmgAdd_desc = "Füge so viel Schaden zum Angriff gegen Läufer hinzu.",
  no_valid_star = "Konnte nicht einen gültigen Stern finden!",
  warp_spam = "Langsam mit den Warps!",
  mini_score = "Punktzahl: %d",
  stats_desc = "- Statistiktabelle ein-/ausblenden",
  force_spectate_one_off = "%s muss nicht mehr zuschauen",
  menu_time = "Zeit",
  blacklist_save = "Schwarze Liste gespeichert!",
  blacklist_load = "Schwarze Liste geladen!",
  demon_unlock = "Green Demon Modus freigeschaltet!",
  target_desc = "[NAME|ID] - Lege diesen Läufer als Ihr Ziel fest, das jederzeit seinen Standort anzeigt.",

  -- v2.6
  leave_error = "%s\\#ffa0a0\\ hat aufgrund eines Fehlers verlassen.",
  hunter_color = "Alle Jäger haben die Burgund Farbpalette",
  runner_color = "Alle Jäger haben die Azureblau Farbpalette",
  stat_playtime = "Spielzeit (Stunden)",
  stat_parkour_time = "Schnellste Parkour Zeit",
  stat_parkour_time_omm = "Schnellste Parkour Zeit (OMM)",
  stat_parkour_time_other = "Schnellste Parkour Zeit (Moveset)",
  menu_free_roam = "Frei Herumlaufen",
  menu_free_roam_desc = "- Deaktiviert die Stern- und Schlüsselanforderungen für Türen und die meisten Level.",
  menu_radar = "Radar",
  menu_radar_desc = "Zeigt an, wo sich Läufer und wichtige Objekte befinden.",
  menu_minimap = "Minikarte",
  menu_minimap_desc = "Zeigt eine Karte des gesamten Levels.",
  menu_romhack_cam = "Romhack-Kamera",                                     -- (cam is short for camera)
  menu_romhack_cam_desc = "Aktiviert die Romhack-Kamera in allen Zeiten.", -- (cam is short for camera)
  menu_star_heal = "Sternenheilung",

  -- v2.6.1
  menu_star_setting = "Beim Stern sammeln", -- from base
  star_leave = "Verlassen",                 -- is this correct?
  star_stay = "Bleiben",                    -- is this correct?
  star_nonstop = "Durchgehend",

  -- v2.7
  added_count = "%d Läufer wurden hinzugefügt",
  added_count_one = "1 Läufer wurde hinzugefügt",
  become_spectator = "werde ein \\#a9a9a9\\Zuschauer\\#ffffff\\, wenn besiegt",
  dead = "Tot",
  dead_become = "Tote \\#00ffff\\Läufer\\#ffffff\\ hinterlassen einen Körper.",
  dead_become_infection = "Tote Spieler, die nicht zu \\#ff5a5a\\Jägern\\#ffffff\\ werden, hinterlassen einen Körper.",
  dead_become_noconfirm = "Tote Spieler hinterlassen einen Körper.",
  disp_asn_bronze = "%s\\#ffffff\\ hat \\#b38752\\Bronze\\#ffffff\\ im ASN-Turnier gewonnen!",
  disp_asn_quarter = "%s\\#ffffff\\ hat das \\#70ff94\\Viertelfinale\\#ffffff\\ im ASN-Turnier erreicht!",
  disp_asn_silver = "%s\\#ffffff\\ hat \\#c5d8de\\Silber\\#ffffff\\ im ASN-Turnier gewonnen!",
  disp_asn_win = "%s hat das ASN-Turnier \\#e3bc2d\\gewonnen\\#ffffff\\!",
  disp_wins_ex = "%s\\#ffffff\\ hat %d Mal als \\#b45aff\\Läufer\\#ffffff\\ im \\#b45aff\\Extremen Modus\\#ffffff\\ gewonnen!",
  disp_wins_ex_one = "%s\\#ffffff\\ hat 1 Mal als \\#b45aff\\Läufer\\#ffffff\\ im \\#b45aff\\Extremen Modus\\#ffffff\\ gewonnen!",
  disp_wins_hard = "%s\\#ffffff\\ hat %d Mal als \\#ffff5a\\Läufer\\#ffffff\\ im \\#ff5a5a\\Schweren Modus\\#ffffff\\ gewonnen!",
  disp_wins_hard_one = "%s\\#ffffff\\ hat 1 Mal als \\#ffff5a\\Runner\\#ffffff\\ in \\#ff5a5a\\Schweren Modus\\#ffffff\\ gewonnen!",
  dmgAdd_set_ohko = "Läufer sterben jetzt durch einen treffer",
  far = "\\#8a8a8a\\(weit entfernt)",
  global_talk_end = "\\#ffa0a0\\Globaler Chat wurde beendet.",
  global_talk_start = "\\#ffa0a0\\Globaler Chat ist für %d Sekunde(n) aktiviert.",
  guard_cooldown = "Kann in %d schützen",
  guard_info = "Drücke %s, um %s zu schützen",
  guard_info_rules = "Tote Spieler können ihre Teamkollegen mit %s schützen.",
  guard_save = "\\#ffff00\\Ein Geist hat dich vor dem Tod gerettet!",
  guard_timer = "%s\\#ffff00\\ wird geschützt (%d)",
  hunter_outline = "Alle Jäger haben eine Umrandung",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Jäger\\#ffa0a0\\ verbleiben.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Jäger\\#ffa0a0\\ verbleibt.",
  players_remain = "\\#ffa0a0\\%d Spieler verbleiben.",
  players_remain_one = "\\#ffa0a0\\1 Spieler verbleibt.",
  hunters_set_count = "Es gibt %d Jäger",
  hunters_set_count_one = "Es gibt einen Jäger",
  hunters_were = "Die Jäger waren: ",
  keep_secret = "Lass dich nicht erwischen!",
  menu_binds = "Tastenbelegung ändern",
  menu_binds_desc = "Passe die Tastenbelegung für verschiedene Aktionen an.",
  menu_confirm_hunter = "Jäger Tode bestätigen",
  menu_confirm_hunter_desc = "Zeigt eine Nachricht an, wenn ein Jäger getötet wird. Wenn deaktiviert, hinterlassen Jäger auch Leichen.",
  menu_coop = "Coop",
  menu_global_chat = "Globale Chat Zeit",
  menu_global_chat_desc = "Die Zeit, wo Spieler reden können, wenn ein Körper gefunden wird.",
  menu_grace_period = "Schonzeit",
  menu_grace_period_desc = "Die Zeit, bis Spieler getötet werden können.",
  menu_guard_button = "Schützen",
  menu_guard_button_desc = "Die Taste, um einen Spieler im Zuschauermodus in MysteryHunt zu schützen.",
  menu_hunters_win_early = "Die Jäger gewinnen früh",
  menu_hunters_win_early_desc = "Die Jäger gewinnen, wenn sie genauso viele oder mehr sind als die Läufer, wie in Among Us.",
  menu_invinc_particle = "Glitzernde I-Frames",
  menu_invinc_particle_desc = "Ersetzt den \"Blinken\"-Effekt, wenn Mario Schaden nimmt durch Glitzerpartikeln.",
  menu_know_team = "Jäger kennen ihre Teamkollegen",
  menu_know_team_desc = "Jäger wissen, wer ihre Teamkollegen sind. Wenn deaktiviert, können Jäger sich gegenseitig töten.",
  menu_menu_button = "Menü öffnen",
  menu_menu_button_desc = "Die Taste(n), um das MarioHunt Menü zu öffnen.",
  menu_overlay = "Kursfortschritt Overlay",
  menu_overlay_desc = "Zeigt gesammelte Sterne, Schlüsseln und Kappenschalter in der nähe des Gemäldes oder Warps eines Kurses an.",
  menu_presets = "Voreinstellungen",
  menu_report_button = "Melden/Reparieren",
  menu_report_button_desc = "Die Taste, um einen Körper zu melden und Sabotagen zu stoppen.",
  menu_sabo = "Sabotage",
  menu_sabo_button = "Sabotage Menü öffnen",
  menu_sabo_button_desc = "Die Taste(n), um das Sabotage Menü in MysteryHunt zu öffnen.",
  menu_show_on_map = "Auf Karte zeigen",
  menu_show_on_map_desc = "Welche Teams auf der Minimap gesehen werden können (Gegner werden auch den Radar haben)",
  menu_shuffle = "Teams mischen",
  menu_shuffle_desc = "Mischt die Teams aller lebendigen Spieler in der ausgewählten Zeit",
  menu_spectate_on_death = "Läufer beobachten nach dem Tod",
  menu_stalk_timer = "Verfolgung Cooldown",
  menu_stalk_timer_desc = "Die Zeit, wo der Spieler nach /stalk gefroren ist.",
  menu_star_stay_old = "Im Level bleiben, wenn bereits gesammelt",
  menu_star_stay_old_desc = "Einen Stern sammeln, der bereits gesammelt wurde, wirft dich nicht aus dem Level.",
  menu_star_timer = "Letzte Stern Zeit",
  menu_star_timer_desc = "Zeigt, wann der letzte Stern unten auf dem Bildschirm gesammelt wurde.",
  menu_unknown = "???",
  menu_vanish_button = "Unsichtbar werden",
  menu_vanish_button_desc = "Die Taste, um die Unsichtbarkeitskappe zu aktivieren, wenn \"Unsichbarkeitskappe schwächen\" aktiv ist.",
  mystery_altgoal = "ODER: Entdecke die \\#ff5a5a\\Jäger\\#ffffff\\ und besiege sie.",
  mysteryhunt_disabled = "\\#ffa0a0\\Einer deiner Mods ist nicht mit MysteryHunt kompatibel!",
  mysteryhunt_innocent = "\\#ffa0a0\\Du hast einen unschuldigen Spieler getötet!",
  mysteryhunt_spectate = "\\#ffa0a0\\Du wirst dieses Spiel beobachten.",
  nearby = "\\#8a8a8a\\(in der Nähe)",
  no_players_here = "Hier sind keine anderen Spieler!",
  no_runners_here = "Hier sind keine anderen \\#00ffff\\Läufer\\#ffffff\\!",
  opponents = "Gegner",
  other_hunters = "Die anderen Jäger sind: ",
  place_asn = "\\#e7a1ff\\[ASN-Teilnehmer]",
  place_asn_1 = "\\#e3bc2d\\[ASN-Gewinner]",
  place_asn_2 = "\\#c5d8de\\[ASN-Silber]",
  place_asn_3 = "\\#b38752\\[ASN-Bronze]",
  place_asn_4 = "\\#70ff94\\[ASN-Viertelfinalist]",
  preset_asn = "ASN-Turnier",
  preset_asn_desc = "Die gleichen Einstellungen wie im ASN-Turnier (mit einem extra Leben).",
  press_report = "%s - Melden",
  press_fix = "%s - Korrigieren",
  preset_classic = "Klassich",
  preset_classic_desc = "Die Einstellungen wie in den alten MarioHunt Versionen.",
  preset_infection = "Infektion",
  preset_infection_desc = "Ein Jäger, der tödlich trifft! Können die Läufer überleben?",
  preset_quick = "Schnelles Spiel",
  preset_quick_desc = "30 Sterne, Freies Spiel, Kein Bowser Kampf.",
  preset_solo = "Solo",
  preset_solo_desc = "Du bist auf dich Alleine gestellt! 3 Leben und doppelte Schadenspunkte.",
  preset_star_rush = "Sternenjagd",
  preset_star_rush_desc = "Minihunt, aber jeder ist ein Läufer!",
  preset_tag = "Fangen",
  preset_tag_desc = "Triff einen Läufer, um sofort einer zu werden!",
  report_body = "%s\\#ffa0a0\\ hat %s's\\#ffa0a0\\ Körper in \\#ffff5a\\ gefunden",
  report_info_rules = "Drücke %s um sie zu melden und um zu diskutieren.",
  role_dead = "\\#ff2020\\[TOT]",
  runner_glow = "Alle Läufer glühen jetzt",
  runner_outline = "Alle Läufer haben eine Umrandung",
  runner_sparkle = "Alle Läufer funkeln jetzt",
  runners_can_kill = "\\#00ffff\\Läufer\\#ffffff\\ können Spieler besiegen, die sie für \\#ff5a5a\\Jäger\\#ffffff\\ halten.\nWenn sie einen unschuldigen töten, sterben sie auch.",
  runners_remain = "Es verbleiben noch %d \\#00ffff\\Läufer\\#ffffff\\.",
  runners_remain_one = "Es verbleibt noch ein \\#00ffff\\Läufer\\#ffffff\\.",
  sabo_activate_timer = "Aktivierung in %d",
  sabo_active = "\\#ffff00\\SABOTAGE AKTIV!",
  sabo_bomb = "\\#ff4040\\Mega Bombe",
  sabo_bomb_desc = "Tötet alle Spieler wenn sie nicht deaktiviert wird!",
  sabo_bomb_timer = "\\#ff4040\\Alle Spieler werden in %d:%02d sterben",
  sabo_cooldown = "Sabotage wird in %d:%02d wieder verwendbar sein",
  sabo_dark = "\\#5050ff\\Dunkelheit",
  sabo_dark_desc = "Verdunkelt die gesamte Welt!",
  sabo_gas = "\\#ffff32\\Giftgas",
  sabo_gas_desc = "Lässt Giftgas erscheinen!",
  sabo_info = "Drücke %s um zu sabotieren",
  sabo_info_rules = "\\#ff5a5a\\Jäger\\#ffffff\\ können Chaos mit Sabotagen verursachen.\nUm eine Sabotage zu deaktivieren, gehe zum angegebenen Level und drücke %s an der Sabotage.",
  scroll_up = "Hoch scrollen für mehr...",
  shuffle_timer = "Die Teams werden in %d gemischt",
  stat_crown = "ASN-Krone",
  stat_placement_asn = "ASN-Turnier Platzierung",
  target_hunters_only = "Nur Jäger können ein Ziel festlegen.",
  tc_only_hunter = "Nur lebende Jäger können den Team Chat nutzen.",
  unless_defeated = "außer sie werden von einem anderen Spieler besiegt",
  unsaved_changes = "\\#ff5a5a\\Du hast ungespeicherte Einstellungen! Drücke erneut, wenn du sicher bist.",
  until_grace = "%d Sekunde(n), bis die Schonzeit endet",
  voidDmg_set = "Spieler nehmen %d Schaden, wenn sie in den Abgrund oder Treibsand fallen",
  voidDmg_set_ohko = "Spieler sterben, wenn sie in den Abgrund oder Treibsand fallen.",

  -- v2.8
  default = "Default",
  gc_desc = "[MSG] - Sende eine Nachricht, die jeder sehen kann, selbst wenn du tot bist; nur für Host/Moderator",
  menu_default_role = "Standard Role",
  menu_default_role_desc = "Welches Team an neuen Spielern zugeteilt wird.",
  menu_game_area = "Spielarena",
  menu_game_area_desc = "Welche Teile des Spiels beitretbar sind. Benutze für alle Level \"Default\".",
  menu_no_player_col = "Deaktiviere Spielerkollision",
  menu_no_player_col_desc = "Verhindert, dass alle Spieler sich gegenseitig anprallen oder sich herumschubsen. PvP funktioniert noch!",
  menu_no_water_heal = "Wasser Heilt Nicht",
  menu_old_input = "Alte Steuerkreuz-Steuerung",
  menu_old_input_desc = "Ändert die Steuerung für das Steuerkreuz auf den Stand vor v2.8",
  menu_pvp_type = "PvP-Modus",
  menu_pvp_type_desc = "Ändert wie PvP funktioniert (genauso wie die Servereinstellung). \"Revamped\" macht Rutschattacken und Schläge stärker und erlaubt Schlag-Kombos, unter anderem.",
  menu_settings_player = "Präferenzen",
  mute_desc = "[NAME|ID] - Schaltet einen Spieler stumm und verhindert, dass sie chatten können.",
  out_desc = "[LEVEL|COURSE] - wirft jedem aus einem Level",
  preset_cant_delete = "Diese Voreinstellung kann nicht gelöscht werden!",
  preset_deleted = "Die Voreinstellung \"%s\" wurde gelöscht.",
  --preset_desc = "[SPEICHERN|LADEN|LÖSCHEN|UMBENENNEN] - Verwalten von benutzerdefinierten Voreinstellungen.",
  preset_desc = "[SAVE|LOAD|DELETE|RENAME] - Verwalten von benutzerdefinierten Voreinstellungen.",
  preset_not_saved = "Diese Voreinstellung muss gespeichert werden, bevor du es umbenennen kannst.",
  preset_save = "Jetzige Voreinstellung Speichern",
  preset_saved = "Voreinstellung wurde als \"%s\" gespeichert. Um diese Voreinstellung umzubenennen, benutze /mh preset rename [neuer Name]",
  pvp_type_classic = "Klassisch",
  pvp_type_revamped = "Überarbeitet",
  unmute_desc = "[NAME|ID] - Hebt die Stummschaltung eines Spielers auf und erlaubt ihm, wieder zu chatten",
  vanish_custom = "Halte \\#ffff5a\\%s\\#ffffff\\ um PvP Attacken zu vermeiden!",
}