langdata["nl"] = -- by LALIEDABBE
{
  -- fullname for auto select (make sure this matches in-game under Misc -> Languages)
  fullname = "Nederlands",

  -- name in the built-in menu
  name_menu = "Dutch",

  -- global command info
  to_switch = "Typ \"/lang %s\" om van taal te veranderen",
  switched = "Switched to Nederlands!", -- Replace "English" with the name of this language
  rule_command = "Typ /rules om dit berich nog een keer te laten zien",
  open_menu = "Typ /mh of druk op %s om het menu te openen",
  stalk = "Gebruik /stalk om te teleporteren naar de renners!",
  rules_desc = "- laat MarioHunt regels zien",
  rules_desc_egg = "- laat LuigiHunt regels zien",
  mh_desc = "[COMMAND,ARGS] - Rent commando; typ niks of \"menu\" om het menu te openen",
  lang_desc = "%s - Verander taal",
  hard_desc = "[EX|ON|OFF,ON|OFF] - Verander moeilijke modus voor jezelf",
  tc_desc = "[ON|OFF|MSG] - Stuur bericht naar alleen jou team; zet ON om toe te passen op alle berichten",
  stats_desc = "- Laat zien/Verstop statistieken tabel",
  stalk_desc = "[NAME|ID] - Teleporteert naar het level waarin de opgegeven speler zich bevindt, of naar de eerste renner",
  spectate_desc = "[NAME|ID|OFF] - Kijk naar de opgegeven speler, vrije camera indien niet gespecificeerd, of OFF om uit te schakelen", -- not to be confused with spectator_desc
  target_desc = "[NAME|ID] - Stel deze Renner in als je target, die altijd hun locatie weergeeft.",
  unsaved_changes = "\\#ff5a5a\\Je hebt onopgeslagen gegevens! Druk nogmaals als je het zeker weet.",

  -- roles
  runner = "Renner",
  runners = "Renners",
  short_runner = "Ren", -- unused
  hunters = "Jagers",
  hunter = "Jager",
  spectator = "Toeschouwer",
  player = "Speler",
  players = "Spelers",
  all = "Alle",
  dead = "Dood",
  opponents = "Tegenstanders", -- only used for the show on map setting

  -- rules
  --[[
    This is laid out as follows:
    {welcome|welcome_mini}
    {runners}{shown_above|thats_you}{any_bowser|collect_bowser|mini_collect}
    {hunters}{thats_you}{all_runners|any_runners}
    {rule_lives_one|rule_lives}{time_needed|stars_needed}{become_hunter|become_runner}
    {infinite_lives}{spectate}
    {banned_glitchless|banned_general}{fun}

    I highly recommend testing this in-game
    Also:
    \\#ffffff\\ = white (default)
    \\#00ffff\\ = cyan (for Runner team name)
    \\#ff5a5a\\ = red (for Hunter team name and popups)
    \\#ffff5a\\ = yellow
    \\#5aff5a\\ = green
    \\#b45aff\\ = purple (for Extreme Mode)
  ]]
  welcome = "Welkom bij \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\! HOE SPEEL JE:",
  welcome_mini = "Welkom bij \\#ffff5a\\Mini\\#ff5a5a\\Hunt\\#ffffff\\! HOE SPEEL JE:",
  welcome_mys = "Welkom bij \\#b45aff\\Mystery\\#ff5a5a\\Hunt\\#ffffff\\! HOE SPEEL JE:",
  welcome_egg = "Welkom bij \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\! HOE SPEEL JE:",
  all_runners = "Versla alle \\#00ffff\\Renners\\#ffffff\\.",
  any_runners = "Defeat elke \\#00ffff\\Renners\\#ffffff\\.",
  shown_above = "(hierboven weergegeven)",
  any_bowser = "Versla %s door \\#ffff5a\\elke\\#ffffff\\ betekent noodzakelijk.",
  collect_bowser = "Verzamel \\#ffff5a\\%d ster(ren)\\#ffffff\\ en versla %s.",
  mini_collect = "Wees de eerste om \\#ffff5a\\verzamel de ster\\#ffffff\\.",
  collect_only = "Verzamel \\#ffff5a\\%d ster(ren)\\#ffffff\\.",
  thats_you = "(dat ben jij!)",
  banned_glitchless = "GEEN: Cross teaming, BLJs, wall clipping, stalling, camping.", -- no longer used
  banned_general = "GEEN: Cross teaming, stalling, camping.",
  time_needed = "%d:%02d om een hoofd level te verlaten; verzamel sterren om te verminderen",
  stars_needed = "%d ster(ren) om een hoofd level te verlaten",
  become_hunter = "word \\#ff5a5a\\Jager\\#ffffff\\ wanneer je bent verslagen",
  become_runner = "versla een \\#00ffff\\Renner\\#ffffff\\ om er een te worden",
  become_spectator = "word een \\#a9a9a9\\Toeschouwer\\#ffffff\\ wanneer je bent verslagen",
  infinite_lives = "Oneindige levens",
  unless_defeated = "tenzij verslagen door een andere speler",
  spectate = "typ \"/spectate\" om toe te schouwen",
  mini_goal = "\\#ffff5a\\Wie de meeste sterren in %d:%02d verzameld wint!\\#ffffff\\",
  fun = "Veel jachtplezier!",
  keep_secret = "Wordt niet gevangen!",
  mystery_altgoal = "OF: Ontdek de \\#ff5a5a\\Jagers\\#ffffff\\ en versla ze.",
  runners_can_kill =
  "\\#00ffff\\Renners\\#ffffff\\ kunnen spelers verslaan waarvan ze vermoeden dat ze \\#ff5a5a\\Jagers\\#ffffff\\ zijn.\nAls ze een onschuldige doden, sterven ze ook.",                    -- \n is a newline
  dead_become = "Dode \\#00ffff\\Renners\\#ffffff\\ laten een lijk achter.",
  dead_become_noconfirm = "Dode spelers laten een lijk achter.",
  dead_become_infection = "Dode spelers die geen \\#ff5a5a\\Jagers\\#ffffff\\ worden laten een lijk achter.",
  report_info_rules = "Druk op %s om ze te rapporteren en te discussiëren.",
  guard_info_rules = "Dode spelers kunnen hun teamgenoten beschermen met %s.",
  sabo_info_rules =
  "\\#ff5a5a\\Jagers\\#ffffff\\ kunnen ook chaos veroorzaken met sabotages.\nOm een sabotage uit te schakelen, ga naar het vermelde level en druk op %s op de sabotage.",


  -- hud, extra desc, and results text (%s is a placeholder for names, and %d is a placeholder for a number)
  win = "%s\\#ffffff\\ wint!", -- team name is placed here
  can_leave = "\\#5aff5a\\Kan level verlaten",
  cant_leave = "\\#ff5a5a\\Kan level niet verlaten",
  time_left = "Kan level verlaten over \\#ffff5a\\%d:%02d",
  stars_left = "Je hebt \\#ffff5a\\%d ster(ren)\\#ffffff\\ om het level te verlaten",
  in_castle = "In kasteel",
  until_hunters = "%d seconde(n) totdat \\#ff5a5a\\Jagers\\#ffffff\\ beginnen",
  until_runners = "%d seconde(n) totdat \\#00ffff\\Renners\\#ffffff\\ beginnen",
  until_grace = "%d seconde(n) totdat wachtperiode eindigt",
  lives_one = "1 leven",
  lives = "%d levens",
  stars_one = "1 ster",
  stars = "%d sterren",
  no_runners = "Geen \\#00ffff\\Renners!",
  camp_timer = "Blijf bewegen! \\#ff5a5a\\(%d)",
  game_over = "Het spel is afgelopen!",
  winners = "Winnaars: ",
  no_winners = "\\#ff5a5a\\Geen winnaars!",
  death_timer = "Dood",
  mini_score = "Score: %d",
  new_record = "\\#ffff5a\\NIEUW RECORD!!!",
  on = "\\#5aff5a\\AAN",
  off = "\\#ff5a5a\\UIT",
  frozen = "Bevroren voor %d",
  shuffle_timer = "Teams veranderen in %d",
  no_runners_here = "Geen \\#00ffff\\Renners\\#ffffff\\ hier!",
  no_players_here = "Geen andere spelers hier!",

  -- popups
  lost_life = "%s\\#ffa0a0\\ verloor een leven!",
  lost_all = "%s\\#ffa0a0\\ verloor al hun levens!",
  now_role = "%s\\#ffa0a0\\ is nu een %s\\#ffa0a0\\.",
  got_star = "%s\\#ffa0a0\\ kreeg een ster!",
  got_key = "%s\\#ffa0a0\\ kreeg een sleutel!",
  rejoin_start = "%s\\#ffa0a0\\ heeft twee minuten om opnieuw deel te nemen.",
  rejoin_success = "%s\\#ffa0a0\\ deed op tijd weer mee!",
  rejoin_fail = "%s\\#ffa0a0\\ heeft niet op tijd opnieuw verbinding gemaakt.",
  leave_error = "%s\\#ffa0a0\\ verliet het spel vanwege een fout.",
  using_ee = "Dit gebruikt alleen Extreme Editie.",
  not_using_ee = "Dit gebruikt alleen Standard Editie.",
  killed = "%s\\#ffa0a0\\ heeft %s gedood!",
  sidelined = "%s\\#ffa0a0\\ heeft %s geëlimineerd!",
  paused = "Je bent gepauzeerd.",
  unpaused = "Je bent niet meer gepauzeerd.",
  kill_combo_2 = "%s\\#ffa0a0\\ kreeg een \\#ffff5a\\dubbele\\#ffa0a0\\ kill!",
  kill_combo_3 = "%s\\#ffa0a0\\ kreeg een \\#ffff5a\\drievoudige\\#ffa0a0\\ kill!",
  kill_combo_4 = "%s\\#ffa0a0\\ kreeg een \\#ffff5a\\viervoudige\\#ffa0a0\\ kill!",
  kill_combo_5 = "%s\\#ffa0a0\\ kreeg een \\#ffff5a\\vijffoudige\\#ffa0a0\\ kill!",
  kill_combo_large = "\\#ffa0a0\\Wauw! %s\\#ffa0a0\\ kreeg \\#ffff5a\\%d\\#ffa0a0\\ kills op rij!",
  set_hack = "Hack ingesteld op %s",
  incompatible_hack = "WAARSCHUWING: Hack heeft geen compatibiliteit!",
  vanilla = "Vanilla game wordt gebruikt",
  omm_detected = "OMM Rebirth gedetecteerd!",
  omm_bad_version = "\\#ff5a5a\\OMM Rebirth is verouderd!\\#ffffff\\\nMinimale versie: %s\nJouw versie: %s",
  warp_spam = "Rustig aan met de warps!",
  no_valid_star = "Kon geen geldige ster vinden!",
  custom_enter = "%s\\#ffffff\\ betrad\n%s", -- zelfde als coop
  vanish_custom = "Hou \\#ffff5a\\%s\\#ffffff\\ vast om PVP aanvallen te vermijden!",
  got_all_stars = "Je hebt genoeg sterren!",
  unstuck = "Poging om staat te herstellen",
  use_out = "Gebruik /mh out om iedereen uit dit level te teleporteren",
  stars_in_area = "%d ster(ren) beschikbaar hier!",
  demon_unlock = "Groene Demon-modus ontgrendeld!",
  hit_switch_red = "%s\\#ffa0a0\\ heeft de\n\\#df5050\\Rode Schakelaar ingedrukt!",         -- donkerrood (uniek)
  hit_switch_green = "%s\\#ffa0a0\\ heeft de\n\\#50b05a\\Groene Schakelaar ingedrukt!",     -- donkergroen (uniek)
  hit_switch_blue = "%s\\#ffa0a0\\ heeft de\n\\#5050e3\\Blauwe Schakelaar ingedrukt!",       -- donkerblauw (uniek)
  hit_switch_yellow = "%s\\#ffa0a0\\ heeft de\n\\#e3b050\\Gele Schakelaar ingedrukt...", -- oranjeachtig (uniek)
  mysteryhunt_disabled = "\\#ffa0a0\\Een van je mods is niet compatibel met MysteryHunt!",
  mysteryhunt_spectate = "\\#ffa0a0\\Je zult dit spel spectaten.",
  mysteryhunt_innocent = "\\#ffa0a0\\Je hebt een onschuldige speler gedood!",
  connected = "%s\\#ffff5a\\ is verbonden!",                                  -- zelfde als coop
  disconnected = "%s\\#ffa0a0\\ is verbroken",                             -- zelfde als coop
  report_body = "%s\\#ffa0a0\\ vond %s's\\#ffa0a0\\ lijk in \\#ffff5a\\", -- "[Level Naam]!" wordt aan het einde toegevoegd
  global_talk_start = "\\#ffa0a0\\Globale chat is ingeschakeld voor %d seconde(s).",
  global_talk_end = "\\#ffa0a0\\De globale chat is geëindigd.",
  runners_remain = "%d \\#00ffff\\Renners\\#ffffff\\ blijven over.",
  runners_remain_one = "1 \\#00ffff\\Renner\\#ffffff\\ blijft over.",
  hunters_remain = "\\#ffa0a0\\%d \\#ff5a5a\\Jagers\\#ffa0a0\\ blijven over.",
  hunters_remain_one = "\\#ffa0a0\\1 \\#ff5a5a\\Jager\\#ffa0a0\\ blijft over.",
  players_remain = "\\#ffa0a0\\%d spelers blijven over.",
  players_remain_one = "\\#ffa0a0\\1 speler blijft over.", -- zal dit überhaupt verschijnen?
  other_hunters = "Andere jagers zijn: ",
  hunters_were = "De jagers waren: ",
  chara_left = "\\#ff0000\\* %d verliet.", -- easter egg
  chara_left_one = "\\#ff0000\\* 1 verliet.",

  -- command feedback
  not_mod = "Je hebt niet de AUTORITEIT om dit commando uit te voeren, idioot!",
  no_such_player = "Zo'n speler bestaat niet",
  bad_id = "Ongeldige speler-ID!",
  command_disabled = "Dit commando is uitgeschakeld.",
  change_setting = "Wijziging instellen:",
  you_are_muted = "Je bent gedempt.",

  -- more command feedback
  bad_param = "Ongeldige parameter!",
  bad_command = "Ongeldig commando!",
  error_no_runners = "Kan het spel niet starten met 0 renners!",
  set_team = "%s's team is ingesteld op '%s'", -- First %s is player name, second is team name (now unused)
  not_started = "spel is nog niet begonnen",
  set_lives_one = "%s heeft nu 1 leven",
  set_lives = "%s heeft nu %d levens",
  not_runner = "%s is geen Renner",
  may_leave = "%s mag het level verlaten",
  must_have_one = "Moet op zijn minst 1 jager hebben",
  added = "Renners toegevoegd: ", -- list comes afterward
  no_runners_added = "Geen Renners toegevoegd",
  runners_are = "Renners zijn: ",
  hunters_set_count_one = "er is 1 jager",
  hunters_set_count = "er zijn %d jagers",
  added_count_one = "1 renner toegevoegd",
  added_count = "%d renners toegevoegd",
  set_lives_total = "Levens van renners ingesteld op %d",
  wrong_mode = "Niet beschikbaar in deze modus",
  need_time_feedback = "Renners kunnen het level nu verlaten in %d seconde(n)",
  game_time = "Spel duurt nu %d seconde(n)",
  need_stars_feedback = "Renners hebben nu %d ster(ren) nodig",
  new_category = "Dit is nu een %d star run",
  new_category_any = "Dit is nu een any% run",
  mode_normal = "In Normale modus",
  mode_swap = "In Swap-modus",
  mode_mini = "In MiniHunt modus",
  mode_mys = "In MysteryHunt modus",
  using_stars = "Gebruikt nu sterren verzameld",
  using_timer = "Gebruikt nu timer",
  can_spectate = "Jagers kunnen nu ven",
  no_spectate = "Jagers kunnen niet meer toekijken",
  all_paused = "Alle spelers gepauzeerd",
  all_unpaused = "Alle spelers niet meer gepauzeerd",
  player_paused = "%s is gepauzeerd",
  player_unpaused = "%s is niet meer gepauzeerd",
  hunter_metal = "Alle jagers zijn nu metaal",
  hunter_normal = "Alle jagers zien er nu normaal uit",
  hunter_glow = "Alle jagers gloeien nu rood",
  hunter_outline = "Alle jagers hebben nu een outline",
  hunter_color = "Alle jagers hebben nu het Bourgondische palet",
  runner_sparkle = "Alle renners schitteren nu",
  runner_normal = "Alle renners zien er nu normaal uit",
  runner_glow = "Alle renners gloeien nu",
  runner_outline = "Alle renners hebben nu een outline",
  runner_color = "Alle renners hebben nu het Azure palet",
  now_weak = "Alle spelers hebben halve onoverwinnelijkheids frames",
  not_weak = "Alle spelers hebben nu normale onoverwinnelijkheidsframes frames",
  auto_on = "Het spel zal automatisch starten",
  auto_off = "Het spel zal niet automatisch starten",
  force_spectate = "Iedereen moet toekijken",
  force_spectate_off = "Toekijken is niet langer geforceerd",
  force_spectate_one = "%s moet toekijken",
  force_spectate_one_off = "%s hoeft niet meer toe te kijken",
  blacklist_add = "%s op de zwarte lijst gezet",
  blacklist_remove = "%s op de witte lijst gezet",
  blacklist_add_already = "Die ster is al op de warte lijst.",
  blacklist_remove_already = "Die ster of level staat niet op de zwarte lijst.",
  blacklist_remove_invalid = "Kan deze ster of level niet op de witte lijst zetten.",
  blacklist_list = "Op de zwarte lijst gezet:",
  blacklist_reset = "Reset de zwarte lijst!",
  blacklist_save = "Zwarte lijst opgeslagen!",
  blacklist_load = "Zwarte lijst geladen!",
  anarchy_set_0 = "Spelers kunnen hun teamgenoten niet aanvallen",
  anarchy_set_1 = "Renners kunnen hun teamgenoten aanvallen",
  anarchy_set_2 = "Jagers kunnen hun teamgenoten aanvallen",
  anarchy_set_3 = "Spelers kunnen hun teamgenoten aanvallen",
  dmgAdd_set = "Renners zullen nu %d extra schade oplopen van PVP aanvallen.",
  dmgAdd_set_ohko = "Renners zullen nu sterven in een slag",
  voidDmg_set = "Spelers zullen %d schade oplopen door het vallen in de leegte of drijfzand.",
  voidDmg_set_ohko = "Spelers zullen meteen doodgaan door het vallen in de leegte of drijfzand.",
  target_hunters_only = "Alleen Jagers kunnen een doel instellen.",
  muted = "\\#ffff00\\%s\\#ffffff\\ werd gedempt door \\#ffff00\\%s\\#ffffff\\.",
  unmuted = "\\#ffff00\\%s\\#ffffff\\ werd ongedempt door \\#ffff00\\%s\\#ffffff\\.",
  you_muted = "Je dempte \\#ffff00\\%s\\#ffffff\\.",
  you_unmuted = "Je ontdempte \\#ffff00\\%s\\#ffffff\\.",
  mute_auto = "\\#ffff00\\%s\\#ffffff\\ werd automatisch gedempt.",
  tc_only_hunter = "Alleen levende Jagers kunnen team chat gebruiken.",
  scroll_up = "Scroll naar boven voor meer...",

  -- team chat, nearby/far tag, and guard stuff
  tc_toggle = "Team chat is %s!",
  to_team = "\\#8a8a8a\\Naar team: ",
  from_team = "\\#8a8a8a\\ (team): ",
  nearby = "\\#8a8a8a\\(dichtbij)",
  far = "\\#8a8a8a\\(verweg)",
  guard_save = "\\#ffff00\\Een geest heeft je gered voor de dood!",
  guard_info = "Druk op %s om %s te beschermen", -- first is a button, second is a name
  guard_timer = "%s\\#ffff00\\ is beschermt (%d)",
  guard_cooldown = "Kan beschermen over %d",

  -- vote skip
  vote_skip = "%s\\#dcdcdc\\ stemde om deze ster over te slaan",
  vote_info = "Typ /skip om te stemmen",
  vote_pass = "De stemming is aangenomen!",
  already_voted = "Je hebt al gestemd.",

  -- sabotage
  sabo_bomb = "\\#ff4040\\Mega Bom",
  sabo_bomb_desc = "vermoordt alle spelers als dit niet uitgeschakeld is!",
  sabo_gas = "\\#ffff32\\Giftig Gas",
  sabo_gas_desc = "Laat giftig gas verschijnen!",
  sabo_dark = "\\#5050ff\\ Duisternis",
  sabo_dark_desc = "Bedekt de wereld in Duisternis!",
  sabo_active = "\\#ffff00\\SABOTAGE ACTIEF!",
  sabo_bomb_timer = "\\#ff4040\\Iedereen zal sterven in %d:%02d",
  sabo_info = "Druk op %s om te saboteren",
  sabo_cooldown = "Kan saboteren in %d:%02d",
  sabo_activate_timer = "Activeert over %d",
  press_report = "%s - Rapporteren",
  press_fix = "%s - Repareren",

  -- hard mode
  hard_notice = "Psst, probeer eens /hard te typen...",
  extreme_notice = "Psst, eens /hard ex te typen...",
  hard_toggle = "\\#ff5a5a\\Moeilijke Modus\\#ffffff\\ is %s!",
  extreme_toggle = "\\#b45aff\\Extreme Modus\\#ffffff\\ is %s!",
  hard_info = "Geïntreseerd in \\#ff5a5a\\Moeilijke Modus\\#ffffff\\?" ..
      "\n- Halve gezondheid" ..
      "\n- Geen water regeneratie" ..
      "\n- \\#ff5a5a\\Een leven" ..
      "\n\\#ffffff\\Typ /hard ON als je klaar bent voor de uitdaging.",
  extreme_info = "Voel je je aangetrokken tot \\#b45aff\\Extreme Modus\\#ffffff\\? Hoe dwaas." ..
      "\n- Een leven" ..
      "\n- Een gezondheid" ..
      "\n- \\#b45aff\\Doodtimer\\#ffffff\\; verzamel munten en sterren om te verlengen" ..
      "\nAls dit je niet bang maakt, typ /hard ex ON.",
  no_hard_win = "Je Moeilijke Overwinningen of Extreme Overwinningen score zal niet geüpdated worden voor deze ronde.",
  hard_mode = "Moeilijke Modus",
  extreme_mode = "Extreme Modus",
  hard_info_short = "Halve gezondheid, geen water regeneratie, en een leven.",
  extreme_info_short = "Een gezondheid, een leven, en doodtimer.",

  -- spectator
  hunters_only = "Alleen Jagers kunnen toekijken!",
  spectate_disabled = "Toekijken is uitgeschakeld!",
  timer_going = "Kan niet toekijken tijdens timer!", -- now unused
  spectate_self = "Kan niet jezekf toekijken!",
  spectator_controls = "Besturingen:" ..
      "\nDPAD-UP: Zet hud uit" ..
      "\nDPAD-DOWN: Swap vrije-camera/speler zicht" ..
      "\nDPAD-LEFT / DPAD-RIGHT: Verwissel van speler" ..
      "\nJOYSTICK: Beweeg" ..
      "\nA: Ga omhoog" ..
      "\nZ: Ga omlaag" ..
      "\nTyp \"/spectate OFF\" om te annuleren",
  spectate_off = "Niet meer aan het toekijken.",
  empty = "LEEG (%d )",
  free_camera = "VRIJE-CAMERA",
  spectate_mode = "- TOEKIJKER MODUS -",
  is_spectator = '* SPELER IS EEN TOESCHOUWER  *',

  -- stats
  disp_wins_one = "%s\\#ffffff\\ heeft 1 keer gewonnen als \\#00ffff\\Renner\\#ffffff\\!",
  disp_wins = "%s\\#ffffff\\ heeft %d keren gewonnen als \\#00ffff\\Renner\\#ffffff\\!",
  disp_kills_one = "%s\\#ffffff\\ heeft 1 speler vermoord!", -- unused
  disp_kills = "%s\\#ffffff\\ Heeft %d spelers vermoordt!",
  disp_wins_hard_one = "%s\\#ffffff\\ heeft 1 keer gewonnen als \\#ffff5a\\Renner\\#ffffff\\ in \\#ff5a5a\\Moeilijke modus!\\#ffffff\\",
  disp_wins_hard = "%s\\#ffffff\\ heeft %d keren gewonnen als \\#ffff5a\\Renner\\#ffffff\\ in \\#ff5a5a\\Moeilijke modus!\\#ffffff\\",
  disp_wins_ex_one =
  "%s\\#ffffff\\ heeft 1 keer gewonnen als \\#b45aff\\Renner\\#ffffff\\ in \\#b45aff\\Extreme Modus!\\#ffffff\\",
  disp_wins_ex = "%s\\#ffffff\\ heeft %d keren gewonnen als \\#b45aff\\Renner\\#ffffff\\ in \\#b45aff\\Extreme Modus!\\#ffffff\\",
  disp_asn_quarter = "%s\\#ffffff\\ heeft de \\#70ff94\\kwart-finale\\#ffffff\\ gehaaldt in het ASN Toernooi!",
  disp_asn_bronze = "%s\\#ffffff\\ heeft \\#b38752\\brons\\#ffffff\\ gekregen in het ASN Toernooi!",
  disp_asn_silver = "%s\\#ffffff\\ heeft \\#c5d8de\\zilver\\#ffffff\\ gekregen in het ASN Toernooi!",
  disp_asn_win = "%s \\#e3bc2d\\won\\#ffffff\\ het ASN Toernooi!",
  -- for stats table
  stat_wins_standard = "Wint",
  stat_wins = "Wint (Minihunt/pre v2.3)",
  stat_wins_mys = "Wint (MysteryHunt)",
  stat_kills = "Kills",
  stat_combo = "Maximale Kill Streek",
  stat_wins_hard_standard = "Wint (Moeilijke Modus)",
  stat_wins_hard = "Wint (Moeilijke Modus, MiniHunt/pre v2.3)",
  stat_wins_hard_mys = "Wint (Moeilijke Modus, MysteryHunt)",
  stat_mini_stars = "Maximale Sterren in een ronde van MiniHunt",
  stat_placement = "64 Tour Plaatsing",
  stat_wins_ex_standard = "Wint (Extreme Modus)",
  stat_wins_ex = "Wint (Extreme Modus, MiniHunt/pre v2.3)",
  stat_wins_ex_mys = "Wint (Extreme Modus, MysteryHunt)",
  stat_playtime = "Speeltijd (Uren)",
  stat_parkour_time = "Snelste Parkour Tijd",
  stat_parkour_time_omm = "Snelste Parkour Tijd (OMM)",
  stat_parkour_time_other = "Snelste Parkour Tijd (Moveset)",
  stat_placement_asn = "ASN Toernooi Plaatsing",
  stat_crown = "ASN Kroon", -- planned for use in "Hide My Roles"

  -- placements
  place_1 = "\\#e3bc2d\\[64T: 1e Plaats]",
  place_2 = "\\#c5d8de\\[64T: 2e Plaats]",
  place_3 = "\\#b38752\\[64T: 3e Plaats]",
  place = "\\#e7a1ff\\[64T: %de Plaats]", -- thankfully we don't go up to 21
  place_asn_1 = "\\#e3bc2d\\[ASN Winnaar]",
  place_asn_2 = "\\#c5d8de\\[ASN Zilver]",
  place_asn_3 = "\\#b38752\\[ASN Brons]",
  place_asn_4 = "\\#70ff94\\[ASN Kwart-Finalist]",
  place_asn = "\\#e7a1ff\\[ASN Deelnemer]",
  place_score_1 = "%de",
  place_score_2 = "%de",
  place_score_3 = "%de",
  place_score = "%de",

  -- chat roles
  role_lead = "\\#9a96ff\\[Hoofd MH-Ontwikkelaar]",
  role_dev = "\\#96ecff\\[MH-Ontwikkelaar]",
  role_cont = "\\#ff9696\\[MH-bijdrager]",
  role_trans = "\\#ffd996\\[MH-Vertaler]",
  role_dead = "\\#ff2020\\[DOOD]",

  -- command descriptions
  page = "\\#ffff5a\\Page %d/%d", -- page for mariohunt command
  start_desc =
  "[CONTINUE|MAIN|ALT|RESET] - Start het spel; voeg \"continue\" toe om niet naar de start te warpen; voeg \"alt\" toe voor alt opgeslagen bestand; voeg \"main\" toe voor main opgeslagen bestand; voeg \"reset\" toe om het bestand te resetten",
  add_desc = "[INT] - Voegt willekeurig het opgegeven aantal Renners toe",
  random_desc = "[INT] - Kiest willekeurig het opgegeven aantal Renners",
  random_desc_hunt = "[INT] - Kiest willekeurig het opgegeven aantal jagers",
  lives_desc = "[INT] - Stelt het aantal levens in dat Renners hebben, van 0 tot 99 (let op: 0 levens is nog steeds 1 leven)",
  time_desc =
  "[NUM] - Stelt in seconden in hoeveel tijd Renners moeten wachten voordat ze het level kunnen verlaten, of hoe lang het spel duurt in MiniHunt.",
  stars_desc = "[INT] - Stelt het aantal sterren in dat Renners moeten verzamelen om te vertrekken, van 0 tot 7 (alleen in de stermodus)",
  category_desc = "[INT] - Stelt het aantal sterren in dat Renners moeten hebben om het op te nemen tegen Bowser.",
  flip_desc = "[NAME|ID] - Draait het team van de opgegeven speler om",
  setlife_desc = "[NAME|ID|INT,INT] - Stelt de opgegeven levens in voor de opgegeven renner",
  leave_desc = "[NAME|ID] - Hiermee kan de opgegeven speler het level verlaten als hij een runner is",
  mode_desc = "[NORMAL|SWAP|MINI] - Verandert de spelmodus; Swap wisselt van loper als er één sterft",
  starmode_desc = "[ON|OFF] - Schakelt tussen het gebruik van verzamelde sterren in plaats van tijd",
  spectator_desc = "[ON|OFF] - Schakelt de mogelijkheid van jagers om toe te kijken in of uit",
  pause_desc = "[NAME|ID|ALL] - Schakelt de pauzestatus in voor specifieke spelers, of voor alle spelers als deze niet zijn gespecificeerd",
  hunter_app_desc = "Verandert het uiterlijk van Jagers.",
  runner_app_desc = "Verandert het uiterlijk van Renners.",
  hack_desc = "[STRING] - Stelt de huidige rom-hack in",
  weak_desc = "[ON|OFF] - Halveert onoverwinnelijkheids frames voor alle spelers",
  auto_desc = "[ON|OFF|NUM] - Start spel automatisch",
  forcespectate_desc = "[NAME|ID|ALL] - Schakel het forceren van toeschouwers in voor deze speler of voor alle spelers",
  desync_desc = "- Pogingen om desynchronisatiefouten op te lossen",
  stop_desc = "- Stop het spel",
  default_desc = "- Zet de instellingen op standaard",
  blacklist_desc = "[ADD|REMOVE|LIST|RESET|SAVE|LOAD,COURSE,ACT] - gezwartlijstte sterren in MiniHunt",
  stalking_desc = "[ON|OFF] - Laat kromtrekken naar Renner's level toe met /stalk",
  mute_desc = "[NAME|ID] - Dempt een speler, waardoor deze niet kan chatten",
  unmute_desc = "[NAME|ID] - Heft het dempen van een speler op, zodat deze weer kan chatten",
  out_desc = "- Schopt iedereen uit dit level",

  -- Blocky's menu
  main_menu = "Hoofdmenu",
  menu_mh = "MarioHunt",
  menu_mh_egg = "LuigiHunt",
  menu_settings_player = "Voorkeuren",
  menu_rules = "Regels",
  menu_list_settings = "Toont Instellingen",
  menu_list_settings_desc = "Toont alle instellingen voor deze lobby.",
  menu_lang = "Taal",
  menu_misc = "diversen",
  menu_stats = "Statistieken",
  menu_back = "Terug",
  menu_exit = "Verlaten",

  menu_run_random = "Willekeurige Renners",
  menu_run_add = "Renners toevoegen",
  menu_hunt_random = "Willekeurige Jagers",
  menu_run_lives = "Renner Levens",
  menu_settings = "Spel instellingen",

  menu_start = "Start",
  menu_stop = "Stop",
  menu_save_main = "Main",
  menu_save_alt = "Alt Save",
  menu_save_reset = "Reset Alt Save",
  menu_save_continue = "Doorgaan (geen terugwarpen)",
  menu_random = "Willekeurig",
  menu_campaign = "Campaing",
  menu_coop = "Coop", -- unused

  menu_gamemode = "Gamemodus",
  menu_hunter_app = "Hunter-uiterlijk",
  menu_runner_app = "Renner-uiterlijk",
  menu_weak = "Zwakke modus",
  menu_allow_spectate = "Toekijken toestaan",
  menu_star_mode = "Ster Modus",
  menu_category = "Categorie",
  menu_time = "Tijd",
  menu_stars = "Sterren",
  menu_auto = "Automatisch Spel",
  menu_blacklist = "MiniHunt Zwartlijst",
  menu_default = "Terugzetten naar standaard",
  menu_anarchy = "Vriendelijk Vuur",
  menu_anarchy_desc = "Hiermee kunnen de opgegeven teams hun teamgenoten aanvallen.",
  menu_dmgAdd = "Renner krijgen meer PVP schade",    -- DMG is "damage"
  menu_dmgAdd_desc = "Voeg zoveel schade toe aan aanvallen op Renners.",
  menu_nerf_vanish = "Nerf Verdwijn pet", -- Nerf, as in to reduce power for balancing
  menu_nerf_vanish_desc = "Nerfs verdwijn-pet door deze kwetsbaar te maken voor PVP-aanvallen, tenzij een knop wordt ingedrukt.",
  menu_first_timer = "Leider DoodsTimer",
  menu_first_timer_desc = "Geeft de leider in MiniHunt een doodstimer.",
  menu_defeat_bowser = "Versla %s",
  menu_allow_stalk = "Sta stalken toe'",
  menu_countdown = "aftellen",
  menu_countdown_desc = "Hoe lang Jagers moeten wachten voordat ze beginnen.",
  menu_voidDmg = "Leegte schade",
  menu_voidDmg_desc = "Schade die wordt toegebracht aan spelers die in de leegte of drijfzand vallen.",
  menu_double_health = "Dubbele Renner Gezondheid",
  menu_double_health_desc = "Renners krijgen 16 gezondheidspunten in plaats van 8",
  menu_free_roam = "Vrij rondlopen",
  menu_free_roam_desc = "Schakelt ster- en sleutelvereisten uit voor deuren en de meeste levels.",
  menu_star_heal = "Ster genezing",
  menu_stalk_timer = "Afkoelperiode van stalken",
  menu_stalk_timer_desc = "Tijdsduur waarvoor de speler bevroren is na gebruik van /stalk.",
  menu_star_setting = "Op sterverzameling",
  menu_star_stay_old = "Blijf in level als de ster al verzameld is",
  menu_star_stay_old_desc = "Als je een ster verzamelt die al verzameld is, word je niet uit het level verwijderd.",
  menu_spectate_on_death = "Renners kijken toe nadat ze dood zijn",
  menu_shuffle = "Teamshuffle",
  menu_shuffle_desc = "Schudt de teams van elke levende speler in de geselecteerde tijdsduur",
  menu_confirm_hunter = "Bevestig de sterfgevallen van Jagers",
  menu_confirm_hunter_desc =
  "Geeft een bericht weer wanneer een Jager wordt gedood. Als ze uitgeschakeld zijn, laten Jagers ook lijken achter.",
  menu_global_chat = "Wereldwijde chattijd",
  menu_global_chat_desc = "Tijd spelers kunnen spreken als er een lijk gevonden is.",
  menu_grace_period = "wachtperiode",
  menu_grace_period_desc = "Tijd totdat spelers gedood kunnen worden.",
  menu_know_team = "Jagers weten wie hun teamgenoten zijn",
  menu_know_team_desc = "Jagers weten wie hun teamgenoten zijn. Als dit uitgeschakeld is, kunnen jagers elkaar doden.",
  menu_hunters_win_early = "Jagers winnen vroeg",
  menu_hunters_win_early_desc = "Jagers winnen als ze hetzelfde aantal zijn als de Renners of als ze dat aantal overtreffen, zoals in Among Us.",
  menu_show_on_map = "Toon op kaart",
  menu_show_on_map_desc = "Welke teams zijn te zien op de minimap (tegenstanders hebben ook de radar)",
  menu_presets = "Voorinstellingen",
  menu_sabo = "Sabotage",
  star_leave = "Verlaten",
  star_stay = "Blijven",
  star_nonstop = "Non-Stop",

  menu_flip = "Verander van team",
  menu_spectate = "Toekijken",
  menu_stalk = "Warp naar dit Level",
  menu_stalk_desc = "Warp naar het level van deze speler.",
  menu_pause = "Pauze",
  menu_forcespectate = "Dwing om toe te kijken",
  menu_allowleave = "Sta toe om te verlaten",
  menu_setlife = "Stel levens in",
  menu_players_all = "Alle Spelers",
  menu_target = "Instellen als doel",
  menu_mute = "Dempen",

  menu_timer = "Speedrun-Timer",
  menu_timer_desc = "[ON|OFF] - Toon een timer onder aan het scherm in de standaardmodus.",
  menu_tc = "Team Chat",
  menu_tc_desc = "Chat alleen met jouw team.",
  menu_demon = "Groene Demon", -- referring to the 1-Up
  menu_demon_desc = "Laat een 1-Up je achtervolgen als Renner.",
  menu_unknown = "???",
  menu_secret = "Dit is een geheim. Hoe ontgrendel je het?",
  menu_hide_roles = "Verberg mijn rollen",
  menu_hide_roles_desc = "Verberg je rollen voor weergave in de chat.",
  menu_hide_hud = "veberg HUD",
  hidehud_desc = "- Verberg alle HUD-elementen.",
  menu_fast = "Snellere acties",
  menu_fast_desc = "Je herstelt, gooit voorwerpen en opent deuren sneller.",
  menu_popup_sound = "Pop-up geluiden",
  menu_season = "Seizoensgebonden veranderingen",
  menu_season_desc = "Leuke visuele veranderingen afhankelijk van de datum.",
  menu_radar = "Radar",
  menu_radar_desc = "Laat zien waar Renners en belangrijke objecten zijn.",
  menu_minimap = "Minimap",
  menu_minimap_desc = "Toont een kaart van het hele level.",
  menu_romhack_cam = "Romhack-Camera",                               -- (cam is short for camera)
  menu_romhack_cam_desc = "Schakelt te allen tijde de romhack-camera in.", -- (cam is short for camera)
  menu_invinc_particle = "Sparkelende onoverwinnelijkheids- frames",                      -- (I-Frames is short for invincibility/invulnerability frames)
  menu_invinc_particle_desc = "Vervangt het \"blinking\" effect wanneer Mario (of een ander personage) schade oploopt met fonkelende deeltjes.",
  menu_star_timer = "Laatste ster-tijd",
  menu_star_timer_desc = "Laat onderaan het scherm zien wanneer de laatste ster is verzameld.",
  menu_overlay = "Overlay voor level-voortgang",
  menu_overlay_desc = "Toont verzamelde sterren, sleutels en pet-schakelaars in de buurt van het schilderij of de warp van een level.",
  menu_binds = "Wijzig bindingen",
  menu_binds_desc = "Wijzig de knoppen die voor verschillende acties worden gebruikt.",

  -- binds menu
  menu_vanish_button = "Verdwijn",
  menu_vanish_button_desc = "Knop ingedrukt om de verdwijn pet te activeren wanneer\"Nerf Vanish Cap\" actief is.",
  menu_menu_button = "Open Menu",
  menu_menu_button_desc = "Knop(pen) ingedrukt om het MarioHunt-menu te openen.",
  menu_report_button = "Rapporteren/repareren",
  menu_report_button_desc = "Knop die wordt gebruikt om lijken te melden en sabotages te stoppen in MysteryHunt.",
  menu_guard_button = "Bewaker",
  menu_guard_button_desc = "Knop ingedrukt om een speler te bewaken in de toeschouwermodus in MysteryHunt.",
  menu_sabo_button = "Open Sabotage Menu",
  menu_sabo_button_desc = "Knop(pen) ingedrukt om het Sabotagemenu in MysteryHunt te openen.",

  menu_free_cam_desc = "Ga naar de vrije-camera in de toeschouwermodus.",
  menu_spectate_run = "Bekijk Renner",
  menu_spectate_run_desc = "Kijk automatisch naar de eerste Runner.",
  menu_exit_spectate = "Verlaat toeschouwer-modus",
  menu_exit_spectate_desc = "Verlaat toeschouwer-modus.",
  menu_stalk_run = "Warp naar level waar Renner in is",
  menu_stalk_run_desc = "Warp naar het level waar de eerste Runner zich in bevindt.",
  menu_skip = "Overslaan",
  menu_skip_desc = "- Stem om deze ster over te slaan in MiniHunt.",

  menu_spectate_desc = "Bekijk deze speler.",

  menu_blacklist_list = "Toon alle gezwartlijstte",
  menu_blacklist_list_desc = "Toon alle gezwartlijstte sterren in MiniHunt voor deze server.",
  menu_blacklist_save = "Sla Zwartlijst op",
  menu_blacklist_save_desc = "Sla deze Zwartlijst op aan jouw einde",
  menu_blacklist_load = "Laad Zwartlijst",
  menu_blacklist_load_desc = "Laad jouw opgeslagen zwartlijst.",
  menu_blacklist_reset = "Reset Zwartlijst",
  menu_blacklist_reset_desc = "Zet de zwarte lijst terug naar standaard.",
  menu_toggle_all = "Schakel alles om",

  -- presets
  preset_quick = "Snel spel",
  preset_quick_desc = "30 Sterren, Vrij Rondlopen, Geen Bowser run.",
  preset_infection = "Infectie",
  preset_infection_desc = "1 jager die in één keer kan doden! Kunnen de Renners overleven??",
  preset_solo = "Alleen",
  preset_solo_desc = "Je bent alleen! met 3 levens en dubbele gezondheid.",
  preset_tag = "Tikkertje",
  preset_tag_desc = "Raak een Renner om er meteen een te worden!",
  preset_star_rush = "Sterren Haast",
  preset_star_rush_desc = "Minihunt, maar iedereen is een Renner!",
  preset_classic = "Klassiek",
  preset_classic_desc = "Verandert de instellingen zodat ze overeenkomen met oude versies van MarioHunt.",
  preset_asn = "ASN Toernooi",
  preset_asn_desc = "Dezelfde instellingen gebruikt in het ASN toernooi (met 1 extra leven).",

  -- updater (now obsolete)
  up_to_date = "\\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\ is up to date!",
  up_to_date_egg = "\\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\ is up to date!",
  has_update = "Er is een update beschikbaar voor \\#00ffff\\Mario\\#ff5a5a\\Hunt\\#ffffff\\!",
  has_update_egg = "Er is een update beschikbaar voor \\#5aff5a\\Luigi\\#ff5a5a\\Hunt\\#ffffff\\!",

  -- tips
  tip = "Tip: ",
  tip_1 = "Druk op %s of typ /mh om het menu te openen. Je kunt hier instellingen configureren!",
  tip_2 = "Grond-stoten veroorzaken 4 schade aan andere spelers.",
  tip_3 = "Een trap veroorzaakt 2 schade en zorgt ervoor dat spelers vliegen!",
  tip_4 =
  "Voor commando's zoals /spectate en /target kun je gedeeltelijke namen invoeren en deze werken nog steeds (bijvoorbeeld: als je \"Emily\" invoert, wordt dit verwezen naar EmilyEmmi)",
  tip_5 = "Je kunt de instellingen halverwege het spel wijzigen in het menu.",
  tip_6 = "Als er iets misgaat, typ je /mh pause om alle spelers te pauzeren. Typ het nogmaals om te hervatten.",
  tip_7 = "Is er iemand die spamt of aanstootgevende dingen zegt? Gebruik /mh mute om ze te dempen!",
  tip_8 = "Je kunt het spel pauzeren voordat je een ster of sleutel verzamelt en het level verlaten om de animatie over te slaan.",
  tip_9 = "Je kunt een Renner targeten met /target. Hierdoor wordt hun locatie bovenaan het scherm weergegeven.",
  tip_10 = "Je kunt persoonlijke instellingen configureren in het menu (%s).",
  tip_11 = "Je hoeft de server niet opnieuw op te starten! Selecteer \"Reset Alt Save\" in \"Start\" om alle voortgang te resetten.",
  tip_12 = "Je kunt de Renner rol verkrijgen door een Renner te verslaan.",
  tip_13 = "Net als in vanilla Mario 64 tellen 0 levens nog steeds als een leven.",
  tip_14 = "Grote glitches, zoals LBLJ, zijn nutteloos buiten Any%.",
  tip_15 = "Borden in het spel kunnen meer nuttige tips bevatten!",
  tip_16 = "Dire Dire Docks mag met één ster minder worden betreden dan de daadwerkelijke categorie.",
  tip_17 = "Zet Cappy op \"Damage\" om hem als afstandswapen te gebruiken. Hij richt 1 schade aan.",
  tip_18 = "Cappy kan voorwerpen oppakken, zoals munten en geheimen.",
  tip_19 = "Gebruik de D-Pad om Cappy in verschillende richtingen te gooien.",
  tip_20 = "Bekijk de video van Key's Artwork's op YouTube voor meer informatie over OMM-technologie!",
  tip_21 =
  "Als objecten in een level beginnen te verdwijnen of warps niet meer werken, gebruik dan /mh out in dat level om dat level te forceren om opnieuw te laden.",
  tip_22 = "Gebruik /mh desync als u denkt dat er een desynchronisatiefout is opgetreden.",
  tip_23 = "Als je een andere speler doodt, wordt al je gezondheid hersteld.",
  tip_24 = "Je kunt de voortgang van Sleutels, petten en geheime levels zien in het pauzemenu in het kasteel.",
  tip_25 = "Renners kunnen elkaar in deze modus pijn doen!",
  tip_26 = "Van het level afvallen in pet levels telt ook als een leven verliezen.",
  tip_27 = "Blauwe munten-schakelaars zullen respawnen",
  tip_28 = "Je kunt een andere act kiezen om Hunters af te werpen.",
  tip_29 = "Het is een feestdag! Als de effecten je niet bevallen, schakel dan \"Seasonal Changes\" uit in het menu.",
  tip_30 = "Je kunt Renners bespioneren met /spectate.",
  tip_31 = "Gebruik /stalk om naar een level te gaan waarop een andere Renner zich bevindt!",
  tip_32 = "Het leren van speedrunning-technieken is een goede manier om je spel te verbeteren.",
  tip_33 = "Je kunt door Whomps heen gaan door op de grond te stoten of te schoppen terwijl ze vallen.",
  tip_34 = "De snelste manier om een driedubbele sprong uit te voeren is door te trappen voor de eerste sprong.",
  tip_35 = "De metale vorm veroorzaakt dubbele schade aan tegenstanders.",
  tip_36 = "De Vanish Cap beschermt je alleen tegen aanvallen van spelers als je %s vasthoudt.",
  tip_37 = "De duur van speciale petten lopen niet leeg in kanonnen.",
  tip_38 = "Blijf niet te lang bij de Act Select hangen!",
  tip_39 = "Duiken is sneller en als je in een andere speler duikt, kun je aanvallen ontwijken.",
  tip_40 = "Van een level afvallen zal schade aanrichten in plaats van je onmiddellijk te doden.",
  tip_41 = "1-Ups herstellen 4 gezondheidspunten.",
  tip_42 = "Gebruik het Spelers-menu voor opdrachten die op een specifieke speler zijn gericht, zoals het omdraaien van teams.",
  tip_43 = "Met het MarioHunt-menu kun je rondes starten en spelinstellingen configureren.",
  tip_44 = "Je kunt je chat-rol verbergen in Instellingen.",
  tip_45 = "Renners die de metalen pet dragen, kunnen nog steeds gewond raken door Jagers.",
  tip_46 = "Zorg ervoor dat je in het menu op A drukt om uw gewijzigde instellingen op te slaan!",

  -- v2.8
  default = "Standaard",
  gc_desc = "[MSG] - Verend een bericht die iedereen kan zien, zelfs als je dood bent; alleen voor host/mod",
  menu_default_role = "Standaard Rol",
  menu_default_role_desc = "Welk team wordt toegewezen aan nieuwe spelers.",
  menu_game_area = "Game Gebied",
  menu_game_area_desc = "Welke delen van het spel toegankelijk zijn. Gebruik \"Default\" voor alle levels.",
  menu_no_player_col = "Spelerbotsingen uitschakelen",
  menu_no_player_col_desc = "Voorkomt dat spelers tegen elkaar aan botsen of duwen. PvP werkt nog steeds!",
  menu_no_water_heal = "Geen Water Regeneratie",
  menu_old_input = "Oude menupijlbedieningen",
  menu_old_input_desc = "Veranderd de bedieningselementen voor pijlselectie naar hoe ze waren vóór versie 2.8.",
  menu_pvp_type = "PvP Modus",
  menu_pvp_type_desc = "Verander hoe PvP werkt (hetzelfde als de serverinstellingen). \"Revamped\" verbetert onder andere slide kicks en maakt stootcombinaties mogelijk.",
  preset_cant_delete = "Deze voorinstelling kan niet worden verwijderd!",
  preset_deleted = "Voorinstelling \"%s\" verwijderd.",
  preset_desc = "[SAVE|LOAD|DELETE|RENAME] - Aangepaste instellingen beheren.",
  preset_not_saved = "Deze voorinstelling moet worden opgeslagen voordat je deze kunt hernoemen.",
  preset_save = "Huidige voorinstelling opslaan",
  preset_saved = "Voorinstelling opgeslagen als \"%s\". Om deze voorinstelling te veranderen, gebruik /mh preset rename [new name]",
  pvp_type_classic = "Klassiek",
  pvp_type_revamped = "Vernieuwd",
}